#!/usr/bin/env zsh

if [[ "$1" == '-a' ]]; then
  ANIMATE=true
  NAME="$2"
  EXTRA="$3"
else
  ANIMATE=false
  NAME="$1"
  EXTRA="$2"
fi


function frame {
  # put some whitespaces before
  # so that the cursor is not over the display
  echo -ne "    $1\033[0K\r"
  sleep 0.2
}

function upside-down {
  local text="$1"
  local result_text

  # can't use tr on non ascii characters...
  for (( i=0; i<${#text}; i++ )); do
    case "${text:$i:1}" in
      'a') result_text+='ɐ' ;;
      'b') result_text+='q' ;;
      'c') result_text+='ɔ' ;;
      'd') result_text+='p' ;;
      'e') result_text+='ǝ' ;;
      'f') result_text+='ɟ' ;;
      'g') result_text+='ɓ' ;;
      'h') result_text+='ɥ' ;;
      'i') result_text+='ᴉ' ;;
      'j') result_text+='ɾ' ;;
      'k') result_text+='ʞ' ;;
      'l') result_text+='l' ;;
      'm') result_text+='ɯ' ;;
      'n') result_text+='u' ;;
      'o') result_text+='o' ;;
      'p') result_text+='d' ;;
      'q') result_text+='b' ;;
      'r') result_text+='ɹ' ;;
      's') result_text+='s' ;;
      't') result_text+='ʇ' ;;
      'u') result_text+='n' ;;
      'v') result_text+='ʌ' ;;
      'w') result_text+='ʍ' ;;
      'x') result_text+='x' ;;
      'y') result_text+='ʎ' ;;
      'z') result_text+='z' ;;
    esac
  done

  echo "$result_text" | rev
}

function fliptable {
  local text="$1"
  local upside_down_text=$( upside-down ${text} )

  if ! $ANIMATE; then
    if [[ -n "${text}" ]]; then
      echo "(╯°□°)╯︵${upside_down_text}"
    else
      echo '(╯°□°)╯︵┻━┻'
    fi
    return
  fi

  if [[ -n "${text}" ]]; then
    frame "( °-°) ${text}"
    frame "( °-°) ${text}"
    frame "( °-°) ${text}"
    frame "( °-°) ${text}"
    frame "( °□°) ${text}"
    frame "(╯°□°)╯${text}"
    frame "(╯°□°)╯︵ ${upside_down_text}"
    frame "(╯°□°)╯        ${upside_down_text}"
    frame "(╯°□°)╯           ${upside_down_text}"
  else
    frame '( °-°) ┬─┬'
    frame '( °-°) ┬─┬'
    frame '( °-°) ┬─┬'
    frame '( °-°) ┬─┬'
    frame '( °□°) ┬─┬'
    frame '(╯°□°)╯┬─┬'
    frame '(╯°□°)╯︵ ┻━┻'
    frame '(╯°□°)╯        ┻━┻'
    frame '(╯°□°)╯           ┻━┻'
  fi

  echo
}

function cool {
  if ! $ANIMATE; then
    echo '(⌐■_■)'
    return
  fi

  frame '( •_•)'
  frame '( •_•)'
  frame '( •_•)'
  frame '( •_•)'
  frame '( •_•)     ⌐■-■'
  frame '( •_•)   ⌐■-■'
  frame '( •_•)>⌐■-■'
  frame '(⌐■_■)'
  echo
}

function shrug {
  if ! $ANIMATE; then
    echo '¯\_(ツ)_/¯'
    return
  fi

  frame '_╭-(ツ)-╮_'
  frame '_╭-(ツ)-╮_'
  frame '_╭-(ツ)-╮_'
  frame '_╭-(ツ)-╮_'
  frame '¯\_(ツ)_/¯'
  echo
}

function disapprove {
  if ! $ANIMATE; then
    echo 'ಠ_ಠ'
    return
  fi

  frame 'ʘ‿ʘ'
  frame 'ʘ‿ʘ'
  frame 'ʘ‿ʘ'
  frame 'ʘ‿ʘ'
  frame 'ʘ_ʘ'
  frame 'ʘ_ʘ'
  frame 'ಠ_ಠ'
  echo
}

function happygary {
  if ! $ANIMATE; then
    echo 'ᕕ(ᐛ)ᕗ'
    return
  fi

  frame 'ᕕ(ᐛ)ᕗ'
  frame 'ᕕ(ᐛ)ᕗ'
  frame 'ᕙ(ᐖ)ᕡ'
  frame 'ᕙ(ᐖ)ᕡ'
  frame 'ᕕ(ᐛ)ᕗ'
  frame 'ᕕ(ᐛ)ᕗ'
  frame 'ᕙ(ᐖ)ᕡ'
  frame 'ᕙ(ᐖ)ᕡ'
  frame 'ᕕ(ᐛ)ᕗ'
  echo
}


$NAME $EXTRA 2> /dev/null
