#!/usr/bin/env zsh

function frame {
  echo -ne "    $1\033[0K\r"
  sleep 0.2
}

echo
frame '( °-°) ┬─┬'
frame '( °-°) ┬─┬'
frame '( °-°) ┬─┬'
frame '( °-°) ┬─┬'
frame '( °□°) ┬─┬'
frame '(╯°□°)╯┬─┬'
frame '(╯°□°)╯︵ ┻━┻'
frame '(╯°□°)╯        ┻━┻'
frame '(╯°□°)╯ FUUU   ┻━┻'
echo
