#!/usr/bin/env zsh

FORCE_INTERACTIVE=false

if [[ "$1" = '-i' ]]; then
  FORCE_INTERACTIVE=true
  topic="$2"
else
  topic="$1"
fi

if man "${topic}" &> /dev/null; then
  colored_man "${topic}"
elif "${topic}" --help &> /dev/null; then
  if $FORCE_INTERACTIVE; then
    "${topic}" --help | less
  else
    "${topic}" --help | less -FX
  fi
else
  if $FORCE_INTERACTIVE; then
    echo "no help for ${topic} :(" \
      && read -s -d q
  else
    echo "no help for ${topic} :("
  fi
fi
