all: sway-docs

sway-docs:
	mkdir -p $(DESTDIR)$(DATA_DIR)/man/man1

	scdoc < files/docs/sway/sway-app-chat.scd                  > $(DESTDIR)$(DATA_DIR)/man/man1/way-app-chat.1
	scdoc < files/docs/sway/sway-app-mail.scd                  > $(DESTDIR)$(DATA_DIR)/man/man1/way-app-mail.1
	scdoc < files/docs/sway/sway-app-monitor.scd               > $(DESTDIR)$(DATA_DIR)/man/man1/way-app-monitor.1
	scdoc < files/docs/sway/sway-app-music.scd                 > $(DESTDIR)$(DATA_DIR)/man/man1/way-app-music.1
	scdoc < files/docs/sway/sway-app-news.scd                  > $(DESTDIR)$(DATA_DIR)/man/man1/way-app-news.1
	scdoc < files/docs/sway/sway-app-tmux-env.scd              > $(DESTDIR)$(DATA_DIR)/man/man1/way-app-tmux-env.1
	scdoc < files/docs/sway/sway-command-input-exec.scd        > $(DESTDIR)$(DATA_DIR)/man/man1/sway-command-input-exec.1
	scdoc < files/docs/sway/sway-command-input.scd             > $(DESTDIR)$(DATA_DIR)/man/man1/way-command-input.1
	scdoc < files/docs/sway/sway-create-workspace.scd          > $(DESTDIR)$(DATA_DIR)/man/man1/way-create-workspace.1
	scdoc < files/docs/sway/sway-focus-window-title.scd        > $(DESTDIR)$(DATA_DIR)/man/man1/way-focus-window-title.1
	scdoc < files/docs/sway/sway-fzf-launcher.scd              > $(DESTDIR)$(DATA_DIR)/man/man1/way-fzf-launcher.1
	scdoc < files/docs/sway/sway-launch-app.scd                > $(DESTDIR)$(DATA_DIR)/man/man1/way-launch-app.1
	scdoc < files/docs/sway/sway-launch-command.scd            > $(DESTDIR)$(DATA_DIR)/man/man1/way-launch-command.1
	scdoc < files/docs/sway/sway-launch-password.scd           > $(DESTDIR)$(DATA_DIR)/man/man1/way-launch-password.1
	scdoc < files/docs/sway/sway-launch-system.scd             > $(DESTDIR)$(DATA_DIR)/man/man1/way-launch-system.1
	scdoc < files/docs/sway/sway-launch-tmux-env.scd           > $(DESTDIR)$(DATA_DIR)/man/man1/way-launch-tmux-env.1
	scdoc < files/docs/sway/sway-launcher.scd                  > $(DESTDIR)$(DATA_DIR)/man/man1/way-launcher.1
	scdoc < files/docs/sway/sway-move-window-new-workspace.scd > $(DESTDIR)$(DATA_DIR)/man/man1/way-move-window-new-workspace.1
	scdoc < files/docs/sway/sway-rename-workspace.scd          > $(DESTDIR)$(DATA_DIR)/man/man1/way-rename-workspace.1
	scdoc < files/docs/sway/sway-run-command.scd               > $(DESTDIR)$(DATA_DIR)/man/man1/way-run-command.1
