sway-create-workspace(1perso)

# NAME

sway-create-workspace - Create a new sway workspace

# SYNOPSIS

sway-create-workspace [ _name_ ]

# DESCRIPTION

Create a new sway workspace in the focused output.

The workspace is created with the next successive number of the workspaces
from the focused output.

# OPTIONS

None

# OPERANDS

_name_
	Name to give to the new workspace

# ENVIRONMENT VARIABLES

None

# FILES

None

# DEPENDENCIES

- jq
- swaymsg
