sway-move-workspace-direction(1perso)

# NAME

sway-move-workspace-direction - Move current workspace in direction

# SYNOPSIS

sway-move-workspace-direction _direction_

# DESCRIPTION

Move current workspace in direction in current output.

# OPTIONS

None

# OPERANDS

_direction_
	Direction of the move.++
Valid directions are:++
- _prev_++
- _next_

# ENVIRONMENT VARIABLES

None

# FILES

None

# DEPENDENCIES

- jq
- sway-move-workspace-index
- swaymsg
