sway-command-input(1)

# NAME

sway-command-input - Open window for user input for running sway command

# SYNOPSIS

sway-command-input _args_

# DESCRIPTION

Open a window for user input to run sway command. It focus current window if it
already exists.

# OPERANDS

_args_
	*sway-command-input-exec*(1) arguments

# DEPENDENCIES

- alacritty
- sway-command-input-exec
- sway-focus-window-title
- swaymsg
