sway-toggle-window-idle-inhibitor(1perso)

# NAME

sway-toggle-window-idle-inhibitor - Toggle the idle inhibitor of current window

# SYNOPSIS

sway-toggle-window-idle-inhibitor _property_

# DESCRIPTION

Toggle the inhibition of idle state from current window

# OPTIONS

None

# OPERANDS

_property_
	Property of the window to inhibit idle state++
see *sway*(5) inhibit_idle command for valid properties

# ENVIRONMENT VARIABLES

None

# FILES

None

# DEPENDENCIES

- jq
- swaymsg
