sway-launch-task(1)

# NAME

sway-launch-task - Launcher to start a task

# SYNOPSIS

sway-launch-task [_fzf_options_...]

# DESCRIPTION

Open a launcher window to start a task:
- start time tracker
- start a pomodoro session (optional)
- enable "Do not disturb" mode (optional)

# OPTIONS

None

# OPERANDS

_fzf_option_
	*fzf* option

# ENVIRONMENT VARIABLES

None

# FILES

None

# DEPENDENCIES

- do-not-disturb
- fzf
- pomodoro
- time-tracker
