ctags:
	@echo -n "… setup ctags"

    # create necessary directories
	@mkdir -p "$(HOME)/.ctags.d"

    # copy config files
	@cp "ctags/main.ctags" "$(HOME)/.ctags.d/main.ctags"

	@echo -e "\r✔ setup ctags"
