i3blocks:
	@echo -n "… setup i3blocks"

    # create necessary directories
	@mkdir -p "$(CONFIG_DIR)/i3blocks"

    # copy config files
	@cp "i3blocks/config" "${CONFIG_DIR}/i3blocks/config"

	@echo -e "\r✔ setup i3blocks"
