mopidy:
	@echo -n "… setup mopidy"

    # create necessary directories
	@mkdir -p "$(CONFIG_DIR)/mopidy"

    # copy config files
	@cp "mopidy/mopidy.conf" "$(CONFIG_DIR)/mopidy/mopidy.conf"

	@echo -e "\r✔ setup mopidy"
