httpie:
	@echo -n "… setup httpie"

    # create necessary directories
	@mkdir -p "$(HOME)/.httpie"

    # copy config files
	@cp "httpie/config.json" "$(HOME)/.httpie/config.json"

	@echo -e "\r✔ setup httpie"
