#! /usr/bin/env zsh

# try to focus existing window if it exists
FOCUS=$(swaymsg -t command '[title="sway_mail"]' focus)
[[ ! "${FOCUS}" =~ 'error' ]] && exit

# launch new app otherwise
# needs a shell started before to have correct GPG_TTY
# so that the pinentry is displayed in the new terminal
swaymsg -t command \
  exec "termite \
          --title sway_mail \
          --exec 'zsh -c neomutt'"
