#! /usr/bin/env zsh

TITLE='sway_music'

# try to focus existing window if it exists
focus_window_title "${TITLE}" && exit

# launch new app otherwise
swaymsg -t command \
  exec "termite \
          --title ${TITLE} \
          --exec ncmpcpp"

# focus the window (not automatic if different workspace)
# need to wait a bit for the window to be registered
sleep 0.1
focus_window_title "${TITLE}"
