#! /usr/bin/env zsh

TITLE='sway_projects'

# try to focus existing window if it exists
focus_window_title "${TITLE}" && exit

# launch new app otherwise
# needs TERM defined properly beforehand
# for proper color within vim
swaymsg -t command \
  exec "termite \
          --title ${TITLE} \
          --exec 'sh -c \"TERM=xterm-256color tmux\"'"

# focus the window (not automatic if different workspace)
# need to wait a bit for the window to be registered
sleep 0.1
focus_window_title "${TITLE}"
