#!/usr/bin/env zsh

TITLE='sway_monitor'

# try to focus existing window if it exists
focus_window_title "${TITLE}" && exit

# launch new app otherwise
#
# HACK: need to set termite size at start,
# also present in sway rules, to have it respected
# and to have the window centered when floating
swaymsg -t command \
  exec "termite \
          --title \"${TITLE}\" \
          --exec htop \
          --geometry 1500x1000"

# focus the window (not automatic if different workspace)
# need to wait a bit for the window to be registered
sleep 0.1
focus_window_title "${TITLE}"
