#! /usr/bin/env zsh

# try to focus existing window if it exists
FOCUS=$(swaymsg -t command '[title="sway_projects"]' focus)
[[ ! "${FOCUS}" =~ 'error' ]] && exit

# launch new app otherwise
# needs TERM defined properly beforehand
# for proper color within vim
swaymsg -t command \
  exec "termite \
         --title sway_projects \
         --exec 'sh -c \"TERM=xterm-256color tmux\"'"
