#! /usr/bin/env zsh

TITLE='sway_music'

# try to focus existing window if it exists
focus_window_title "${TITLE}" && exit

# launch music server and app otherwise
if ! systemctl --user is-active mopidy.service; then
  systemctl --user start mopidy.service
fi

swaymsg -t command \
  exec "termite \
          --title \"${TITLE}\" \
          --exec ncmpcpp \
          --geometry 1200x800"

# focus the window (not automatic if different workspace)
# need to wait a bit for the window to be registered
sleep 0.1
focus_window_title "${TITLE}"
