#! /usr/bin/env zsh

echo -n "${PATH}" \
  | xargs --delimiter=: -I{} \
    -- find -L {} \
       -maxdepth 1 -mindepth 1 \
       -type f -executable \
       -printf '%P\n' \
       2> /dev/null \
  | sort -u \
  | fzf --reverse \
  | xargs -I{} \
    -- swaymsg -t command exec {}
