#! /usr/bin/env zsh

TITLE="$1"
ENV_NAME="$2"

ENV_PATH="${XDG_CONFIG_HOME:-$HOME/.config}/tmux/env/${ENV_NAME}"

SESSION=$(
  print -l -- all "${ENV_PATH}"/*.sh(:t:r) \
  | fzf --reverse \
        --no-multi \
        --margin 1,2,0,2 \
        --prompt 'open session ' \
        --color info:8 \
)

[[ -n "${SESSION}" ]] || exit

[[ "${SESSION}" == 'all' ]] && SESSION=

app_tmux_env "${TITLE}" "${ENV_NAME}" "${SESSION}"
