#! /usr/bin/env zsh

ENV_PATH="${XDG_DATA_HOME:-$HOME/.local/share}/tmux/env/projects"

PROJECT=$(
  print -l -- "${ENV_PATH}"/*.sh(:t:r) \
  | fzf --reverse \
        --no-multi \
        --margin 1,2,0,2 \
        --prompt 'open project ' \
        --color info:8 \
)

[[ -n "${PROJECT}" ]] || exit

app_tmux_env projects " Projects environment" "${PROJECT}"
