#! /usr/bin/env zsh

COMMAND="$@"

# try to focus existing window if it exists
FOCUS=$(swaymsg -t command '[title="sway_launcher"]' focus)
[[ ! "${FOCUS}" =~ 'error' ]] && exit

# launch new launcher otherwise
#
# HACK: need to set termite size at start,
# also present in sway rules, to have it respected
# and to have the window centered when floating
swaymsg -t command exec "\
  termite \
    --exec \"${COMMAND}\" \
    --config ${HOME}/.config/termite/config_launcher \
    --title sway_launcher \
    --geometry 700x400 \
"
