#! /usr/bin/env zsh

COMMAND="$1"

# try to focus existing window if it exists
FOCUS=$(swaymsg -t command '[title="menu"]' focus)
[[ ! "${FOCUS}" =~ 'error' ]] && exit

# launch new menu otherwise
swaymsg -t command exec "\
  termite \
    --exec ${COMMAND} \
    --title menu \
    --geometry 500x300 \
"
