#! /usr/bin/env zsh

COMMAND="$1"

# try to focus existing window if it exists
FOCUS=$(swaymsg -t command '[title="sway_menu"]' focus)
[[ ! "${FOCUS}" =~ 'error' ]] && exit

# launch new menu otherwise
swaymsg -t command exec "\
  termite \
    --exec ${COMMAND} \
    --config ${HOME}/.config/termite/config_menu \
    --title sway_menu \
    --geometry 700x400 \
"
