#! /usr/bin/env zsh

TITLE="$1"
TMP_TEXT_FILE="$2"

swaymsg -t command exec "\
  termite \
    --exec 'sh -c \"display_notification \\\"${TITLE}\\\" ${TMP_TEXT_FILE}\"' \
    --config ${HOME}/.config/termite/config_notification \
    --title sway_notification \
    --geometry 500X300 \
  && rm \"${TMP_TEXT_FILE}\"\
"
