#! /usr/bin/env zsh

TITLE="$1"
TMP_TEXT_FILE="$2"

EXTRA_COMMAND="$3"

# do nothing if the "Do not disturb" mode is on
# or if the lockscreen is on
# HACK: there is a bug that floating windows are visible atop the lockscreen
#       so we prevent the display in that case
if pgrep swaylock &> /dev/null \
     || [[ -f "${XDG_DATA_HOME:-$HOME/.local/share}/sway/do_not_disturb" ]]; then
  rm "${TMP_TEXT_FILE}"
  exit
fi

# HACK: need to set termite size at start,
# also present in sway rules, to have it respected
FULL_COMMAND="\
  termite \
    --exec 'sh -c \"display_notification \\\"${TITLE}\\\" ${TMP_TEXT_FILE}\"' \
    --config ${HOME}/.config/termite/config_notification \
    --title sway_notification \
    --geometry 500X300 \
  && rm \"${TMP_TEXT_FILE}\"\
"

if [[ -n "${EXTRA_COMMAND}" ]]; then
  FULL_COMMAND+="&& ${EXTRA_COMMAND}"
fi

swaymsg -t command exec "${FULL_COMMAND}"
