#!/usr/bin/env zsh

TMP_RESULT_FILE=$(mktemp)

cat << EOF > "${TMP_RESULT_FILE}"
                                 ███████▀▀▔▔▔▔▔▀▀▀▀▀▀███████
- exercise your eyes             ███▛▘                 ▀████
                                 ██▘           ▂▄▄▅▄▁    ▜██
- stretch your legs              █▌   ▁▁▄▃▃▂▃▆▇█████▋     ▜█
                                 █▏  ▗███████████████▏     █
- fix your posture               █▙  ▝███████████████▙    ▐█
                                 ███▖ █▛▃▃▔▀▀█▛▘▔ ▝▆██▎▁▃▀██
- relax and focus your mind      ███▎▁▟█▅▅▅▇████▇▇▇███▙▄▀███
                                 ███▅▛▀█████████▋▜██████████
                                 █████▎████▆▆▃▃▅█▆█████▋████
                                 ██████████▀▔ ▔  ▜██████████
$(tput sitm)         Calm your tits          ███████▀███▅▆▇▇▆▆████▛▀████
$(tput sitm)               and               ███▀▔▔▔  ▜▜█▙▄▄▄███▛▀▀▌
$(tput sitm)           Do it live!           ▀▔        ▜▅▀▀▛▀▀▀▘▄▇█▌
EOF

notification 'Take a break' "${TMP_RESULT_FILE}"
