all: remind-configs

remind-configs:
	setup/setup-config remind/reminders         $(HOME)/.reminders
	setup/setup-config remind/general.rem       $(CONFIG_DIR)/remind/general.rem
	setup/setup-config remind/notifications.rem $(CONFIG_DIR)/remind/notifications.rem
