qutebrowser:
	@echo -n "… setup qutebrowser"

    # create necessary directories
	@mkdir -p "$(CONFIG_DIR)/qutebrowser"

    # copy config files
	@cp "qutebrowser/config.py" "$(CONFIG_DIR)/qutebrowser/config.py"

	@echo -e "\r✔ setup qutebrowser"
