vifm:
	@echo -n "… setup vifm"

    # create necessary directories
	@mkdir -p "$(CONFIG_DIR)/vifm"
	@mkdir -p "$(CONFIG_DIR)/vifm/colors"

    # copy config files
	@cp "vifm/vifmrc" "$(CONFIG_DIR)/vifm/vifmrc"
	@cp "vifm/solarized-dark.vifm" "$(CONFIG_DIR)/vifm/colors/solarized-dark.vifm"

	@echo -e "\r✔ setup vifm"
