#!/bin/sh

init_variables() {
  COMMAND=${0##*/}

  LOCAL_BROWSER_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/qutebrowser"
  LOCAL_BOOKS_DIR="${XDG_BOOKS_DIR:-$HOME/Books}"
  LOCAL_CONTACTS_DIR="${XDG_CONTACTS_DIR:-$HOME/Contacts}"
  LOCAL_NOTES_DIR="${XDG_NOTES_DIR:-$HOME/Notes}"
  LOCAL_TIME_TRACKER_LOGS_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/time-tracker/logs"
  LOCAL_VIDEOS_DIR="${XDG_VIDEOS_DIR:-$HOME/Videos}"

  HDD1_UUID='e89b95fd-8520-43c1-bebf-610c92176955'
  HDD2_UUID='204b2ecc-e3c3-497c-aa4a-c0421a2ddb4f'

  SERVER_HOST='chestnut'
  SERVER_BASE_DIR="backup/$( uname -n )"

  SERVER_BOOKMARKS_DIR="${SERVER_BASE_DIR}/bookmarks"
  SERVER_NOTES_DIR="${SERVER_BASE_DIR}/notes"
  SERVER_TIME_TRACKER_LOGS_DIR="${SERVER_BASE_DIR}/time_tracker_logs"
  SERVER_PACKAGES_DIR="/usr/local/www/pkgs"
  SERVER_REPOSITORIES_DIR="repos"

  SOURCE='laptop'
  TARGET='hdd1'
  ITEM=
}

init_hdd_variables() {
  HDD_BACKUP_DIR="${HDD_BASE_DIR}/Backup"

  HDD_BOOKMARKS_DIR="${HDD_BASE_DIR}/Bookmarks"
  HDD_BOOKS_DIR="${HDD_BASE_DIR}/Books"
  HDD_CONTACTS_DIR="${HDD_BASE_DIR}/Contacts"
  HDD_NOTES_DIR="${HDD_BASE_DIR}/Notes"
  HDD_VIDEOS_DIR="${HDD_BASE_DIR}/Videos"
  HDD_PACKAGES_DIR="${HDD_BASE_DIR}/Packages"
  HDD_REPOSITORIES_DIR="${HDD_BASE_DIR}/Repositories"
}

parse_command_line() {
  while getopts s:t: OPT; do
    case "${OPT}" in
      s) SOURCE="${OPTARG}" ;;
      t) TARGET="${OPTARG}" ;;
      ?) exit_error ;;
    esac
  done

  shift $(( OPTIND - 1 ))

  ITEM="$1"
}

validate_command_line() {
  if [ "${SOURCE}" != 'laptop' ] \
     && [ "${SOURCE}" != 'server' ]; then
    exit_error "Invalid source '${SOURCE}'"
  fi

  if [ "${TARGET}" != 'hdd1' ] \
     && [ "${TARGET}" != 'hdd2' ] \
     && [ "${TARGET}" != 'server' ]; then
    exit_error "Invalid target '${TARGET}'"
  fi

  if [ -z "${ITEM}" ]; then
    exit_error 'missing item'
  fi

  if [ "${ITEM}" != 'bookmarks' ] \
     && [ "${ITEM}" != 'books' ] \
     && [ "${ITEM}" != 'contacts' ] \
     && [ "${ITEM}" != 'notes' ] \
     && [ "${ITEM}" != 'packages' ] \
     && [ "${ITEM}" != 'repositories' ] \
     && [ "${ITEM}" != 'time_tracker_logs' ] \
     && [ "${ITEM}" != 'videos' ]; then
    exit_error "Invalid item '${ITEM}'"
  fi

  if [ "${SOURCE}" = 'laptop' ]; then
    if [ "${TARGET}" = 'hdd1' ] || [ "${TARGET}" = 'hdd2' ]; then
      if [ "${ITEM}" != 'bookmarks' ] \
         && [ "${ITEM}" != 'books' ] \
         && [ "${ITEM}" != 'contacts' ] \
         && [ "${ITEM}" != 'notes' ] \
         && [ "${ITEM}" != 'videos' ]; then
        exit_error "Cannot backup ${ITEM} from ${SOURCE} to ${TARGET}"
      fi
    fi

    if [ "${TARGET}" = 'server' ]; then
      if [ "${ITEM}" != 'bookmarks' ] \
         && [ "${ITEM}" != 'notes' ] \
         && [ "${ITEM}" != 'time_tracker_logs' ]; then
        exit_error "Cannot backup ${ITEM} from ${SOURCE} to ${TARGET}"
      fi
    fi
  elif [ "${SOURCE}" = 'server' ]; then
    if [ "${TARGET}" = 'hdd1' ] || [ "${TARGET}" = 'hdd2' ]; then
      if [ "${ITEM}" != 'packages' ] \
         && [ "${ITEM}" != 'repositories' ]; then
        exit_error "Cannot backup ${ITEM} from ${SOURCE} to ${TARGET}"
      fi
    fi
    if [ "${TARGET}" = 'server' ]; then
        exit_error "Cannot backup to itself"
    fi
  fi
}

exit_error() {
  [ -z "$1" ] || echo "${COMMAND}: $1"
  exit 1
} >&2

backup_laptop_hdd_bookmarks() {
  rsync -az \
    --backup-dir="${HDD_BACKUP_DIR}/Bookmarks" \
    "${LOCAL_BROWSER_DIR}/bookmarks/urls" \
    "${HDD_BOOKMARKS_DIR}/urls"

  rsync -az \
    --backup-dir="${HDD_BACKUP_DIR}/Bookmarks" \
    "${LOCAL_BROWSER_DIR}/quickmarks" \
    "${HDD_BOOKMARKS_DIR}/quickmarks"
}

backup_laptop_hdd_books() {
  rsync -az --delete \
    --backup-dir="${HDD_BACKUP_DIR}/Books" \
    "${LOCAL_BOOKS_DIR}/" \
    "${HDD_BOOKS_DIR}"
}

backup_laptop_hdd_contacts() {
  rsync -az --delete --exclude=".*" \
    --backup-dir="${HDD_BACKUP_DIR}/Contacts" \
    "${LOCAL_CONTACTS_DIR}/" \
    "${HDD_CONTACTS_DIR}"
}

backup_laptop_hdd_notes() {
  rsync -az --delete --exclude=".*" \
    --backup-dir="${HDD_BACKUP_DIR}/Notes" \
    "${LOCAL_NOTES_DIR}/" \
    "${HDD_NOTES_DIR}"
}

backup_laptop_hdd_videos() {
  rsync -az \
    "${LOCAL_VIDEOS_DIR}/" \
    "${HDD_VIDEOS_DIR}"
}

backup_laptop_server_bookmarks() {
  rsync -azb \
    "${LOCAL_BROWSER_DIR}/bookmarks/urls" \
    "${SERVER_HOST}:${SERVER_BOOKMARKS_DIR}/urls"

  rsync -azb \
    "${LOCAL_BROWSER_DIR}/quickmarks" \
    "${SERVER_HOST}:${SERVER_BOOKMARKS_DIR}/quickmarks"
}

backup_laptop_server_notes() {
  rsync -azb --delete --exclude=".*" \
    "${LOCAL_NOTES_DIR}/" \
    "${SERVER_HOST}:${SERVER_NOTES_DIR}"
}

backup_laptop_server_time_tracker_logs() {
  rsync -azb --delete --exclude=".*" \
    "${LOCAL_TIME_TRACKER_LOGS_DIR}/" \
    "${SERVER_HOST}:${SERVER_TIME_TRACKER_LOGS_DIR}"
}

backup_server_hdd_packages() {
  rsync -az --delete \
    "${SERVER_HOST}:${SERVER_PACKAGES_DIR}/" \
    "${HDD_PACKAGES_DIR}"
}

backup_server_hdd_repositories() {
  rsync -az --delete \
    "${SERVER_HOST}:${SERVER_REPOSITORIES_DIR}/" \
    "${HDD_REPOSITORIES_DIR}"
}

init_hdd() {
  HDD_BASE_DIR="$(
    lsblk -n -o UUID,MOUNTPOINT \
      | grep "^$1 " \
      | awk '{ print $2 }'
  )"

  if [ -z "${HDD_BASE_DIR}" ]; then
    exit_error "HDD is not connected"
  fi

  init_hdd_variables
  TARGET='hdd'
}

init_variables
parse_command_line "$@"
validate_command_line

if [ "${TARGET}" = 'hdd1' ]; then
  init_hdd "${HDD1_UUID}"
elif [ "${TARGET}" = 'hdd2' ]; then
  init_hdd "${HDD2_UUID}"
fi

"backup_${SOURCE}_${TARGET}_${ITEM}"
