#!/bin/sh

LOCAL_BROWSER_FOLDER="${XDG_CONFIG_HOME:-$HOME/.config}/qutebrowser"
REMOTE_BOOKMARKS_FOLDER="backup/$( uname -n )/bookmarks"

rsync -azb \
  "${LOCAL_BROWSER_FOLDER}/bookmarks/urls" \
  surg:"${REMOTE_BOOKMARKS_FOLDER}/urls"

rsync -azb \
  "${LOCAL_BROWSER_FOLDER}/quickmarks" \
  surg:"${REMOTE_BOOKMARKS_FOLDER}/quickmarks"
