#!/bin/sh

ADAPTER_STATUS=$(
  [ "$( cat /sys/class/power_supply/AC/online )" -eq 1 ] \
    && echo 'on' \
    || echo 'off'
)

IS_ANY_BATTERY_CHARGING='no'
TOTAL_CAPACITY_NOW=0
TOTAL_CAPACITY_FULL=0

for bat in /sys/class/power_supply/BAT*; do
  if [ -f "${bat}/energy_now" ]; then
    TOTAL_CAPACITY_NOW=$(( TOTAL_CAPACITY_NOW + $( cat "${bat}/energy_now" ) ))
    TOTAL_CAPACITY_FULL=$(( TOTAL_CAPACITY_FULL + $( cat "${bat}/energy_full" ) ))
  else
    TOTAL_CAPACITY_NOW=$(( TOTAL_CAPACITY_NOW + $( cat "${bat}/charge_now" ) ))
    TOTAL_CAPACITY_FULL=$(( TOTAL_CAPACITY_FULL + $( cat "${bat}/charge_full" ) ))
  fi

  if [ "$( cat "${bat}/status" )" = 'Charging' ]; then
    IS_ANY_BATTERY_CHARGING='yes'
  fi
done

TOTAL_CAPACITY_PERCENT=$(
  printf %.0f "$(
    echo "( ${TOTAL_CAPACITY_NOW} / ${TOTAL_CAPACITY_FULL} ) * 100" \
      | bc -l
  )"
)

printf 'Adapter: %s\n' "${ADAPTER_STATUS}"
printf 'Charging: %s\n' "${IS_ANY_BATTERY_CHARGING}"
printf 'Charge: %s%%\n' "${TOTAL_CAPACITY_PERCENT}"
