#!/bin/sh

exec /usr/bin/bemenu-run \
  -i -l 10 \
  --fn 'Source Sans Pro 14' \
  --tb '#{color/base09/hex}' \
  --tf '#{color/base00/hex}' \
  --fb '#{color/base09/hex}' \
  --ff '#{color/base00/hex}' \
  --nb '#{color/popup_background/hex}' \
  --nf '#{color/popup_foreground/hex}' \
  --hb '#{color/current_item/hex}' \
  --hf '#{color/base00/hex}' \
  --sb '#{color/selected_item/hex}' \
  --sf '#{color/base00/hex}' \
  --ab '#{color/popup_background/hex}' \
  --af '#{color/popup_foreground/hex}' \
  "$@"
