#!/bin/sh

MESSAGE=

PACMAN_UPDATES_COUNT=$(
  packages-updates list \
    | wc -l
)
if [ "${PACMAN_UPDATES_COUNT}" -gt 0 ]; then
  MESSAGE="${MESSAGE}pacman: ${PACMAN_UPDATES_COUNT}\n"
fi

AUR_UPDATES_COUNT=$(
  aur repo -d aur -S -u \
    | wc -l
)
if [ "${AUR_UPDATES_COUNT}" -gt 0 ]; then
  MESSAGE="${MESSAGE}aur: ${AUR_UPDATES_COUNT}\n"
fi

TARDYPAD_UPDATES_COUNT=$(
  aur repo -d tardypad -S -u \
    | wc -l
)
if [ "${TARDYPAD_UPDATES_COUNT}" -gt 0 ]; then
  MESSAGE="${MESSAGE}tardypad: ${TARDYPAD_UPDATES_COUNT}\n"
fi

[ -n "${MESSAGE}" ] || exit

notify \
  -c 'info' \
  'Packages updates available' \
  "${MESSAGE}"
