#!/bin/sh

ALERT_THRESHOLD_PERCENT=10

BATTERY_STATUS=$( battery-status )

ADAPTER_STATUS=$(
  echo "${BATTERY_STATUS}" \
    | sed -n 's/^Adapter: \(.*\)$/\1/p'
)

[ "${ADAPTER_STATUS}" = 'on' ] && exit

TOTAL_ENERGY_PERCENT=$(
  echo "${BATTERY_STATUS}" \
    | sed -n 's/^Charge: \(.*\)%$/\1/p'
)

[ "${TOTAL_ENERGY_PERCENT}" -gt "${ALERT_THRESHOLD_PERCENT}" ] && exit

notify \
  -c 'alert' \
  -i 'low_battery' \
  -s "${XDG_DATA_HOME:-$HOME/.local/share}/sounds/low_battery.ogg" \
  'Low battery' \
  'Battery level is getting low'
