#!/bin/sh

NAME=$(
  ykman oath accounts list 2> /dev/null \
    | sort \
    | wmenu -p 'Copy OTP'
)

[ -n "${NAME}" ] || exit

ykman oath accounts code -s "${NAME}" \
  | wl-copy -n \
      > /dev/null 2>&1
