#!/bin/sh

PASSWORD_STORE_DIR="${PASSWORD_STORE_DIR:-$HOME/.password-store}"

NAME=$(
  find -L "${PASSWORD_STORE_DIR}" \
    -type f -name '*.gpg' \
    | sed -e "s#${PASSWORD_STORE_DIR}/##" \
          -e 's/\.gpg//' \
    | sort \
    | fzf --reverse \
          --no-multi \
          --info hidden \
          --header "$( printf '\n' )" \
          "$@"
)

[ -n "${NAME}" ] || exit

nohup \
  pass show --clip "${NAME}" \
  > /dev/null 2>&1
