#!/bin/sh

PASSWORD_STORE_DIR="${PASSWORD_STORE_DIR:-$HOME/.password-store}"

NAME=$(
  find -L "${PASSWORD_STORE_DIR}" \
    -type f -name '*.gpg' \
    | sed -e "s#${PASSWORD_STORE_DIR}/##" \
          -e 's/\.gpg//' \
    | sort \
    | wmenu -p 'Copy password'
)

[ -n "${NAME}" ] || exit

pass show -c "${NAME}" \
  > /dev/null 2>&1
