#!/bin/sh

init_variables() {
  COMMAND=${0##*/}

  FILE_PATH="${XDG_RUNTIME_DIR:-/tmp}/do_not_disturb"

  ACTION='status'
  DURATION_MIN=
  WORK=
}

parse_command_line() {
  while getopts d:u:U:w: OPT; do
    case "${OPT}" in
      d) DURATION_MIN="${OPTARG}" ;;
      w) WORK="${OPTARG}" ;;
      ?) exit_error ;;
    esac
  done

  shift $(( OPTIND - 1 ))

  [ -z "$1" ] || ACTION="$1"
}

validate_command_line() {
  if [ "${ACTION}" != 'enable' ] \
     && [ "${ACTION}" != 'disable' ] \
     && [ "${ACTION}" != 'toggle' ] \
     && [ "${ACTION}" != 'remote-status' ] \
     && [ "${ACTION}" != 'status' ]; then
    exit_error "Invalid action '${ACTION}'"
  fi

  case "${DURATION_MIN}" in
    *[!0-9]*) exit_error 'duration must be an integer' ;;
  esac
}

exit_error() {
  [ -z "$1" ] || echo "${COMMAND}: $1"
  exit 1
} >&2

end_time() {
  CUR_HOURS=$( date +%H )
  CUR_MINUTES=$( date +%M )
  # values with leading 0 are interpreted as octals
  # which leads to issue with "08" and "09"
  # so we need to remove them
  TIME_MIN=$((
    ${CUR_HOURS#0} * 60 + ${CUR_MINUTES#0} + ${DURATION_MIN}
  ))

  TIME_H=$(( TIME_MIN / 60 ))
  TIME_M=$(( TIME_MIN % 60 ))
  printf '%02dH%02d' "${TIME_H}" "${TIME_M}"
}

dnd_enable() {
  echo '/slack away' | weechat-fifo 2> /dev/null &

  STATUS_TEXT=

  if [ -n "${DURATION_MIN}" ]; then
    STATUS_TEXT="until $( end_time )"
    ( sleep $(( DURATION_MIN * 60 )) && dnd_disable )&
  fi

  if [ -n "${WORK}" ]; then
    STATUS_TEXT="${STATUS_TEXT} working on ${WORK}"
  fi

  ssh surg bin/set-status busy "${STATUS_TEXT}" 2> /dev/null &

  # function return value from file creation
  touch "${FILE_PATH}"
}

dnd_disable() {
  echo '/slack back' | weechat-fifo 2> /dev/null &

  ssh surg bin/set-status available 2> /dev/null &

  # function return value from file deletion
  rm -f "${FILE_PATH}"
}

dnd_status() {
  if is_dnd_enabled; then
    echo 'enabled'
  else
    echo 'disabled'
  fi
}

dnd_toggle() {
  if is_dnd_enabled; then
    dnd_disable
  else
    dnd_enable
  fi
}

is_dnd_enabled() {
  [ -f "${FILE_PATH}" ]
}

dnd_remote_status() {
  curl -s -H 'Accept: text/plain' https://status.tardypad.me \
    | grep -v '^$'
}

init_variables
parse_command_line "$@"
validate_command_line

"dnd_$( echo "${ACTION}" | tr '-' '_' )"

pkill -x -RTMIN+3 i3blocks
