#!/bin/sh

DESKTOP_FILE="$1"

if [ -z "${DESKTOP_FILE}" ]; then
  echo 'Missing desktop entry file' >&2
  exit 1
fi

if [ ! -f "${DESKTOP_FILE}" ]; then
  echo "'${DESKTOP_FILE}' is not a file" >&2
  exit 1
fi

# extract exec command and remove field codes
COMMAND=$(
  sed -n '/^Exec=/ {
    s/^Exec=\(.*\)/\1/
    s/%[a-zA-Z]//
    p
  }' "${DESKTOP_FILE}" \
)

if [ -z "${COMMAND}" ]; then
  echo 'No Exec command' >&2
  exit 1
fi

eval "${COMMAND}"&
