#!/bin/sh

init_variables() {
  COMMAND=${0##*/}

  TOKEN_TYPE=
}

parse_command_line() {
  TOKEN_TYPE="$1"
}

validate_command_line() {
  if [ -z "${TOKEN_TYPE}" ]; then
    exit_error 'missing token type'
  fi

  if [ "${TOKEN_TYPE}" != 'hash' ] \
     && [ "${TOKEN_TYPE}" != 'line' ] \
     && [ "${TOKEN_TYPE}" != 'path' ] \
     && [ "${TOKEN_TYPE}" != 'url' ] \
     && [ "${TOKEN_TYPE}" != 'word' ] \
     && [ "${TOKEN_TYPE}" != 'WORD' ]; then
    exit_error "Invalid action '${TOKEN_TYPE}'"
  fi
}

exit_error() {
  [ -z "$1" ] || echo "${COMMAND}: $1"
  exit 1
} >&2

grep_hash() {
  grep -E -o '[[:digit:]a-fA-F][-[:digit:]a-fA-F]{5,}'
}

grep_line() {
  grep '.' | sed -e 's/^[ \t]*//' -e 's/[ \t]*$//'
}

grep_path() {
  grep -E -o '[-_.~[:alnum:]]*/[-_.%~/[:alnum:]]+'
}

grep_url() {
  grep -E -o 'https?://[[:alnum:]?=%/_.:,;~@!#$&*+-]*'
}

grep_word() {
  grep -E -o '[-_.[:alnum:]]+'
}

grep_WORD() {
  grep -E -o '[^ ]+'
}

init_variables
parse_command_line "$@"
validate_command_line

"grep_${TOKEN_TYPE}"
