#!/bin/sh
# commands used:
# - http

init_variables() {
  COMMAND=${0##*/}

  ENV_DIR_PATH="${XDG_DATA_HOME:-$HOME/.local/share}/env/http"

  HTTP_OPTIONS=
  PROJECT=
  ENVIRONMENT=
  REQUEST_METHOD=
  REQUEST_PATH=
  REQUEST_ITEMS=

  ENV_PATH=
}

parse_command_line() {
  PROJECT="$1"
  ENVIRONMENT="$2"
  REQUEST_METHOD="$3"
  REQUEST_PATH="$4"
  shift 4 2> /dev/null

  while [ "$#" -gt 0 ] && [ "$1" != '--' ]; do
    REQUEST_ITEMS="${REQUEST_ITEMS} $1"
    shift
  done

  shift 2> /dev/null
  HTTP_OPTIONS="$*"
}

validate_command_line() {
  if [ -z "${PROJECT}" ]; then
    exit_error 'missing project'
  fi

  if [ -z "${ENVIRONMENT}" ]; then
    exit_error 'missing environment'
  fi

  if [ -z "${REQUEST_METHOD}" ]; then
    exit_error 'missing request method'
  fi

  if [ -z "${REQUEST_PATH}" ]; then
    exit_error 'missing request path'
  fi

  ENV_PATH="${ENV_DIR_PATH}/${PROJECT}/${ENVIRONMENT}"

  if [ ! -f "${ENV_PATH}" ]; then
    exit_error 'invalid project/environment'
  fi
}

exit_error() {
  [ -z "$1" ] || echo "${COMMAND}: $1"
  exit 1
} >&2

run_http() {
  URL="$( head -n 1 "${ENV_PATH}" )/${REQUEST_PATH}"

  OPTIONS=$( grep '^-' "${ENV_PATH}" | tr '\n' ' ' )
  OPTIONS="${OPTIONS} ${HTTP_OPTIONS}"

  ITEMS=$( tail -n +2 "${ENV_PATH}" | grep -v '^-' | tr '\n' ' ' )
  ITEMS="${ITEMS} ${REQUEST_ITEMS}"

  http ${OPTIONS} "${REQUEST_METHOD}" "${URL}" ${ITEMS}
}

init_variables
parse_command_line "$@"
validate_command_line

run_http
