#!/bin/sh

USE_NEW=false

while getopts n OPT; do
  case "${OPT}" in
    n) USE_NEW=true ;;
    ?) exit 1 ;;
  esac
done

shift $(( OPTIND - 1 ))

ENV="$1"

SESSION=$(
  {
    [ "${USE_NEW}" = 'true' ] && echo New;
    find "${XDG_DATA_HOME:-$HOME/.local/share}/env/tmux/${ENV}" \
      -type f -name '*.sh' -exec basename {} .sh \; \
      | sort
  } \
  | tofi --prompt-text="Open ${ENV}"
)

[ -n "${SESSION}" ] || exit

[ "${SESSION}" = 'New' ] && SESSION=

TITLE="${ENV} environment"

# create env in background
# will do nothing if already exists
tmux-env -b "${ENV}" "${SESSION}"

swaymsg -q "[title=\"${TITLE}\"]" focus && exit

sway-create-workspace "${ENV}"

swaymsg -q exec \
  "foot \
   -T \"${TITLE}\" -o locked-title=yes \
   tmux-env ${ENV} ${SESSION}"
