#!/bin/sh

init_variables() {
  COMMAND=${0##*/}

  ONLY_ONE=false
}

parse_command_line() {
  while getopts o OPT; do
    case "${OPT}" in
      o) ONLY_ONE=true ;;
      ?) exit_error ;;
    esac
  done

  shift $(( OPTIND - 1 ))
}

# shellcheck disable=SC2120
exit_error() {
  [ -z "$1" ] || echo "${COMMAND}: $1"
  exit 1
} >&2

print_text_center() {
  TEXT_WIDTH="$( echo "${TEXT}" | awk 'length > maxl { maxl = length } END { print maxl }' )"
  TEXT_HEIGHT="$( echo "${TEXT}" | awk 'END { print NR }' )"

  COL=$(( ( $( tput cols ) - TEXT_WIDTH ) / 2 ))
  ROW=$(( ( $( tput lines ) - TEXT_HEIGHT ) / 2 ))

  tput cup 0 0
  tput ed
  tput cup "${ROW}" 0

  SPACER="$( printf "%${COL}s" ' ' )"

  printf '%s' "$TEXT" | sed "s/^/${SPACER}/"
}

print_line_by_line() {
  while read -r LINE; do
    TEXT="$( printf '%s' "${LINE}" | sed 's/\t/\n/g' )"

    if [ "${ONLY_ONE}" = 'true' ]; then
      print_text_center
    else
      printf '%s' "${TEXT}"
    fi

    read -r < /dev/tty
  done
}

init_variables
parse_command_line "$@"

print_line_by_line
