#!/bin/sh

init_variables() {
  COMMAND=${0##*/}

  ENV_DIR_PATH="${XDG_DATA_HOME:-$HOME/.local/share}/env/mysql"

  ENV_ID=
  QUERY=

  if [ -t 1 ]; then
    MYSQL_OPTIONS='--raw --table --column-names'
  else
    MYSQL_OPTIONS='--raw --batch --skip-column-names'
  fi

  ENV_PATH=
}

parse_command_line() {
  ENV_ID="$1"

  [ $# -eq 0 ] && return
  shift

  while [ "$#" -gt 0 ] && [ "$1" != '--' ]; do
    QUERY="${QUERY} $1"
    shift
  done

  if [ "$1" = '--' ]; then
    shift
    MYSQL_OPTIONS="${MYSQL_OPTIONS} $*"
  fi
}

validate_command_line() {
  if [ -z "${ENV_ID}" ]; then
    exit_error 'missing environment identifier'
  fi

  ENV_PATH="${ENV_DIR_PATH}/${ENV_ID}"

  if [ ! -f "${ENV_PATH}" ]; then
    exit_error 'invalid environment'
  fi
}

exit_error() {
  [ -z "$1" ] || echo "${COMMAND}: $1"
  exit 1
} >&2

run_mysql() {
  # shellcheck disable=SC2046 disable=SC2086
  if [ -z "${QUERY}" ]; then
    mysql $( cat "${ENV_PATH}" ) ${MYSQL_OPTIONS}
  else
    mysql $( cat "${ENV_PATH}" ) ${MYSQL_OPTIONS} -e "${QUERY}"
  fi
}

init_variables
parse_command_line "$@"
validate_command_line

run_mysql
