#!/bin/sh

init_variables() {
  COMMAND=${0##*/}

  ENV_DIR_PATH="${XDG_DATA_HOME:-$HOME/.local/share}/env/mysql"

  PROJECT=
  QUERY=

  if [ -t 1 ]; then
    MYSQL_OPTIONS='--raw --column-names'
  else
    MYSQL_OPTIONS='--raw --batch --skip-column-names'
  fi

  ENV_PATH=
}

parse_command_line() {
  PROJECT="$1"
  shift 2> /dev/null

  while [ "$#" -gt 0 ] && [ "$1" != '--' ]; do
    QUERY="${QUERY} $1"
    shift
  done

  shift 2> /dev/null
  MYSQL_OPTIONS="${MYSQL_OPTIONS} $*"
}

validate_command_line() {
  if [ -z "${PROJECT}" ]; then
    exit_error 'missing project'
  fi

  ENV_PATH="${ENV_DIR_PATH}/${PROJECT}"

  if [ ! -f "${ENV_PATH}" ]; then
    exit_error 'invalid project'
  fi
}

exit_error() {
  [ -z "$1" ] || echo "${COMMAND}: $1"
  exit 1
} >&2

run_mysql() {
  if [ -z "${QUERY}" ]; then
    mysql $( cat "${ENV_PATH}" ) ${MYSQL_OPTIONS}
  else
    mysql $( cat "${ENV_PATH}" ) ${MYSQL_OPTIONS} -e "${QUERY}"
  fi
}

init_variables
parse_command_line "$@"
validate_command_line

run_mysql
