#!/bin/sh

MESSAGE="Straighten your back"
MESSAGE="${MESSAGE}\nLook far away"
MESSAGE="${MESSAGE}\nBlink and roll your eyes"

notify \
  -c 'warning' \
  -i 'break' \
  'Take a break' \
  "${MESSAGE}"
