#!/bin/sh
# commands used:
# - pacman
# - tar

init_variables() {
  COMMAND=${0##*/}

  PACKAGE_NAME=
}

parse_command_line() {
  PACKAGE_NAME="$1"
}

validate_command_line() {
  if [ -z "${PACKAGE_NAME}" ]; then
    exit_error 'missing package name'
  fi

  if ! pacman -Q "${PACKAGE_NAME}" > /dev/null 2>&1; then
    exit_error "invalid package name ${PACKAGE_NAME}"
  fi
}

exit_error() {
  [ -z "$1" ] || echo "${COMMAND}: $1"
  exit 1
} >&2

diff_package() {
  PACKAGE_VERSION=$(
    pacman -Q "${PACKAGE_NAME}" 2> /dev/null \
      | cut -f 2 -d ' '
  )

  # need double -k argument to show modified files
  pacman -Qkk "${PACKAGE_NAME}" \
   | grep '^backup file:' \
   | cut -f 4 -d ' ' \
   | uniq \
   | while read -r PACKAGE_MODIFIED_FILE; do
       echo "${PACKAGE_MODIFIED_FILE}"
       tar -xO \
         -f "/var/cache/pacman/pkg/${PACKAGE_NAME}-${PACKAGE_VERSION}"-*.pkg.tar.xz \
         "$( echo "${PACKAGE_MODIFIED_FILE}" | sed 's|/||' )" \
         2> /dev/null \
       | diff - "${PACKAGE_MODIFIED_FILE}"
       echo
     done
}

init_variables
parse_command_line "$@"
validate_command_line

diff_package
