#!/bin/sh

CHANNELS=$( somafm channels )

CHANNEL_NAME=$(
  echo "${CHANNELS}" \
    | cut -f2 \
    | bemenu -p 'Play SomaFM channel'
)

[ -n "${CHANNEL_NAME}" ] || exit

CHANNEL_ID=$(
  echo "${CHANNELS}" \
    | cut -f1,2 \
    | grep "${CHANNEL_NAME}" \
    | cut -f1
)

CHANNEL_URL=$( somafm direct_url "${CHANNEL_ID}" )

mpc -q clear
mpc -q add "${CHANNEL_URL}"
mpc -q play
