#!/bin/sh

init_variables() {
  COMMAND=${0##*/}

  DEFAULT_TYPE=line
  DEFAULT_WIDTH=80
  DEFAULT_HEIGHT=25

  JP_OPTIONS=
}

parse_command_line() {
  shift 2> /dev/null
  JP_OPTIONS="$*"
}

exit_error() {
  [ -z "$1" ] || echo "${COMMAND}: $1"
  exit 1
} >&2

plot_data() {
  awk '
    BEGIN { OFS="," }
    /^[0-9.]+$/ { print NR,$1; next; }
    { print $1,$2; }
  ' \
    | jp \
      -input csv \
      -type "${DEFAULT_TYPE}" \
      -width "${DEFAULT_WIDTH}" \
      -height "${DEFAULT_HEIGHT}" \
      ${JP_OPTIONS}
}

init_variables
parse_command_line "$@"

plot_data
