#!/bin/sh

init_variables() {
  COMMAND=${0##*/}

  FILE_PATH="${XDG_RUNTIME_DIR:-/tmp}/pomodoro"
  DURATION_MIN=25

  ACTION='status'
}

parse_command_line() {
  [ -z "$1" ] || ACTION="$1"
  [ -z "$2" ] || DURATION_MIN="$2"
}

validate_command_line() {
  if [ "${ACTION}" != 'start' ] \
     && [ "${ACTION}" != 'cancel' ] \
     && [ "${ACTION}" != 'toggle' ] \
     && [ "${ACTION}" != 'status' ]; then
    exit_error "Invalid action '${ACTION}'"
  fi

  case "${DURATION_MIN}" in
    *[!0-9]*) exit_error 'duration must be an integer' ;;
  esac
}

exit_error() {
  [ -z "$1" ] || echo "${COMMAND}: $1"
  exit 1
} >&2

current_time_sec() {
  CUR_HOURS=$( date +%H )
  CUR_MINUTES=$( date +%M )
  CUR_SECONDS=$( date +%S )
  # values with leading 0 are interpreted as octals
  # which leads to issue with "08" and "09"
  # so we need to remove them
  echo $((
    ${CUR_HOURS#0} * 3600 + ${CUR_MINUTES#0} * 60 + ${CUR_SECONDS#0}
  ))
}

session_start() {
  CURRENT_TIME=$( current_time_sec )
  {
    echo "${CURRENT_TIME}"
    echo "${DURATION_MIN}"
  } > "${FILE_PATH}" \
    && update_i3blocks

  ( sleep $(( DURATION_MIN * 60 )) && session_end "${CURRENT_TIME}" )&
}

session_status() {
  if ! is_session_started; then
    echo 'No current session' >&2
    return 1
  fi

  CURRENT_TIME=$( current_time_sec )
  START_TIME=$( head -n 1 "${FILE_PATH}" )
  DURATION_MIN=$( tail -n +2 "${FILE_PATH}" )
  MINUTES_LEFT=$((
    DURATION_MIN - ( (CURRENT_TIME - START_TIME) / 60 )
  ))

  echo "${MINUTES_LEFT} min left"
}

session_cancel() {
  if ! is_session_started; then
    echo 'No current session' >&2
    return 1
  fi

  rm -f "${FILE_PATH}" \
    && update_i3blocks
}

session_toggle() {
  if is_session_started; then
    session_cancel
  else
    session_start
  fi
}

session_end() {
  is_session_started || return 1

  SESSION_START_TIME="$1"
  CURRENT_START_TIME=$( head -n 1 "${FILE_PATH}" )

  # only end session if no newer one was created
  if [ "${SESSION_START_TIME}" = "${CURRENT_START_TIME}" ]; then
    rm -rf "${FILE_PATH}"
    notify_end_pomodoro
    update_i3blocks
  fi
}

notify_end_pomodoro() {
  notify \
    -t 5 \
    -c 'notice' \
    'Pomodoro end' \
    'Take a break'

  paplay \
    "${XDG_DATA_HOME:-$HOME/.local/share}/sounds/end_pomodoro.wav" \
    2> /dev/null
}

update_i3blocks() {
  pkill -x -RTMIN+5 i3blocks
}

is_session_started() {
  [ -f "${FILE_PATH}" ]
}

init_variables
parse_command_line "$@"
validate_command_line

"session_${ACTION}"
