#!/bin/sh

init_variables() {
  COMMAND=${0##*/}

  PERIOD='day'
  DATE=
  FINAL_DATE=
}

parse_command_line() {
  while getopts dmw OPT; do
    case "${OPT}" in
      d) PERIOD='day' ;;
      m) PERIOD='month' ;;
      w) PERIOD='week' ;;
      ?) exit_error ;;
    esac
  done

  shift $(( OPTIND - 1 ))

  [ -z "$1" ] || DATE="$1"
}

validate_command_line() {
  # shellcheck disable=SC2221 disable=SC2222
  case "$( echo "${DATE}" | tr '[:upper:]' '[:lower:]' )" in
    [+-][0-9]*)
      FINAL_DATE="$( date '+%Y/%m/%d' -d "${DATE} ${PERIOD}" )"
      ;;
    jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)
      FINAL_DATE="$( date '+%Y/%m/%d' -d "01 ${DATE}" )"
      ;;
    january|february|march|april|may|june|july|august|september|october|november|december)
      FINAL_DATE="$( date '+%Y/%m/%d' -d "01 ${DATE}" )"
      ;;
    *)
      FINAL_DATE="$( date '+%Y/%m/%d' -d "${DATE}" )"
      ;;
  esac 2> /dev/null

  if [ -z "${FINAL_DATE}" ]; then
    exit_error "Invalid date '${DATE}'"
  fi
}

exit_error() {
  [ -z "$1" ] || echo "${COMMAND}: $1"
  exit 1
} >&2

schedule_day() {
  rem -s -b1 "${FINAL_DATE}" \
    | grep "${FINAL_DATE}" \
    | cut -d' ' -f6- \
    | sed -e 's/\(.*\) (.*)$/\1/' \
          -e '/^[0-9]/s/ /\t/' \
          -e '/^[^0-9]/s/^/\t/' \
    | column -t -s '	' \
    | sed 's/^ *//' \
    | awk '!found && /^[^0-9]/ { print ""; found=1 } 1'
}

schedule_week() {
  rem -cu+1 -b1 -m "${FINAL_DATE}"
}

schedule_month() {
  rem -cu1 -b1 -m "${FINAL_DATE}"
}

init_variables
parse_command_line "$@"
validate_command_line

"schedule_${PERIOD}"
