#!/bin/sh

TMP_FILE="$( mktemp )"
trap 'rm -f "${TMP_FILE}"' EXIT

TEXT="$( wl-paste 2> /dev/null )"

[ -z "${TEXT}" ] && exit 1

qrencode -t png -s 10 "${TEXT}" -o "${TMP_FILE}" \
  && imv -W 400 -H 400 "${TMP_FILE}"
