#!/bin/sh

TAGS=$*

IGNORE_TAGS='^ *name '
while [ "$#" -gt 0 ]; do
  IGNORE_TAG=$( echo "$1" | sed 's/\([^=]*\)=.*/\1/' )
  IGNORE_TAGS="${IGNORE_TAGS}|^ *${IGNORE_TAG} "
  shift
done

SELECTED_HOST=$(
  query-hosts-tags hosts "${TAGS}" \
    | fzf \
      --no-multi \
      --exit-0 \
      --select-1 \
      --height=10 \
      --layout=reverse \
      --preview="query-hosts-tags tags {} | grep -vE '${IGNORE_TAGS}'" \
      --preview-window='right:70%:border-left'
)

[ -n "${SELECTED_HOST}" ] || exit

TERM=xterm-256color ssh "${SELECTED_HOST}"
