#!/bin/sh

TAGS=$*

IGNORE_TAGS='^ *name '
while [ "$#" -gt 0 ]; do
  IGNORE_TAG=$( echo "$1" | sed 's/\([^=]*\)=.*/\1/' )
  IGNORE_TAGS="${IGNORE_TAGS}|^ *${IGNORE_TAG} "
  shift
done

SELECTED_HOSTS=$(
  query-hosts-tags hosts "${TAGS}" \
    | fzf \
      --multi \
      --exit-0 \
      --select-1 \
      --height=10 \
      --layout=reverse \
      --preview="query-hosts-tags tags {} | grep -vE '${IGNORE_TAGS}'" \
      --preview-window='right:60%:border-left'
)

[ -n "${SELECTED_HOSTS}" ] || exit

if [ "$( echo "${SELECTED_HOSTS}" | wc -l )" -eq 1 ]; then
  ssh "${SELECTED_HOSTS}"
else
  echo "${SELECTED_HOSTS}" | xpanes -t -s -c "ssh {}"
fi

