#!/bin/sh

TASK=$(
  task -n ids \
    | fzf --reverse \
          --no-multi \
          --info hidden \
          --header "$( printf '\n' )" \
          --print-query \
          --prompt 'start task ' \
    | tail -n1
)

[ -n "${TASK}" ] || exit

TASK_ID="$( echo "${TASK}" | cut -d' ' -f1 )"
TASK_NAME="$( echo "${TASK}" | sed 's/[^ ]* *\(.*\)/\1/' )"

printf 'Id: %s\n' "${TASK_ID}"

if [ -n "${TASK_NAME}" ]; then
  printf 'Name: %s\n' "${TASK_NAME}"
else
  printf 'Name: '
  read -r TASK_NAME
fi

printf '\n'
printf 'Log [y/N]: '
read -r LOG

TASK_DESC=
if [ "${LOG}" = 'Y' ] || [ "${LOG}" = 'y' ]; then
    printf 'Description: '
    read -r TASK_DESC
fi

printf '\n'
while true; do
  printf 'Pomodoro duration (min): '
  read -r POMODORO_DURATION

  case "${POMODORO_DURATION}" in
    *[!0-9]*)
      echo 'duration must be an integer' >&2
      continue
      ;;
  esac

  break
done

printf '\n'
printf 'Do not disturb [y/N]: '
read -r DO_NOT_DISTURB

if [ "${LOG}" = 'Y' ] || [ "${LOG}" = 'y' ]; then
  task start "${TASK_ID}" "${TASK_NAME}" "${TASK_DESC}"
else
  task -q start "${TASK_ID}" "${TASK_NAME}" "${TASK_DESC}"
fi

if [ -n "${POMODORO_DURATION}" ]; then
  nohup \
    pomodoro start "${POMODORO_DURATION}" \
    > /dev/null 2>&1
fi

if [ "${DO_NOT_DISTURB}" = 'Y' ] || [ "${DO_NOT_DISTURB}" = 'y' ]; then
  nohup \
    do-not-disturb -d "${POMODORO_DURATION}" -w "${TASK_ID} ${TASK_NAME}" enable \
    > /dev/null 2>&1
fi
