#!/bin/sh

swaymsg -q exec 'foot -T sway_dashboard -o locked-title=yes tmux-env general dashboard'
sleep 0.1
swaymsg move window to scratchpad

swaymsg -q rename workspace to '1:projects'
tmux-env -b projects arch_system
tmux-env -b projects dotfiles
swaymsg -q exec "foot  -T \"projects environment\" -o locked-title=yes tmux -L projects attach-session -t arch_system"

swaymsg -q workspace '2:web'
# shellcheck disable=SC1083
swaymsg -q exec '{app/web_browser} -r default'

swaymsg -q workspace '1:projects'
sleep 0.1
swaymsg scratchpad show
