#!/bin/sh

TMP_FILE="$( mktemp )"
trap 'rm -f "${TMP_FILE}"' EXIT

swaymsg -q rename workspace to '1:projects'
tmux-env -b projects arch_system
tmux-env -b projects dotfiles
swaymsg -q exec "foot  -T \"projects environment\" -o locked-title=yes tmux -L projects attach-session -t arch_system"

swaymsg -q workspace '2:web'
# shellcheck disable=SC1083
swaymsg -q exec '{app/web_browser} -r default'

swaymsg -q workspace '1:projects'

sleep 0.1

{
  printf "$( tput bold )%s\n\n" 'TODAY';
  schedule today;

  printf "\n$( tput bold )%s\n\n" 'TODO'
  cat "${XDG_NOTES_DIR:-$HOME/Notes}/todo.md";
} > "${TMP_FILE}"

sway-quick-command "${PAGER}" "${TMP_FILE}"
