#!/bin/sh

TASK_ID=$(
  task ids \
    | fzf --reverse \
          --no-multi \
          --info hidden \
          --header "$( printf '\n' )" \
          --print-query \
          --prompt 'start task ' \
    | tail -n1
)

[ -n "${TASK_ID}" ] || exit

printf 'Task: %s\n' "${TASK_ID}"

printf 'Description: '
read -r TASK_DESC

printf 'Log at its end [y/N]: '
read -r LOG

while true; do
  printf 'Pomodoro duration (min): '
  read -r POMODORO_DURATION

  case "${POMODORO_DURATION}" in
    *[!0-9]*)
      echo 'duration must be an integer' >&2
      continue
      ;;
  esac

  break
done

printf 'Do not disturb [Y/n]: '
read -r DO_NOT_DISTURB

if [ "${LOG}" = 'Y' ] || [ "${LOG}" = 'y' ]; then
  task start "${TASK_ID}" "${TASK_DESC}"
else
  task -n start "${TASK_ID}" "${TASK_DESC}"
fi

if [ -n "${POMODORO_DURATION}" ]; then
  nohup \
    pomodoro start "${POMODORO_DURATION}" \
    > /dev/null 2>&1
fi

if [ -z "${DO_NOT_DISTURB}" ] \
   || [ "${DO_NOT_DISTURB}" = 'Y' ] \
   || [ "${DO_NOT_DISTURB}" = 'y' ]; then
  nohup \
    do-not-disturb -d "${POMODORO_DURATION}" -w "${TASK_ID}" enable \
    > /dev/null 2>&1
fi
