#!/bin/sh

print_item() {
  HEADER="$1"
  VALUE="$2"

  printf "%s\n" "${HEADER}"
  # shellcheck disable=SC1083
  printf "$(tput setaf {color/base09/number} )%s$(tput sgr0)\n" "${VALUE}"
}

{
  print_item 'User' "${LOGNAME}"
  print_item 'Host' "$(cat /proc/sys/kernel/hostname )"
  print_item 'Dir' "${PWD}"

  if git rev-parse --git-dir > /dev/null 2>&1; then
    print_item 'Branch' "$( git current-branch )"
  fi
} | pr -l1 -s -2 | expand  -t 8
