#!/bin/sh

ACTION=$(
  {
    echo 'Lock screen';
    echo 'Suspend';
    echo 'Logout';
    echo 'Shut down';
    echo 'Reboot';
  } \
    | fuzzel --dmenu \
        --prompt='Execute ' \
        --anchor='top' \
        --width=10 \
        --lines=5
)

case "${ACTION}" in
  Lock\ screen) swaylock ;;
  Suspend)      systemctl suspend ;;
  Logout)       swaymsg -q exit ;;
  Shut\ down)   systemctl poweroff ;;
  Reboot)       systemctl reboot ;;
esac
