#!/bin/sh

init_variables() {
  COMMAND=${0##*/}

  FIFO_FILE="${XDG_RUNTIME_DIR:-/tmp}/weechat/weechat_fifo"

  BUFFER=
}

parse_command_line() {
  BUFFER=$1
}

validate_command_line() {
  if [ ! -p "${FIFO_FILE}" ]; then
    exit_error "FIFO file not present"
  fi
}

exit_error() {
  [ -z "$1" ] || echo "${COMMAND}: $1"
  exit 1
} >&2

fifo_send() {
  while read -r LINE; do
    echo "${BUFFER} *${LINE}" > "${FIFO_FILE}"
  done
}

init_variables
parse_command_line "$@"
validate_command_line

fifo_send
