#!/bin/sh

# shellcheck disable=SC2009
if ps -A -o args | grep -q '^/usr/bin/wmenu'; then
  exit 1
fi

EXECUTABLE="$(
  printf '%s' "${PATH}" \
    | tr ':' '\n' \
    | xargs -I {} find -L {} -type f 2> /dev/null \
    | sed 's|.*/\([^/]*\)$|\1|' \
    | sort \
    | wmenu -p Run
)"

if [ -z "${EXECUTABLE}" ]; then
  exit 1
fi

"${EXECUTABLE}"
