#!/bin/sh

# shellcheck disable=SC1083

case "${1%%:*}" in
  http|https) exec {app/web_browser} "$1" ;;
esac

case "$( echo "${1##*.}" | tr '[:upper:]' '[:lower:]')" in
  asc|txt) exec {app/text_editor} "$1" ;;
  htm|html) exec {app/web_browser} "$1" ;;
  cbr|cbz|epub|pdf) exec {app/document_viewer} "$1" ;;
  jpg|jpeg|jfif|png|gif|svg) exec {app/image_viewer} "$1" ;;
esac

exec /usr/bin/xdg-open "$@"
