xdg-utils:
	@echo -n "… setup xdg-utils"

    # create necessary directories
	@mkdir -p "$(CONFIG_DIR)"

    # copy config files
	@cp "xdg-utils/mimeapps.list" "$(CONFIG_DIR)/mimeapps.list"

	@echo -e "\r✔ setup xdg-utils"
