aria2:
	@echo -n "… setup aria2"

    # create necessary directories
	@mkdir -p "$(CONFIG_DIR)/aria2"

    # copy config files
	@cp "aria2/aria2.conf" "$(CONFIG_DIR)/aria2/aria2.conf"

	@echo -e "\r✔ setup aria2"
