ncmpcpp:
	@echo -n "… setup ncmpcpp"

    # create necessary directories
	@mkdir -p "$(CONFIG_DIR)/ncmpcpp"
	@mkdir -p "$(DATA_DIR)/ncmpcpp"

    # copy config files
	@cp "ncmpcpp/config" "$(CONFIG_DIR)/ncmpcpp/config"
	@cp "ncmpcpp/bindings" "$(CONFIG_DIR)/ncmpcpp/bindings"

	@echo -e "\r✔ setup ncmpcpp"
