i3blocks-chat(1perso)

# NAME

i3blocks-chat - Report the chat status for i3blocks

# SYNOPSIS

i3blocks-chat

# DESCRIPTION

Print the chat status for i3blocks

# OPTIONS

None

# OPERANDS

None

# ENVIRONMENT VARIABLES

_XDG_RUNTIME_DIR_
	Path to user-specific base directory to store runtime files++
If unset, defaults to /tmp

# FILES

_$XDG_RUNTIME_DIR/chat_count_
	Contains the count of important chats to display

# DEPENDENCIES

- i3blocks-mode
- pidof
