#! /usr/bin/env zsh

FILE_PATH="${XDG_DATA_HOME:-$HOME/.local/share}/sway/do_not_disturb"

# only display something if the mode is on
[[ -f "${FILE_PATH}" ]] || exit 0

echo "<span foreground='#dc322f'> Do not disturb</span>"
