all: libqalculate-configs

libqalculate-configs:
	$(start_setup)

	mkdir -p $(DESTDIR)$(CONFIG_DIR)/qalculate

	$(setup_file)/configs/libqalculate/qalc.cfg > $(DESTDIR)$(CONFIG_DIR)/qalculate/qalc.cfg
