all: sounds

sounds:
	mkdir -p $(DESTDIR)$(DATA_DIR)/sounds

	cp files/data/sounds/end_pomodoro.ogg $(DESTDIR)$(DATA_DIR)/sounds/end_pomodoro.ogg
	cp files/data/sounds/low_battery.ogg  $(DESTDIR)$(DATA_DIR)/sounds/low_battery.ogg
	cp files/data/sounds/reminder.ogg     $(DESTDIR)$(DATA_DIR)/sounds/reminder.ogg
