all: sounds

sounds:
	mkdir -p $(DESTDIR)$(DATA_DIR)/sounds

	cp files/data/sounds/end_pomodoro.wav $(DESTDIR)$(DATA_DIR)/sounds/end_pomodoro.wav
	cp files/data/sounds/low_battery.wav  $(DESTDIR)$(DATA_DIR)/sounds/low_battery.wav
	cp files/data/sounds/reminder.ogg     $(DESTDIR)$(DATA_DIR)/sounds/reminder.ogg
