qalculate:
	@echo -n "… setup qalculate"

    # create necessary directories
	@mkdir -p "$(CONFIG_DIR)/qalculate"

    # copy config files
	@cp "qalculate/qalc.cfg" "$(CONFIG_DIR)/qalculate/qalc.cfg"

	@echo -e "\r✔ setup qalculate"
