qalculate:
	$(start_setup)

    # create necessary directories
	@mkdir -p "$(CONFIG_DIR)/qalculate"

    # copy config files
	@cp "qalculate/qalc.cfg" "$(CONFIG_DIR)/qalculate/qalc.cfg"

	$(end_setup)
