#!/bin/sh
# commands used:
# - create_workspace
# - focus_window_title
# - newsboat
# - swaymsg
# - termite
# - tmux

TITLE='News reader'

# try to focus existing window if it exists
focus_window_title "${TITLE}" && exit

# launch new app otherwise in new workspace
create_workspace 'news'
swaymsg -q exec \
  "termite \
   -t \"${TITLE}\" \
   -e 'tmux new-session -A -s news \"newsboat\"'"
