#!/bin/sh
# commands used:
# - create_workspace
# - focus_window_title
# - swaymsg
# - termite
# - tmux
# - weechat

TITLE='Chat client'

# try to focus existing window if it exists
focus_window_title "${TITLE}" && exit

# launch new app otherwise in new workspace
create_workspace 'chat'
swaymsg -q exec \
  "termite \
   -t \"${TITLE}\" \
   -e 'tmux new-session -A -s chat \"weechat\"'"
