#!/bin/sh
# commands used:
# - create_workspace
# - focus_window_title
# - swaymsg
# - termite
# - tmux-env

ENV_NAME="$1"
SESSION_NAME="$2"

TITLE="${ENV_NAME} environment"

# create env in background
# will do nothing if already exists
tmux-env -b "${ENV_NAME}" "${SESSION_NAME}"

# try to focus existing window if it exists
focus_window_title "${TITLE}" && exit

# launch new app otherwise in new workspace
create_workspace "${ENV_NAME}"
swaymsg -q exec \
  "termite \
   -t \"${TITLE}\" \
   -e 'tmux-env ${ENV_NAME} ${SESSION_NAME}'"
