#!/bin/sh
# commands used:
# - focus_window_title
# - ncmpcpp
# - swaymsg
# - systemctl
# - termite
# - tmux

TITLE='sway_music'

# try to focus existing window if it exists
focus_window_title "${TITLE}" && exit

# launch music server and app otherwise
if ! systemctl --user is-active mopidy.service; then
  systemctl --user start mopidy.service
fi

swaymsg -q exec \
  "termite \
   -t \"${TITLE}\" \
   -e 'tmux new-session -A -s music \"ncmpcpp\"'"
