#!/bin/sh
# commands used:
# - command_input_exec
# - focus_window_title
# - swaymsg
# - termite

# try to focus existing window if it exists
focus_window_title 'sway_command_input' && exit

# quote arguments for usage in next command
ARGUMENTS=
while [ "$#" -gt 0 ]; do
  case "$1" in
    -*) ARGUMENTS="${ARGUMENTS} $1";;
    *) ARGUMENTS="${ARGUMENTS} '$1'";;
  esac
  shift
done

# launch new command input window otherwise
swaymsg -q exec \
  "termite \
   -e \"command_input_exec ${ARGUMENTS}\" \
   -c ${HOME}/.config/termite/config_command_input \
   -t sway_command_input"
