#!/bin/sh
# commands used:
# - app_tmux_env
# - fzf_launcher

ENV_NAME="$1"

SESSION=$(
  {
    echo NEW;
    find "${XDG_DATA_HOME:-$HOME/.local/share}/env/tmux/${ENV_NAME}" \
      -type f -name '*.sh' -exec basename {} .sh \; \
      | sort
  } \
  | fzf_launcher "open ${ENV_NAME%s} "
)

[ -n "${SESSION}" ] || exit

[ "${SESSION}" = 'NEW' ] && SESSION=

app_tmux_env "${ENV_NAME}" "${SESSION}"
