#!/bin/sh
# commands used:
# - command_input
# - jq
# - swaymsg

# rename current workspace

CURRENT_WORKSPACE_NUMBER=$(
  swaymsg -t get_workspaces \
    | jq -r \
      ".[]|select(.focused==true)|.name" \
    | sed 's/\([0-9]*\).*/\1/'
)

command_input \
  -F "rename workspace to ${CURRENT_WORKSPACE_NUMBER}:%s" \
  -P 'rename workspace: '
