#!/bin/sh
# commands used:
# - jq
# - sway-command-input
# - swaymsg

# rename current workspace

CURRENT_WORKSPACE_NUMBER=$(
  swaymsg -t get_workspaces \
    | jq -r \
      ".[]|select(.focused==true)|.name" \
    | sed 's/\([0-9]*\).*/\1/'
)

sway-command-input \
  -F "rename workspace to ${CURRENT_WORKSPACE_NUMBER}:%s" \
  -P 'rename workspace: '
