#!/bin/sh
# commands used:
# - sway-command-input-exec
# - sway-focus-window-title
# - swaymsg
# - termite

# try to focus existing window if it exists
sway-focus-window-title 'sway_command_input' && exit

# quote arguments for usage in next command
ARGUMENTS=
while [ "$#" -gt 0 ]; do
  case "$1" in
    -*) ARGUMENTS="${ARGUMENTS} $1";;
    *) ARGUMENTS="${ARGUMENTS} '$1'";;
  esac
  shift
done

# launch new command input window otherwise
swaymsg -q exec \
  "termite \
   -e \"sway-command-input-exec ${ARGUMENTS}\" \
   -c ${XDG_CONFIG_HOME:-$HOME/.config}/termite/config_command_input \
   -t sway_command_input"
