#!/bin/sh
# commands used:
# - sway-focus-window-title
# - swaymsg
# - termite

COMMAND="$*"

# try to focus existing window if it exists
sway-focus-window-title 'sway_launcher' && exit

# launch new launcher otherwise
swaymsg -q exec \
  "termite \
   -e \"${COMMAND}\" \
   -c ${XDG_CONFIG_HOME:-$HOME/.config}/termite/config_launcher \
   -t sway_launcher"
