#!/bin/sh
# commands used:
# - sway-fzf-launcher
# - swaylock
# - swaymsg
# - systemctl

ACTION=$(
  {
    echo '  Lock screen';
    echo '  Suspend';
    echo '  Logout';
    echo '  Shutdown';
    echo '  Reboot';
  } \
  | sway-fzf-launcher 'execute '
)

case "${ACTION}" in
  *Lock\ screen) swaylock ;;
  *Suspend)      systemctl suspend ;;
  *Logout)       swaymsg -q exit ;;
  *Shutdown)     systemctl poweroff ;;
  *Reboot)       systemctl reboot ;;
esac
