#!/bin/sh
# commands used:
# - column
# - exec-desktop-entry
# - stat
# - sway-fzf-launcher
# - swaymsg

APP_DESKTOP_FILES_PATH="${XDG_DATA_HOME:-$HOME/.local/share}/applications"
CACHE_LIST_PATH="${XDG_CACHE_HOME:-$HOME/.cache}/sway/launch_app"

should_build_cache() {
  [ -f "${CACHE_LIST_PATH}" ] || return 0

  CACHE_LAST_MODIFIED=$(
    stat -c '%Y' "${CACHE_LIST_PATH}"
  )

  FILES_LAST_MODIFIED=$(
    find "${APP_DESKTOP_FILES_PATH}" \
      -type f -exec stat -c '%Y' {} \; \
      | sort \
      | tail -n 1
  )

  [ "${CACHE_LAST_MODIFIED}" -lt "${FILES_LAST_MODIFIED}" ]
}

build_cache() {
  mkdir -p "$( dirname "${CACHE_LIST_PATH}" )"

  for APP_DESKTOP_FILE in "${APP_DESKTOP_FILES_PATH}"/*.desktop; do
    APP_NAME=$(
      sed -n 's/^Name=\(.*\)/\1/p' "${APP_DESKTOP_FILE}"
    )
    APP_GENERIC_NAME=$(
      sed -n 's/^GenericName=\(.*\)/\1/p' "${APP_DESKTOP_FILE}"
    )
    APP_ICON=$(
      sed -n 's/^Icon=\(.*\)/\1/p' "${APP_DESKTOP_FILE}"
    )
    echo "${APP_ICON}  ${APP_GENERIC_NAME}&${APP_NAME}&${APP_DESKTOP_FILE}"
  done \
    | sort \
    | column -t -R 2 -s '&' \
    > "${CACHE_LIST_PATH}"
}

should_build_cache && build_cache

SELECTED_APP=$(
  sway-fzf-launcher 'run app ' --with-nth ..-2 < "${CACHE_LIST_PATH}" \
    | sed 's/.* \(.*\)$/\1/'
)

if [ -n "${SELECTED_APP}" ]; then
  # #FIXME: not sure why running exec-desktop-entry directly without using swaymsg
  # doesn't work when ran from the launcher
  swaymsg -q exec \
    "exec-desktop-entry ${SELECTED_APP}"
fi
