#!/bin/sh
# commands used:
# - i3blocks-mode
# - pidof

COUNT_FILE_PATH="${XDG_RUNTIME_DIR}/chat_count"

MODE="$( i3blocks-mode )"

# don't show anything if weechat is not running
pidof weechat > /dev/null || exit 0

# show 0 notification if there is no file
# just to let us know at least that weechat is running
if [ ! -f "${COUNT_FILE_PATH}" ]; then
  if [ "${MODE}" = 'full' ]; then
    echo "<span foreground='#{color/base09/hex}'></span> 0"
  else
    echo "<span foreground='#{color/base09/hex}'></span>"
  fi
fi

COUNT=$( cat "${COUNT_FILE_PATH}" )

if [ "${COUNT}" -gt 0 ]; then
  if [ "${MODE}" = 'full' ]; then
    echo "<span foreground='#{color/notice/hex}'> ${COUNT}</span>"
  else
    echo "<span foreground='#{color/notice/hex}'></span>"
  fi
else
  if [ "${MODE}" = 'full' ]; then
    echo "<span foreground='#{color/base09/hex}'></span> 0"
  else
    echo "<span foreground='#{color/base09/hex}'></span>"
  fi
fi
