all: zsh-configs

zsh-configs:
	setup/setup-config zsh/zlogin                                                                 $(HOME)/.zlogin
	setup/setup-config zsh/zprofile                                                               $(HOME)/.zprofile
	setup/setup-config zsh/zshenv                                                                 $(HOME)/.zshenv
	setup/setup-config zsh/zshrc                                                                  $(HOME)/.zshrc
	setup/setup-config zsh/config.d/10-general.zsh                                                $(HOME)/.zsh/config.d/10-general.zsh
	setup/setup-config zsh/config.d/11-history.zsh                                                $(HOME)/.zsh/config.d/11-history.zsh
	setup/setup-config zsh/config.d/12-prompt.zsh                                                 $(HOME)/.zsh/config.d/12-prompt.zsh
	setup/setup-config zsh/config.d/20-completion.zsh                                             $(HOME)/.zsh/config.d/20-completion.zsh
	setup/setup-config zsh/config.d/30-bindings.zsh                                               $(HOME)/.zsh/config.d/30-bindings.zsh
	setup/setup-config zsh/config.d/40-aliases.zsh                                                $(HOME)/.zsh/config.d/40-aliases.zsh
	setup/setup-config zsh/config.d/41-variables.zsh                                              $(HOME)/.zsh/config.d/41-variables.zsh
	setup/setup-config zsh/config.d/90-plugins.zsh                                                $(HOME)/.zsh/config.d/90-plugins.zsh
	setup/setup-config zsh/completions/_backup                                                    $(HOME)/.zsh/completions/_backup
	setup/setup-config zsh/completions/_bluetooth                                                 $(HOME)/.zsh/completions/_bluetooth
	setup/setup-config zsh/completions/_clock                                                     $(HOME)/.zsh/completions/_clock
	setup/setup-config zsh/completions/_do-not-disturb                                            $(HOME)/.zsh/completions/_do-not-disturb
	setup/setup-config zsh/completions/_documentation                                             $(HOME)/.zsh/completions/_documentation
	setup/setup-config zsh/completions/_extract-tokens                                            $(HOME)/.zsh/completions/_extract-tokens
	setup/setup-config zsh/completions/_http-env                                                  $(HOME)/.zsh/completions/_http-env
	setup/setup-config zsh/completions/_http-stats                                                $(HOME)/.zsh/completions/_http-stats
	setup/setup-config zsh/completions/_line-by-line                                              $(HOME)/.zsh/completions/_line-by-line
	setup/setup-config zsh/completions/_loop                                                      $(HOME)/.zsh/completions/_loop
	setup/setup-config zsh/completions/_mount-device                                              $(HOME)/.zsh/completions/_mount-device
	setup/setup-config zsh/completions/_mysql-env                                                 $(HOME)/.zsh/completions/_mysql-env
	setup/setup-config zsh/completions/_notify                                                    $(HOME)/.zsh/completions/_notify
	setup/setup-config zsh/completions/_pomodoro                                                  $(HOME)/.zsh/completions/_pomodoro
	setup/setup-config zsh/completions/_project-path                                              $(HOME)/.zsh/completions/_project-path
	setup/setup-config zsh/completions/_proxy                                                     $(HOME)/.zsh/completions/_proxy
	setup/setup-config zsh/completions/_query-hosts-tags                                          $(HOME)/.zsh/completions/_query-hosts-tags
	setup/setup-config zsh/completions/_read-news                                                 $(HOME)/.zsh/completions/_read-news
	setup/setup-config zsh/completions/_schedule                                                  $(HOME)/.zsh/completions/_schedule
	setup/setup-config zsh/completions/_screencast                                                $(HOME)/.zsh/completions/_screencast
	setup/setup-config zsh/completions/_screenshot                                                $(HOME)/.zsh/completions/_screenshot
	setup/setup-config zsh/completions/_somafm                                                    $(HOME)/.zsh/completions/_somafm
	setup/setup-config zsh/completions/_ssh-tags                                                  $(HOME)/.zsh/completions/_ssh-tags
	setup/setup-config zsh/completions/_task                                                      $(HOME)/.zsh/completions/_task
	setup/setup-config zsh/completions/_theme                                                     $(HOME)/.zsh/completions/_theme
	setup/setup-config zsh/completions/_time-tracker                                              $(HOME)/.zsh/completions/_time-tracker
	setup/setup-config zsh/completions/_time-tracker-day                                          $(HOME)/.zsh/completions/_time-tracker-day
	setup/setup-config zsh/completions/_tmux-env                                                  $(HOME)/.zsh/completions/_tmux-env
	setup/setup-config zsh/completions/_url                                                       $(HOME)/.zsh/completions/_url
	setup/setup-config zsh/completions/git/_git-argument                                          $(HOME)/.zsh/completions/git/_git-argument
	setup/setup-config zsh/completions/git/_git-ci                                                $(HOME)/.zsh/completions/git/_git-ci
	setup/setup-config zsh/completions/git/_git-hist                                              $(HOME)/.zsh/completions/git/_git-hist
	setup/setup-config zsh/completions/git/_git-mgrbma                                            $(HOME)/.zsh/completions/git/_git-mgrbma
	setup/setup-config zsh/completions/git/_git-push-current-branch                               $(HOME)/.zsh/completions/git/_git-push-current-branch
	setup/setup-config zsh/completions/git/_git-run-command                                       $(HOME)/.zsh/completions/git/_git-run-command
	setup/setup-config zsh/completions/git/_git-sed                                               $(HOME)/.zsh/completions/git/_git-sed
	setup/setup-config zsh/completions/git/_git-semantic-tag                                      $(HOME)/.zsh/completions/git/_git-semantic-tag
	setup/setup-config zsh/completions/git/_git-stamp                                             $(HOME)/.zsh/completions/git/_git-stamp
	setup/setup-config zsh/completions/git/_git-url                                               $(HOME)/.zsh/completions/git/_git-url
	setup/setup-config zsh/functions/dirsum                                                       $(HOME)/.zsh/functions/dirsum
	setup/setup-config zsh/functions/goto-project                                                 $(HOME)/.zsh/functions/goto-project
	setup/setup-config zsh/functions/init-todo                                                    $(HOME)/.zsh/functions/init-todo
	setup/setup-config zsh/functions/mkcd                                                         $(HOME)/.zsh/functions/mkcd
	setup/setup-config zsh/functions/task-log                                                     $(HOME)/.zsh/functions/task-log
	setup/setup-config zsh/functions/time-tracker-overview                                        $(HOME)/.zsh/functions/time-tracker-overview
	setup/setup-config zsh/functions/time-tracker-sum                                             $(HOME)/.zsh/functions/time-tracker-sum
	setup/setup-config zsh/functions/highlighters/_zsh_highlight_add_keywords_highlights          $(HOME)/.zsh/functions/_zsh_highlight_add_keywords_highlights
	setup/setup-config zsh/functions/highlighters/_zsh_highlight_add_positional_params_highlights $(HOME)/.zsh/functions/_zsh_highlight_add_positional_params_highlights
	setup/setup-config zsh/functions/highlighters/_zsh_highlight_highlighter_http_env_paint       $(HOME)/.zsh/functions/_zsh_highlight_highlighter_http_env_paint
	setup/setup-config zsh/functions/highlighters/_zsh_highlight_highlighter_http_env_predicate   $(HOME)/.zsh/functions/_zsh_highlight_highlighter_http_env_predicate
	setup/setup-config zsh/functions/highlighters/_zsh_highlight_highlighter_mysql_env_paint      $(HOME)/.zsh/functions/_zsh_highlight_highlighter_mysql_env_paint
	setup/setup-config zsh/functions/highlighters/_zsh_highlight_highlighter_mysql_env_predicate  $(HOME)/.zsh/functions/_zsh_highlight_highlighter_mysql_env_predicate

	# same git completions
	ln -sf _git-argument $(DESTDIR)$(HOME)/.zsh/completions/git/_git-bwc
	ln -sf _git-argument $(DESTDIR)$(HOME)/.zsh/completions/git/_git-bwi
	ln -sf _git-argument $(DESTDIR)$(HOME)/.zsh/completions/git/_git-bwr
	ln -sf _git-argument $(DESTDIR)$(HOME)/.zsh/completions/git/_git-commit-description
	ln -sf _git-argument $(DESTDIR)$(HOME)/.zsh/completions/git/_git-commit-issue-id
	ln -sf _git-argument $(DESTDIR)$(HOME)/.zsh/completions/git/_git-commit-review-id
	ln -sf _git-argument $(DESTDIR)$(HOME)/.zsh/completions/git/_git-commit-subject
	ln -sf _git-argument $(DESTDIR)$(HOME)/.zsh/completions/git/_git-head
	ln -sf _git-argument $(DESTDIR)$(HOME)/.zsh/completions/git/_git-rbi
	ln -sf _git-argument $(DESTDIR)$(HOME)/.zsh/completions/git/_git-sh
	ln -sf _git-argument $(DESTDIR)$(HOME)/.zsh/completions/git/_git-sh0
	ln -sf _git-argument $(DESTDIR)$(HOME)/.zsh/completions/git/_git-urlc
	ln -sf _git-argument $(DESTDIR)$(HOME)/.zsh/completions/git/_git-urli
	ln -sf _git-argument $(DESTDIR)$(HOME)/.zsh/completions/git/_git-urlr
	ln -sf _git-url      $(DESTDIR)$(HOME)/.zsh/completions/git/_git-browse

	# clear completion cache
	rm -f $(DESTDIR)$(HOME)/.zcompdump
