# locale settings
export LANG=en_GB.UTF-8
export LC_ADDRESS=en_GB.UTF-8
export LC_COLLATE=C
export LC_CTYPE=en_GB.UTF-8
export LC_IDENTIFICATION=en_GB.UTF-8
export LC_MEASUREMENT=en_GB.UTF-8
export LC_MESSAGES=en_GB.UTF-8
export LC_MONETARY=en_GB.UTF-8
export LC_NAME=en_GB.UTF-8
export LC_NUMERIC=en_GB.UTF-8
export LC_PAPER=en_GB.UTF-8
export LC_TELEPHONE=en_GB.UTF-8
export LC_TIME=en_GB.UTF-8

# Needed to use true colors in some applications
export COLORTERM='truecolor'

# Add custom man pages location to man path
export MANPATH="${XDG_DATA_HOME:-$HOME/.local/share}/man:/usr/share/man"

# fix color usage in man output
export MANROFFOPT="-P -c"

# disable flow control within apps
stty -ixon 2> /dev/null
