# load all individual configs in filename order
for conf in "${HOME}/.zsh/config.d/"*.zsh; do
  source "${conf}"
done
unset conf

# add personal functions directories
fpath=(
  "${HOME}/.zsh/functions/"
  $fpath
)

# autoload all functions
for func in "${HOME}/.zsh/functions"/*; do
  autoload -Uz "${func##*/}"
done
unset func
