#!/bin/sh

# list hexadecimal values of base colors

THEME="$1"

if [ -z "${THEME}" ]; then
  printf 'missing theme argument\n' >&2
  exit 1
fi

BASE_COLORS_FILE="defs/colors/base_${THEME}"

if [ ! -f "${BASE_COLORS_FILE}" ]; then
  printf "invalid theme '%s'\n" "${THEME}" >&2
  exit 1
fi

sed -n 's/| base0[[:alnum:]] | #\([[:alnum:]]\+\) |.*/\1/p' "${BASE_COLORS_FILE}"
