#!/bin/sh
# commands used:
# - column
# - pacman

init_variables() {
  COMMAND=${0##*/}

  ONLY_DIFF=0

  TYPE=
}

show_usage() {
  cat <<- EOF
	usage: ${COMMAND} [<options>]

	Check and report packages versions:
	- version installed on the system
	- version listed in the docs

	Options:
	  -d    only list packages where versions are different
	  -h    show this message only
	EOF
}

parse_command_line() {
  while getopts dh OPT; do
    case "${OPT}" in
      d) ONLY_DIFF=1 ;;
      h) show_usage; exit 0 ;;
      ?) exit_error ;;
    esac
  done

  shift $(( OPTIND - 1 ))
}

# shellcheck disable=SC2120
exit_error() {
  [ -z "$1" ] || echo "${COMMAND}: $1"
  echo "Try '${COMMAND} -h' for more information."
  exit 1
} >&2

docs_version() {
  ITEM="$1"

  sed -n "s#^| ${ITEM} .*| \[\(.*\)\].*#\1#p" "doc/${TYPE}.md"
}

pacman_version() {
  PACKAGE="$1"

  PACMAN_INFO=$(
    pacman -Qi "${PACKAGE}" 2> /dev/null
  )

  if [ -z "${PACMAN_INFO}" ]; then
    # try with -git suffix if package couldn't be found
    PACMAN_INFO=$(
      pacman -Qi "${PACKAGE}-git" 2> /dev/null
    )
  fi

  if [ -z "${PACMAN_INFO}" ]; then
    echo 'unknown'
    return
  fi

  # extract version without the release number
  echo "${PACMAN_INFO}" \
    | sed -n 's/^Version *: \(.*\)\-[0-9]*/\1/p'
}

report_item() {
  while read -r ITEM; do
    VERSION_INSTALLED=$( pacman_version "${ITEM}" )

    # ignore plugins not managed by packages manager
    if [ "${TYPE}" = 'PLUGINS' ] && [ "${VERSION_INSTALLED}" = 'unknown' ]; then
      continue
    fi

    VERSION_DOCS=$( docs_version "${ITEM}" )

    if [ "${ONLY_DIFF}" -eq 1 ] \
       && [ "${VERSION_INSTALLED}" = "${VERSION_DOCS}" ]; then
      continue
    fi

    printf '%s %s %s\n' \
      "${ITEM}" \
      "${VERSION_DOCS}" \
      "${VERSION_INSTALLED}"
  done
}

list_items() {
  sed -n 's#^| \([a-z][^ ]*\) .*#\1#p' "doc/${TYPE}.md"
}

report_all() {
  {
    for TYPE in PACKAGES PLUGINS; do
      list_items | report_item
    done
  } \
    | sort \
    | column -t
}

init_variables
parse_command_line "$@"

report_all
