all: git-configs

git-configs:
	setup/setup-config git/config                $(CONFIG_DIR)/git/config
	setup/setup-config git/ignore                $(CONFIG_DIR)/git/ignore
	setup/setup-config git/config.d/aliases      $(CONFIG_DIR)/git/config.d/aliases
	setup/setup-config git/config.d/general      $(CONFIG_DIR)/git/config.d/general
	setup/setup-config git/config.d/style        $(CONFIG_DIR)/git/config.d/style
	setup/setup-config git/template/info/exclude $(CONFIG_DIR)/git/template/info/exclude
