all: sway-configs

sway-configs:
	setup/setup-config sway/config            $(CONFIG_DIR)/sway/config
	setup/setup-config sway/config.d/bar      $(CONFIG_DIR)/sway/config.d/bar
	setup/setup-config sway/config.d/bindings $(CONFIG_DIR)/sway/config.d/bindings
	setup/setup-config sway/config.d/general  $(CONFIG_DIR)/sway/config.d/general
	setup/setup-config sway/config.d/inputs   $(CONFIG_DIR)/sway/config.d/inputs
	setup/setup-config sway/config.d/outputs  $(CONFIG_DIR)/sway/config.d/outputs
	setup/setup-config sway/config.d/rules    $(CONFIG_DIR)/sway/config.d/rules
	setup/setup-config sway/config.d/style    $(CONFIG_DIR)/sway/config.d/style
	setup/setup-config sway/swaynag/config    $(CONFIG_DIR)/swaynag/config
