all: sway-scripts

sway-scripts:
	$(start_setup)

	mkdir -p $(DESTDIR)$(BIN_DIR)

	$(setup_scripts_file)/sway/sway-app-chat                  > $(DESTDIR)$(BIN_DIR)/sway-app-chat
	$(setup_scripts_file)/sway/sway-app-mail                  > $(DESTDIR)$(BIN_DIR)/sway-app-mail
	$(setup_scripts_file)/sway/sway-app-monitor               > $(DESTDIR)$(BIN_DIR)/sway-app-monitor
	$(setup_scripts_file)/sway/sway-app-music                 > $(DESTDIR)$(BIN_DIR)/sway-app-music
	$(setup_scripts_file)/sway/sway-app-news                  > $(DESTDIR)$(BIN_DIR)/sway-app-news
	$(setup_scripts_file)/sway/sway-app-tmux-env              > $(DESTDIR)$(BIN_DIR)/sway-app-tmux-env
	$(setup_scripts_file)/sway/sway-command-input             > $(DESTDIR)$(BIN_DIR)/sway-command-input
	$(setup_scripts_file)/sway/sway-command-input-exec        > $(DESTDIR)$(BIN_DIR)/sway-command-input-exec
	$(setup_scripts_file)/sway/sway-create-workspace          > $(DESTDIR)$(BIN_DIR)/sway-create-workspace
	$(setup_scripts_file)/sway/sway-focus-window-title        > $(DESTDIR)$(BIN_DIR)/sway-focus-window-title
	$(setup_scripts_file)/sway/sway-fzf-launcher              > $(DESTDIR)$(BIN_DIR)/sway-fzf-launcher
	$(setup_scripts_file)/sway/sway-launch-app                > $(DESTDIR)$(BIN_DIR)/sway-launch-app
	$(setup_scripts_file)/sway/sway-launch-command            > $(DESTDIR)$(BIN_DIR)/sway-launch-command
	$(setup_scripts_file)/sway/sway-launcher                  > $(DESTDIR)$(BIN_DIR)/sway-launcher
	$(setup_scripts_file)/sway/sway-launch-note               > $(DESTDIR)$(BIN_DIR)/sway-launch-note
	$(setup_scripts_file)/sway/sway-launch-password           > $(DESTDIR)$(BIN_DIR)/sway-launch-password
	$(setup_scripts_file)/sway/sway-launch-system             > $(DESTDIR)$(BIN_DIR)/sway-launch-system
	$(setup_scripts_file)/sway/sway-launch-tmux-env           > $(DESTDIR)$(BIN_DIR)/sway-launch-tmux-env
	$(setup_scripts_file)/sway/sway-move-window-new-workspace > $(DESTDIR)$(BIN_DIR)/sway-move-window-new-workspace
	$(setup_scripts_file)/sway/sway-rename-workspace          > $(DESTDIR)$(BIN_DIR)/sway-rename-workspace
	$(setup_scripts_file)/sway/sway-run-command               > $(DESTDIR)$(BIN_DIR)/sway-run-command

	chmod +x $(DESTDIR)$(BIN_DIR)/sway-app-chat
	chmod +x $(DESTDIR)$(BIN_DIR)/sway-app-mail
	chmod +x $(DESTDIR)$(BIN_DIR)/sway-app-monitor
	chmod +x $(DESTDIR)$(BIN_DIR)/sway-app-music
	chmod +x $(DESTDIR)$(BIN_DIR)/sway-app-news
	chmod +x $(DESTDIR)$(BIN_DIR)/sway-app-tmux-env
	chmod +x $(DESTDIR)$(BIN_DIR)/sway-command-input
	chmod +x $(DESTDIR)$(BIN_DIR)/sway-command-input-exec
	chmod +x $(DESTDIR)$(BIN_DIR)/sway-create-workspace
	chmod +x $(DESTDIR)$(BIN_DIR)/sway-focus-window-title
	chmod +x $(DESTDIR)$(BIN_DIR)/sway-fzf-launcher
	chmod +x $(DESTDIR)$(BIN_DIR)/sway-launch-app
	chmod +x $(DESTDIR)$(BIN_DIR)/sway-launch-command
	chmod +x $(DESTDIR)$(BIN_DIR)/sway-launcher
	chmod +x $(DESTDIR)$(BIN_DIR)/sway-launch-note
	chmod +x $(DESTDIR)$(BIN_DIR)/sway-launch-password
	chmod +x $(DESTDIR)$(BIN_DIR)/sway-launch-system
	chmod +x $(DESTDIR)$(BIN_DIR)/sway-launch-tmux-env
	chmod +x $(DESTDIR)$(BIN_DIR)/sway-move-window-new-workspace
	chmod +x $(DESTDIR)$(BIN_DIR)/sway-rename-workspace
	chmod +x $(DESTDIR)$(BIN_DIR)/sway-run-command
