all: sway-scripts

sway-scripts:
	setup/setup-script sway/sway-command-input
	setup/setup-script sway/sway-create-workspace
	setup/setup-script sway/sway-move-window-new-workspace
	setup/setup-script sway/sway-move-workspace-direction
	setup/setup-script sway/sway-move-workspace-index
	setup/setup-script sway/sway-quick-command
	setup/setup-script sway/sway-rename-workspace
	setup/setup-script sway/sway-renumber-workspaces
	setup/setup-script sway/sway-subscribe-events-run
	setup/setup-script sway/sway-toggle-window-idle-inhibitor
