#!/bin/sh

ENV_NAME="$1"
SESSION_NAME="$2"

TITLE="${ENV_NAME} environment"

# create env in background
# will do nothing if already exists
tmux-env -b "${ENV_NAME}" "${SESSION_NAME}"

# try to focus existing window if it exists
sway-focus-window-title "${TITLE}" && exit

# launch new app otherwise in new workspace
sway-create-workspace "${ENV_NAME}"
swaymsg -q exec \
  "termite \
   -t \"${TITLE}\" \
   -e 'tmux-env ${ENV_NAME} ${SESSION_NAME}'"
