#!/bin/sh

MARK='move'

swaymsg -q "mark --add ${MARK}"

sway-create-workspace

swaymsg [con_mark="${MARK}"] -q \
        move container to workspace current, \
        focus

swaymsg -q unmark "${MARK}"
