#!/bin/sh

# try to focus existing window if it exists
sway-focus-window-title 'sway_command_input' && exit

# quote arguments for usage in next command
ARGUMENTS=
while [ "$#" -gt 0 ]; do
  case "$1" in
    -*) ARGUMENTS="${ARGUMENTS} $1";;
    *) ARGUMENTS="${ARGUMENTS} '$1'";;
  esac
  shift
done

# launch new command input window otherwise
swaymsg -q exec \
  "alacritty \
   -t sway_command_input \
   --config-file ${XDG_CONFIG_HOME:-$HOME/.config}/alacritty/alacritty_command_input.yml \
   -e sway-command-input-exec ${ARGUMENTS}" \
