#!/bin/sh

TITLE='Mail client'

sway-focus-window-title "${TITLE}" && exit

sway-create-workspace 'mail'

swaymsg -q exec \
  "alacritty \
   -t \"${TITLE}\" \
   -e tmux new-session -A -s mail \"neomutt\""
