#!/bin/sh

init_variables() {
  COMMAND=${0##*/}

  PROMPT=':'
  FORMAT='%s'
  USER_INPUT=
}

parse_command_line() {
  while getopts F:P: OPT; do
    case "${OPT}" in
      F) FORMAT="${OPTARG}" ;;
      P) PROMPT="${OPTARG}" ;;
      ?) exit_error ;;
    esac
  done

  shift $(( OPTIND - 1 ))
}

# shellcheck disable=SC2120
exit_error() {
  [ -z "$1" ] || echo "${COMMAND}: $1"
  exit 1
} >&2

run() {
  USER_INPUT=$(
    echo '' | wmenu -l 0 -p "${PROMPT}"
  )

  # shellcheck disable=SC2181
  [ "$?" -eq 0 ] || return

  SWAY_COMMAND="$(
    echo "${FORMAT}" \
      | sed "s/%s/${USER_INPUT}/g"
  )"

  # shellcheck disable=SC2086
  swaymsg -q ${SWAY_COMMAND}
}

init_variables
parse_command_line "$@"

run
