#!/bin/sh

TITLE='sway_music'

# try to focus existing window if it exists
sway-focus-window-title "${TITLE}" && exit

# launch music server and app otherwise
if ! systemctl --user is-active mpd.service; then
  systemctl --user start mpd.service
fi

swaymsg -q exec \
  "alacritty \
   -t \"${TITLE}\" \
   -e tmux new-session -A -s music \"ncmpcpp\""
