#!/bin/sh

ENV_NAME="$1"
SESSION_NAME="$2"

TITLE="${ENV_NAME} environment"

# create env in background
# will do nothing if already exists
tmux-env -b "${ENV_NAME}" "${SESSION_NAME}"

sway-focus-window-title "${TITLE}" && exit

sway-create-workspace "${ENV_NAME}"

swaymsg -q exec \
  "alacritty \
   -t \"${TITLE}\" \
   -e tmux-env ${ENV_NAME} ${SESSION_NAME}"
