#!/bin/sh
# commands used:
# - sway-create-workspace
# - sway-focus-window-title
# - swaymsg
# - termite
# - tmux
# - weechat

TITLE='Chat client'

# try to focus existing window if it exists
sway-focus-window-title "${TITLE}" && exit

# launch new app otherwise in new workspace
sway-create-workspace 'chat'
swaymsg -q exec \
  "termite \
   -t \"${TITLE}\" \
   -e 'tmux new-session -A -s chat \"weechat\"'"
