#!/bin/sh

PASSWORD_STORE_DIR="${PASSWORD_STORE_DIR:-$HOME/.password-store}"

NAME=$(
  find -L "${PASSWORD_STORE_DIR}" \
    -type f -name '*.gpg' \
    | sed -e "s#${PASSWORD_STORE_DIR}/##" \
          -e 's/\.gpg//' \
    | sort \
    | sway-fzf-launcher 'copy password '
)

[ -n "${NAME}" ] || exit

# #FIXME: not sure why I need to use nohup there
# Without it, the password gets cleared immediately after exiting the launcher
# even if it works fine when running launch_password manually in a terminal...
nohup pass show --clip "${NAME}" > /dev/null 2>&1
