#!/bin/sh

is_workspace_num_used() {
  WORKSPACE_NUM="$1"

  swaymsg -t get_workspaces \
    | jq -e -r \
      ".[]|select(.num==${WORKSPACE_NUM})" \
    > /dev/null
}

NEW_WORKSPACE_NUM=1
while is_workspace_num_used "${NEW_WORKSPACE_NUM}"; do
  NEW_WORKSPACE_NUM=$(( NEW_WORKSPACE_NUM + 1 ))
done

swaymsg -q \
        move container to workspace "${NEW_WORKSPACE_NUM}", \
        workspace "${NEW_WORKSPACE_NUM}"
