#!/bin/sh

TITLE='sway_monitor'

# try to focus existing window if it exists
sway-focus-window-title "${TITLE}" && exit

# launch new app otherwise
swaymsg -q exec \
  "termite \
   -t \"${TITLE}\" \
   -e 'tmux new-session -A -s monitor \"htop\"'"
