#!/bin/sh

COMMAND="$1"

TITLE='sway_quick_command'

sway-focus-window-title "${TITLE}" && exit

if [ -n "${COMMAND}" ]; then
  swaymsg -q fullscreen disable, \
    exec "alacritty -t \"${TITLE}\" -e \"${COMMAND}\""
else
  swaymsg -q fullscreen disable, \
    exec "alacritty -t \"${TITLE}\""
fi
