#!/bin/sh

COMMAND="$*"

TITLE='sway_launcher'

sway-focus-window-title "${TITLE}" && exit

swaymsg -q exec \
  "alacritty \
   -t \"${TITLE}\" \
   --config-file ${XDG_CONFIG_HOME:-$HOME/.config}/alacritty/alacritty_launcher.yml \
   -e ${COMMAND}"
