#!/bin/sh

TITLE='sway_command_input'

sway-focus-window-title "${TITLE}" && exit

# quote arguments for usage in next command
ARGUMENTS=
while [ "$#" -gt 0 ]; do
  case "$1" in
    -*) ARGUMENTS="${ARGUMENTS} $1";;
    *) ARGUMENTS="${ARGUMENTS} '$1'";;
  esac
  shift
done

swaymsg -q exec \
  "alacritty \
   -t \"${TITLE}\" \
   --config-file ${XDG_CONFIG_HOME:-$HOME/.config}/alacritty/alacritty_command_input.yml \
   -e sway-command-input-exec ${ARGUMENTS}" \
