#!/bin/sh

{
  swaymsg -t subscribe -m '[ "workspace" ]' |
  while read -r EVENT; do
    CHANGE=$( echo "${EVENT}" | jq -r '.change' )
    if [ "${CHANGE}" != 'focus' ] \
      && [ "${CHANGE}" != 'urgent' ]; then
      sway-renumber-workspaces
    fi

    if [ "${CHANGE}" = 'focus' ] \
      || [ "${CHANGE}" = 'move' ]; then
      pkill -x -RTMIN+8 i3blocks
    fi
  done
}&

{
  swaymsg -t subscribe -m '[ "window" ]' |
  jq --unbuffered 'select(.change == "focus").container.id' |
  while read CURRENT_WINDOW; do
    pkill -x -RTMIN+8 i3blocks

    swaymsg "[con_id=${PREV_WINDOW}] mark --add _prev" > /dev/null
    PREV_WINDOW="${CURRENT_WINDOW}"
  done
}&
