#!/bin/sh

CURRENT_OUTPUT=$(
  swaymsg -t get_outputs \
    | jq -r '.[] | select(.focused == true) | .name'
)

NEW_WORKSPACE_NUM=$((
  $(
    swaymsg -t get_workspaces \
      | jq ".[] | select(.output == \"${CURRENT_OUTPUT}\") | .num" \
      | tail -n1
  ) + 1
))

if [ -n "$1" ]; then
  swaymsg -q workspace "${NEW_WORKSPACE_NUM}:$1"
else
  swaymsg -q workspace "${NEW_WORKSPACE_NUM}:"
fi
