#!/bin/sh

NAME=$(
  ykman oath list 2> /dev/null \
    | sort \
    | sway-fzf-launcher 'copy otp '
)

[ -n "${NAME}" ] || exit

ykman oath code -s "${NAME}" \
  | nohup \
      wl-copy -n \
      > /dev/null 2>&1
