#!/bin/sh

NEW_WORKSPACE_NUM=$((
  $(
    swaymsg -t get_workspaces \
      | jq '.[] | .num' \
      | tail -n1
  ) + 1
))

if [ -n "$1" ]; then
  swaymsg -q workspace "${NEW_WORKSPACE_NUM}:$1"
else
  swaymsg -q workspace "${NEW_WORKSPACE_NUM}:"
fi
