#!/bin/sh

NOTES_FOLDER="$( xdg-user-dir NOTES )"

NOTE=$(
  {
    echo NEW;
    ls "${NOTES_FOLDER}";
  } \
  | sway-fzf-launcher 'open note '
)

[ -n "${NOTE}" ] || exit

if [ "${NOTE}" = 'NEW' ]; then
  printf 'filename: '
  read -r NOTE
fi

swaymsg -q exec \
  "alacritty \
   -t ' Notes' \
   -e tmux new-session \"vim ${NOTES_FOLDER}/${NOTE}\""
