#!/bin/sh

ACTION=$(
  {
    echo 'Lock screen';
    echo 'Suspend';
    echo 'Logout';
    echo 'Shut down';
    echo 'Reboot';
  } \
  | fzf --reverse \
        --no-multi \
        --info hidden \
        --header "$( printf '\n' )" \
        "$@"
)

case "${ACTION}" in
  Lock\ screen) swaylock ;;
  Suspend)      systemctl suspend ;;
  Logout)       swaymsg -q exit ;;
  Shut\ down)   systemctl poweroff ;;
  Reboot)       systemctl reboot ;;
esac
