#!/bin/sh

COMMAND="$*"

# try to focus existing window if it exists
sway-focus-window-title 'sway_launcher' && exit

# launch new launcher otherwise
swaymsg -q exec \
  "alacritty \
   -t sway_launcher \
   --config-file ${XDG_CONFIG_HOME:-$HOME/.config}/alacritty/alacritty_launcher.yml \
   -e ${COMMAND}" \
