#!/bin/sh

# Fetch channels before the start of the fzf interface to have its informative
# messages displayed properly beforehand
CHANNELS=$( somafm channels )

CHANNEL_ID=$(
    echo "${CHANNELS}" \
    | sort -k 2 \
    | fzf --reverse \
          --no-multi \
          --info hidden \
          --header "$( printf '\n' )" \
          -d '\t' \
          --with-nth 2 \
          "$@" \
    | cut -f 1
)

[ -n "${CHANNEL_ID}" ] || exit

CHANNEL_URL=$( somafm direct_url "${CHANNEL_ID}" )

mpc -q clear
mpc -q add "${CHANNEL_URL}"
mpc -q play
