#!/bin/sh

TITLE="$1"

WINDOW_ID=$(
  swaymsg -t get_tree \
    | jq "recurse(.floating_nodes[]?,.nodes[]?)
          | select(.name == \"${TITLE}\" and (.type == \"con\" or .type == \"floating_con\") )
          | .id"
)

[ -z "${WINDOW_ID}" ] && exit 1

swaymsg -q "[con_id=\"${WINDOW_ID}\"]" focus
