#!/bin/sh

COMMAND="$*"

TITLE='sway_quick_command'

swaymsg -q "[title=\"${TITLE}\"]" focus && exit

swaymsg -q fullscreen disable

if [ -n "${COMMAND}" ]; then
  #shellcheck disable=SC2086
  foot -T "${TITLE}" -o locked-title=yes ${COMMAND}
else
  foot -T "${TITLE}" -o locked-title=yes
fi

