#!/bin/sh

ENV_NAME="$1"
shift

SESSION=$(
  {
    echo NEW;
    find "${XDG_DATA_HOME:-$HOME/.local/share}/env/tmux/${ENV_NAME}" \
      -type f -name '*.sh' -exec basename {} .sh \; \
      | sort
  } \
  | fzf --reverse \
        --no-multi \
        --info hidden \
        --header "$( printf '\n' )" \
        "$@"
)

[ -n "${SESSION}" ] || exit

[ "${SESSION}" = 'NEW' ] && SESSION=

sway-app-tmux-env "${ENV_NAME}" "${SESSION}"
