#!/bin/sh

TITLE='Chat client'

sway-focus-window-title "${TITLE}" && exit

sway-create-workspace 'chat'

swaymsg -q exec \
  "alacritty \
   -t \"${TITLE}\" \
   -e tmux new-session -A -s chat \"WEECHAT_PASSPHRASE=$(pass perso/weechat) weechat\""
