#!/bin/sh

TITLE='Mail client'

# try to focus existing window if it exists
sway-focus-window-title "${TITLE}" && exit

# launch new app otherwise in new workspace
sway-create-workspace 'mail'
swaymsg -q exec \
  "termite \
   -t \"${TITLE}\" \
   -e 'tmux new-session -A -s mail \"neomutt\"'"
