#!/bin/sh

CACHE_LIST_PATH="${XDG_CACHE_HOME:-$HOME/.cache}/sway/launch_command"

should_build_cache() {
  [ -f "${CACHE_LIST_PATH}" ] || return 0

  CACHE_LAST_MODIFIED=$(
    stat -c '%Y' "${CACHE_LIST_PATH}"
  )

  FOLDERS_LAST_MODIFIED=$(
    printf '%s' "${PATH}" \
      | tr ':' '\n' \
      | xargs -I {} \
        -- stat -c '%Y' {} \
        2> /dev/null \
      | sort \
      | tail -n 1
  )

  [ "${CACHE_LAST_MODIFIED}" -lt "${FOLDERS_LAST_MODIFIED}" ]
}

build_cache() {
  mkdir -p "$( dirname "${CACHE_LIST_PATH}" )"

  echo "Building list of commands..." >&2

  printf '%s' "${PATH}" \
    | tr ':' '\n' \
    | xargs -I [] \
      -- find -L [] \
         -type f \
         -exec basename {} \; \
         2> /dev/null \
    | sort -u \
    > "${CACHE_LIST_PATH}"
}

should_build_cache && build_cache

sway-fzf-launcher 'run ' < "${CACHE_LIST_PATH}" \
  | xargs -I{} \
    -- swaymsg -q exec {}
