#!/bin/sh

# small wrapper to focus a window by title

TITLE="$1"

# find window id in tree
WINDOW_ID=$(
  swaymsg -t get_tree \
    | jq "recurse(.floating_nodes[]?,.nodes[]?)
          | select(.name == \"${TITLE}\" and (.type == \"con\" or .type == \"floating_con\") )
          | .id"
)

# error out if window with such title doesn't exist
[ -z "${WINDOW_ID}" ] && exit 1

swaymsg -q "[con_id=\"${WINDOW_ID}\"]" focus
