#!/bin/sh

NAME=$(
  ykman oath list 2> /dev/null \
    | sort \
    | fzf --reverse \
          --no-multi \
          --info hidden \
          --header "$( printf '\n' )" \
          "$@"
)

[ -n "${NAME}" ] || exit

ykman oath code -s "${NAME}" \
  | nohup \
      wl-copy -n \
      > /dev/null 2>&1
