#!/bin/sh

CHANNEL_ID=$(
  somafm channels \
    | sort -k 2 \
    | sway-fzf-launcher 'play SomaFM channel ' \
        -d '\t' \
        --with-nth 2 \
    | cut -f 1
)

[ -n "${CHANNEL_ID}" ] || exit

echo "Fetching channel..."

CHANNEL_URL=$( somafm direct_url "${CHANNEL_ID}" )

mpc -q clear
mpc -q add "${CHANNEL_URL}"
mpc -q play
