#!/bin/sh

COMMAND="$*"

TITLE='sway_quick_command'

swaymsg -q "[title=\"${TITLE}\"]" focus && exit

if [ -n "${COMMAND}" ]; then
  swaymsg -q fullscreen disable, \
    exec "alacritty -t \"${TITLE}\" -e ${COMMAND}"
else
  swaymsg -q fullscreen disable, \
    exec "alacritty -t \"${TITLE}\""
fi
