#!/bin/sh
# commands used:
# - ykman

# Autofill OTP for known websites.
# Rely on focus being on OTP field

DOMAINS_OTP_ID_FILE="${PASSWORD_STORE_DIR:-$HOME/.password-store}/domains_otp_id"

exit_error() {
  echo "message-error 'autofill-otp: $1'" >> "${QUTE_FIFO}"
  exit 0
}

exit_warning() {
  echo "message-warning 'autofill-otp: $1'" >> "${QUTE_FIFO}"
  exit 0
}

if [ ! -f "${DOMAINS_OTP_ID_FILE}" ]; then
  exit_error 'Missing domains otp id file'
fi

DOMAIN="$( echo "${QUTE_URL}" | awk -F/ '{print $3}' )"
OTP_ID="$(grep "^${DOMAIN}	" "${DOMAINS_OTP_ID_FILE}" | cut -f2 )"

if [ -z "${OTP_ID}" ]; then
  exit_warning "No existing OTP for ${DOMAIN}"
fi

OTP_CODE="$( ykman oath accounts code -s "${OTP_ID}" )"

if [ -z "${OTP_CODE}" ]; then
  exit_error "Invalid OTP identifier ${OTP_ID} for ${DOMAIN}"
fi

{
  echo 'mode-enter insert'
  echo "fake-key ${OTP_CODE}"
} >> "${QUTE_FIFO}"
