# add custom scripts paths
# and make sure they are no duplicates
typeset -aU path
path=(
  "${HOME}/.zsh/scripts"
  "${HOME}/.config/git/scripts"
  "${HOME}/.config/sway/scripts"
  $path
)

# set PATH in systemd user environment
systemctl --user import-environment PATH 2> /dev/null
