# add custom scripts paths
# and make sure they are no duplicates
typeset -aU path
path=(
  {folder/bin}
  $path
)

# set PATH in systemd user environment
systemctl --user import-environment PATH 2> /dev/null
