zathura:
	@echo -n "… setup zathura"

    # create necessary directories
	@mkdir -p "$(CONFIG_DIR)/zathura"

    # copy config files
	@cp "zathura/zathurarc" "$(CONFIG_DIR)/zathura/zathurarc"

	@echo -e "\r✔ setup zathura"
