termite:
	@echo -n "… setup termite"

    # create necessary directories
	@mkdir -p "$(CONFIG_DIR)/termite"

    # copy config files
	@cp "termite/config" "$(CONFIG_DIR)/termite/config"

	@echo -e "\r✔ setup termite"
