termite:
	@echo -n "… setup termite"

    # create necessary directories
	@mkdir -p "$(CONFIG_DIR)/termite"

    # copy config files
	@cp "termite/config" "$(CONFIG_DIR)/termite/config"
	@cp "termite/config_menu" "$(CONFIG_DIR)/termite/config_menu"
	@cp "termite/config_notification" "$(CONFIG_DIR)/termite/config_notification"

	@echo -e "\r✔ setup termite"
