#!/bin/sh

FILE="$1"

BASE_COLORS_DEFINITION_FILE="${0%/*}/definitions/base"
ALIASES_COLORS_DEFINITION_FILE="${0%/*}/definitions/aliases"

# extract color hexadecimal values from definition file
BASE00_HEX=$( grep base00 "${BASE_COLORS_DEFINITION_FILE}" | tr -s ' ' | cut -f2 -d' ' )
BASE01_HEX=$( grep base01 "${BASE_COLORS_DEFINITION_FILE}" | tr -s ' ' | cut -f2 -d' ' )
BASE02_HEX=$( grep base02 "${BASE_COLORS_DEFINITION_FILE}" | tr -s ' ' | cut -f2 -d' ' )
BASE03_HEX=$( grep base03 "${BASE_COLORS_DEFINITION_FILE}" | tr -s ' ' | cut -f2 -d' ' )
BASE04_HEX=$( grep base04 "${BASE_COLORS_DEFINITION_FILE}" | tr -s ' ' | cut -f2 -d' ' )
BASE05_HEX=$( grep base05 "${BASE_COLORS_DEFINITION_FILE}" | tr -s ' ' | cut -f2 -d' ' )
BASE06_HEX=$( grep base06 "${BASE_COLORS_DEFINITION_FILE}" | tr -s ' ' | cut -f2 -d' ' )
BASE07_HEX=$( grep base07 "${BASE_COLORS_DEFINITION_FILE}" | tr -s ' ' | cut -f2 -d' ' )
BASE08_HEX=$( grep base08 "${BASE_COLORS_DEFINITION_FILE}" | tr -s ' ' | cut -f2 -d' ' )
BASE09_HEX=$( grep base09 "${BASE_COLORS_DEFINITION_FILE}" | tr -s ' ' | cut -f2 -d' ' )
BASE0A_HEX=$( grep base0A "${BASE_COLORS_DEFINITION_FILE}" | tr -s ' ' | cut -f2 -d' ' )
BASE0B_HEX=$( grep base0B "${BASE_COLORS_DEFINITION_FILE}" | tr -s ' ' | cut -f2 -d' ' )
BASE0C_HEX=$( grep base0C "${BASE_COLORS_DEFINITION_FILE}" | tr -s ' ' | cut -f2 -d' ' )
BASE0D_HEX=$( grep base0D "${BASE_COLORS_DEFINITION_FILE}" | tr -s ' ' | cut -f2 -d' ' )
BASE0E_HEX=$( grep base0E "${BASE_COLORS_DEFINITION_FILE}" | tr -s ' ' | cut -f2 -d' ' )
BASE0F_HEX=$( grep base0F "${BASE_COLORS_DEFINITION_FILE}" | tr -s ' ' | cut -f2 -d' ' )

# extract color number values from definition file
BASE00_NUMBER=$( grep base00 "${BASE_COLORS_DEFINITION_FILE}" | tr -s ' ' | cut -f3 -d' ' )
BASE01_NUMBER=$( grep base01 "${BASE_COLORS_DEFINITION_FILE}" | tr -s ' ' | cut -f3 -d' ' )
BASE02_NUMBER=$( grep base02 "${BASE_COLORS_DEFINITION_FILE}" | tr -s ' ' | cut -f3 -d' ' )
BASE03_NUMBER=$( grep base03 "${BASE_COLORS_DEFINITION_FILE}" | tr -s ' ' | cut -f3 -d' ' )
BASE04_NUMBER=$( grep base04 "${BASE_COLORS_DEFINITION_FILE}" | tr -s ' ' | cut -f3 -d' ' )
BASE05_NUMBER=$( grep base05 "${BASE_COLORS_DEFINITION_FILE}" | tr -s ' ' | cut -f3 -d' ' )
BASE06_NUMBER=$( grep base06 "${BASE_COLORS_DEFINITION_FILE}" | tr -s ' ' | cut -f3 -d' ' )
BASE07_NUMBER=$( grep base07 "${BASE_COLORS_DEFINITION_FILE}" | tr -s ' ' | cut -f3 -d' ' )
BASE08_NUMBER=$( grep base08 "${BASE_COLORS_DEFINITION_FILE}" | tr -s ' ' | cut -f3 -d' ' )
BASE09_NUMBER=$( grep base09 "${BASE_COLORS_DEFINITION_FILE}" | tr -s ' ' | cut -f3 -d' ' )
BASE0A_NUMBER=$( grep base0A "${BASE_COLORS_DEFINITION_FILE}" | tr -s ' ' | cut -f3 -d' ' )
BASE0B_NUMBER=$( grep base0B "${BASE_COLORS_DEFINITION_FILE}" | tr -s ' ' | cut -f3 -d' ' )
BASE0C_NUMBER=$( grep base0C "${BASE_COLORS_DEFINITION_FILE}" | tr -s ' ' | cut -f3 -d' ' )
BASE0D_NUMBER=$( grep base0D "${BASE_COLORS_DEFINITION_FILE}" | tr -s ' ' | cut -f3 -d' ' )
BASE0E_NUMBER=$( grep base0E "${BASE_COLORS_DEFINITION_FILE}" | tr -s ' ' | cut -f3 -d' ' )
BASE0F_NUMBER=$( grep base0F "${BASE_COLORS_DEFINITION_FILE}" | tr -s ' ' | cut -f3 -d' ' )

{
  # aliases intermediate conversion to base color equivalent
  while read -r line; do
    alias=$( echo "${line}" | cut -f1 -d' ' )
    base_color=$( echo "${line}" | cut -f2 -d' ' )
    echo "s|{color/${alias}/\([[:alpha:]]\+\)}|{color/${base_color}/\1}|g"
  done < "${ALIASES_COLORS_DEFINITION_FILE}"
} | sed -i -f - "${FILE}"

{
  # hexadecimal final conversion
  echo "s|{color/base00/hex}|${BASE00_HEX}|g"
  echo "s|{color/base01/hex}|${BASE01_HEX}|g"
  echo "s|{color/base02/hex}|${BASE02_HEX}|g"
  echo "s|{color/base03/hex}|${BASE03_HEX}|g"
  echo "s|{color/base04/hex}|${BASE04_HEX}|g"
  echo "s|{color/base05/hex}|${BASE05_HEX}|g"
  echo "s|{color/base06/hex}|${BASE06_HEX}|g"
  echo "s|{color/base07/hex}|${BASE07_HEX}|g"
  echo "s|{color/base08/hex}|${BASE08_HEX}|g"
  echo "s|{color/base09/hex}|${BASE09_HEX}|g"
  echo "s|{color/base0A/hex}|${BASE0A_HEX}|g"
  echo "s|{color/base0B/hex}|${BASE0B_HEX}|g"
  echo "s|{color/base0C/hex}|${BASE0C_HEX}|g"
  echo "s|{color/base0D/hex}|${BASE0D_HEX}|g"
  echo "s|{color/base0E/hex}|${BASE0E_HEX}|g"
  echo "s|{color/base0F/hex}|${BASE0F_HEX}|g"
} | sed -i -f - "${FILE}"

{
  # fixed intermediate conversion
  # for color name via 16 color number
  echo 's|{color/base0\([[:alnum:]]\)/name}|{color/number_{color/base0\1/number}/name}|g'

  # fixed intermediate conversion
  # for foreground color code via 16 color number
  echo 's|{color/base0\([[:alnum:]]\)/fg}|{color/number_{color/base0\1/number}/fg}|g'

  # fixed intermediate conversion
  # for background color code via 16 color number
  echo 's|{color/base0\([[:alnum:]]\)/bg}|{color/number_{color/base0\1/number}/bg}|g'
} | sed -i -f - "${FILE}"

{
  # number final conversion
  echo "s|{color/base00/number}|${BASE00_NUMBER}|g"
  echo "s|{color/base01/number}|${BASE01_NUMBER}|g"
  echo "s|{color/base02/number}|${BASE02_NUMBER}|g"
  echo "s|{color/base03/number}|${BASE03_NUMBER}|g"
  echo "s|{color/base04/number}|${BASE04_NUMBER}|g"
  echo "s|{color/base05/number}|${BASE05_NUMBER}|g"
  echo "s|{color/base06/number}|${BASE06_NUMBER}|g"
  echo "s|{color/base07/number}|${BASE07_NUMBER}|g"
  echo "s|{color/base08/number}|${BASE08_NUMBER}|g"
  echo "s|{color/base09/number}|${BASE09_NUMBER}|g"
  echo "s|{color/base0A/number}|${BASE0A_NUMBER}|g"
  echo "s|{color/base0B/number}|${BASE0B_NUMBER}|g"
  echo "s|{color/base0C/number}|${BASE0C_NUMBER}|g"
  echo "s|{color/base0D/number}|${BASE0D_NUMBER}|g"
  echo "s|{color/base0E/number}|${BASE0E_NUMBER}|g"
  echo "s|{color/base0F/number}|${BASE0F_NUMBER}|g"
} | sed -i -f - "${FILE}"

{
  # fixed ANSI final conversion
  # from 16 color number to color name
  echo 's|{color/number_0/name}|black|g'
  echo 's|{color/number_1/name}|red|g'
  echo 's|{color/number_2/name}|green|g'
  echo 's|{color/number_3/name}|yellow|g'
  echo 's|{color/number_4/name}|blue|g'
  echo 's|{color/number_5/name}|magenta|g'
  echo 's|{color/number_6/name}|cyan|g'
  echo 's|{color/number_7/name}|white|g'
  echo 's|{color/number_8/name}|brblack|g'
  echo 's|{color/number_9/name}|brred|g'
  echo 's|{color/number_10/name}|brgreen|g'
  echo 's|{color/number_11/name}|bryellow|g'
  echo 's|{color/number_12/name}|brblue|g'
  echo 's|{color/number_13/name}|brmagenta|g'
  echo 's|{color/number_14/name}|brcyan|g'
  echo 's|{color/number_15/name}|brwhite|g'
} | sed -i -f - "${FILE}"

{
  # fixed ANSI final conversion
  # from 16 color number to foreground color code
  echo 's|{color/number_0/fg}|30|g'
  echo 's|{color/number_1/fg}|31|g'
  echo 's|{color/number_2/fg}|32|g'
  echo 's|{color/number_3/fg}|33|g'
  echo 's|{color/number_4/fg}|34|g'
  echo 's|{color/number_5/fg}|35|g'
  echo 's|{color/number_6/fg}|36|g'
  echo 's|{color/number_7/fg}|37|g'
  echo 's|{color/number_8/fg}|90|g'
  echo 's|{color/number_9/fg}|91|g'
  echo 's|{color/number_10/fg}|92|g'
  echo 's|{color/number_11/fg}|93|g'
  echo 's|{color/number_12/fg}|94|g'
  echo 's|{color/number_13/fg}|95|g'
  echo 's|{color/number_14/fg}|96|g'
  echo 's|{color/number_15/fg}|97|g'
} | sed -i -f - "${FILE}"

{
  # fixed ANSI final conversion
  # from 16 color number to background color code
  echo 's|{color/number_0/bg}|40|g'
  echo 's|{color/number_1/bg}|41|g'
  echo 's|{color/number_2/bg}|42|g'
  echo 's|{color/number_3/bg}|43|g'
  echo 's|{color/number_4/bg}|44|g'
  echo 's|{color/number_5/bg}|45|g'
  echo 's|{color/number_6/bg}|46|g'
  echo 's|{color/number_7/bg}|47|g'
  echo 's|{color/number_8/bg}|100|g'
  echo 's|{color/number_9/bg}|101|g'
  echo 's|{color/number_10/bg}|102|g'
  echo 's|{color/number_11/bg}|103|g'
  echo 's|{color/number_12/bg}|104|g'
  echo 's|{color/number_13/bg}|105|g'
  echo 's|{color/number_14/bg}|106|g'
  echo 's|{color/number_15/bg}|107|g'
} | sed -i -f - "${FILE}"
