#!/bin/bash

function init_todo()
{
  [[ -f TODO ]] && return

  cat > TODO << EOF
Periodic:

Cleaning:

Bugs:

Testing:

Improvements:

New Features:

Discarded:

Research:

Resources:

EOF
}

init_todo

exit 0
