#!/bin/sh
# commands used:
# - amixer
# - i3blocks-mode

MODE="$( i3blocks-mode )"

VOLUME_INFO=$(
  amixer get Master \
    | sed -n '/\[[0-9]\{1,3\}%\] \[.*\]/p' \
    | head -n 1
)

echo "${VOLUME_INFO}" | grep -q '\[on\]'
IS_VOLUME_MUTED=$?

VOLUME_PERCENT=$(
  echo "${VOLUME_INFO}" \
    | sed 's/.*\[\([0-9]\{1,3\}\)%\].*/\1/'
)

if [ "${VOLUME_PERCENT}" -lt 50 ]; then
  VOLUME_ICON=''
else
  VOLUME_ICON=''
fi

if [ "${IS_VOLUME_MUTED}" -eq 1 ]; then
  if [ "${MODE}" = 'full' ]; then
    echo "<span foreground='#{color/notice/hex}'> Muted</span>"
  else
    echo "<span foreground='#{color/notice/hex}'></span>"
  fi
else
  if [ "${MODE}" = 'full' ]; then
    echo "<span foreground='#{color/base09/hex}'>${VOLUME_ICON}</span> ${VOLUME_PERCENT}%"
  else
    echo "<span foreground='#{color/base09/hex}'>${VOLUME_ICON}</span>"
  fi
fi
