#!/bin/sh
# commands used:
# - bluetoothctl
# - i3blocks-mode

MODE="$( i3blocks-mode )"

CONNECTED_DEVICES=$(
  bluetoothctl devices Paired \
    | cut -d' ' -f2 \
    | xargs -I{} bluetoothctl info {} \
    | sed -n -e 's/.*Alias: \(.*\)/\1/p' -e 's/.*Connected: \(.*\)/\1/p' \
    | paste - - \
    | sed -n 's/\(.*\)\tyes$/\1/p' \
    | paste -sd,
)

if [ -z "${CONNECTED_DEVICES}" ]; then
  exit 0
fi

if [ "${MODE}" = 'full' ]; then
  TEXT="  ${CONNECTED_DEVICES}"
else
  TEXT=''
fi

printf '%s\n\n%s\n' "${TEXT}" "${COLOR}"
