#!/bin/sh
# commands used:
# - pomodoro

SESSION_STATUS=$( pomodoro status 2> /dev/null )

if [ -n "${SESSION_STATUS}" ]; then
  TEXT="( ${SESSION_STATUS} )"
else
  TEXT='(no timer)'
  COLOR='#{color/warning/hex}'
fi

printf '%s\n\n%s\n' "${TEXT}" "${COLOR}"
