#!/bin/sh
# commands used:
# - i3blocks-mode
# - wpctl

MODE="$( i3blocks-mode )"

VOLUME="$( wpctl get-volume @DEFAULT_AUDIO_SOURCE@ )"

if echo "${VOLUME}" | grep -q 'MUTED'; then
  exit 0
fi

COLOR='#{color/notice/hex}'

VOLUME_PERCENT=$(
  echo "${VOLUME}" \
    | sed 's/Volume: \([0-9\.]*\).*/\1/' \
    | sed -e 's/^0//' -e 's/\.//'
)

if [ "${MODE}" = 'full' ]; then
  TEXT="  ${VOLUME_PERCENT}%"
else
  TEXT=''
fi

printf '%s\n\n%s\n' "${TEXT}" "${COLOR}"
