#!/bin/sh

MODE="$( i3blocks-mode )"

VOLUME_INFO=$(
  amixer get Capture \
    | sed -n '/\[[0-9]\{1,3\}%\] \[.*\]/p' \
    | head -n 1
)

if echo "${VOLUME_INFO}" | grep -q '\[off\]'; then
  exit 0
fi

VOLUME_PERCENT=$(
  echo "${VOLUME_INFO}" \
    | sed 's/.*\[\([0-9]\{1,3\}\)%\].*/\1/'
)

if [ "${MODE}" = 'full' ]; then
  echo "<span foreground='#{color/notice/hex}'></span> ${VOLUME_PERCENT}%"
else
  echo "<span foreground='#{color/notice/hex}'></span>"
fi
