#!/bin/sh
# commands used:
# - i3blocks-mode
# - nmcli

MODE="$( i3blocks-mode )"

NETWORK_INFO=$(
  nmcli -f type,state,connection device status \
    | tr -s ' '
)

if echo "${NETWORK_INFO}" \
     | grep -q 'ethernet connected'; then
  IS_ETHERNET_CONNECTED=true
else
  IS_ETHERNET_CONNECTED=false
fi

if echo "${NETWORK_INFO}" \
     | grep -q 'wifi connected'; then
  IS_WIFI_CONNECTED=true
else
  IS_WIFI_CONNECTED=false
fi

WIFI_CONNECTION=$(
  echo "${NETWORK_INFO}" \
    | grep 'wifi connected' \
    | cut -d ' ' -f 3-
)

# NetworkManager automatically favors wired connections over wireless
if [ "${IS_ETHERNET_CONNECTED}" = 'true' ]; then
  if [ "${MODE}" = 'full' ]; then
    echo "<span foreground='#{color/base09/hex}'></span> Wired"
  else
    echo "<span foreground='#{color/base09/hex}'></span>"
  fi
elif [ "${IS_WIFI_CONNECTED}" = 'true' ]; then
  if [ "${MODE}" = 'full' ]; then
    echo "<span foreground='#{color/base09/hex}'></span> ${WIFI_CONNECTION}"
  else
    echo "<span foreground='#{color/base09/hex}'></span>"
  fi
else
  if [ "${MODE}" = 'full' ]; then
    echo "<span foreground='#{color/warning/hex}'> Disconnected</span>"
  else
    echo "<span foreground='#{color/warning/hex}'></span>"
  fi
fi
