#!/bin/sh
# commands used:
# - i3blocks-mode
# - mpc

MODE="$( i3blocks-mode )"

MUSIC_INFO=$(
  mpc status -f '[[%artist% / ]%title%]|[%file%]' 2> /dev/null
)

# only display something if the MPD is on
# and the songs queue is not empty
if [ -z "${MUSIC_INFO}" ] \
   || [ "$( mpc playlist | wc -l )" -eq 0 ]; then
  exit 0
fi

if echo "${MUSIC_INFO}" | grep -q '^\[playing\]'; then
  MUSIC_ICON=''
  MUSIC_TEXT=$(
    echo "${MUSIC_INFO}" \
      | head -n 1 \
      | cut -c -50
  )
elif echo "${MUSIC_INFO}" | grep -q '^\[paused\]'; then
  MUSIC_ICON=''
  MUSIC_TEXT='Paused'
else
  MUSIC_ICON=''
  MUSIC_TEXT='Stopped'
fi

if [ "${MODE}" = 'full' ]; then
  TEXT="${MUSIC_ICON}  ${MUSIC_TEXT}"
else
  TEXT="${MUSIC_ICON}"
fi

printf '%s\n\n%s\n' "${TEXT}" "${COLOR}"
