#!/bin/sh
# commands used:
# - i3blocks-mode
# - pactl

MODE="$( i3blocks-mode )"

if pactl get-source-mute @DEFAULT_SOURCE@ | grep -q ' yes$'; then
  exit 0
fi

COLOR='#{color/notice/hex}'

VOLUME_PERCENT=$(
  pactl get-source-volume @DEFAULT_SOURCE@ \
    | sed -n 's/.* \([0-9]\{1,3\}\)% .*/\1/p'
)

if [ "${MODE}" = 'full' ]; then
  TEXT="  ${VOLUME_PERCENT}%"
else
  TEXT=''
fi

printf '%s\n\n%s\n' "${TEXT}" "${COLOR}"
