#!/bin/sh

SESSION_STATUS=$( pomodoro status 2> /dev/null )

[ -n "${SESSION_STATUS}" ] || exit 0

SESSION_MINUTES_LEFT=$(
  echo "${SESSION_STATUS}" \
    | cut -f 1 -d ' '
)

if [ "${SESSION_MINUTES_LEFT}" -lt 5 ]; then
  SESSION_ICON=''
elif [ "${SESSION_MINUTES_LEFT}" -lt 20 ]; then
  SESSION_ICON=''
else
  SESSION_ICON=''
fi

echo "<span foreground='#{color/notice/hex}'>${SESSION_ICON} ${SESSION_STATUS}</span>"
