#!/bin/sh
# commands used:
# - do-not-disturb
# - i3blocks-mode

MODE="$( i3blocks-mode )"

COUNTS=$(
  cd "${HOME}/Mail" || return
  find ./* -type d -prune \
    | xargs -I{} sh -c "printf '{}:'; find {} -path '*/new/*' -type f | wc -l" \
    | paste -sd' ' \
    | sed 's#\./##g'
)

if echo "${COUNTS}" | grep -q ':[1-9]'; then
  # do not set notice color if we are busy not to get tempted to check mail
  if [ "$( do-not-disturb status )" = 'disabled' ]; then
    COLOR='#{color/notice/hex}'
  fi
fi

if [ "${MODE}" = 'full' ]; then
  TEXT="  ${COUNTS}"
else
  TEXT=''
fi

printf '%s\n\n%s\n' "${TEXT}" "${COLOR}"
