#!/bin/sh
# commands used:
# - i3blocks-mode
# - pass (wrapper)
# - ykman (wrapper)

MODE="$( i3blocks-mode )"

OATH_TOUCH_STATUS="$( ykman oath touch )"
PGP_TOUCH_STATUS="$( pass touch )"

# it's currently not possible for both OATH and PGP to be waiting for touch
if [ "${OATH_TOUCH_STATUS}" = 'not waiting' ]; then
  if [ "${PGP_TOUCH_STATUS}" = 'not waiting' ]; then
    exit 0
  else
    TOUCH_STATUS="PGP: $( echo "${PGP_TOUCH_STATUS}" | paste -sd, )"
  fi
else
  TOUCH_STATUS="OATH: ${OATH_TOUCH_STATUS}"
fi

if [ "${MODE}" = 'full' ]; then
  TEXT=" ${TOUCH_STATUS}"
else
  TEXT=''
fi

COLOR_FG='#{color/base00/hex}'
COLOR_BG='#{color/alert/hex}'

printf '%s\n\n%s\n%s\n' " ${TEXT} " "${COLOR_FG}" "${COLOR_BG}"
