#!/bin/sh
# commands used:
# - i3blocks-mode
# - task

MODE="$( i3blocks-mode )"

TASK=$( task show 2> /dev/null )

if [ -n "${TASK}" ]; then
  TASK_ID="$( echo "${TASK}" | cut -f1 )"
  TASK_NAME="$( echo "${TASK}" | cut -f2 )"

  if [ "${MODE}" = 'full' ] && [ -n "${TASK_NAME}" ]; then
    TEXT="${TASK_NAME}"
  else
    TEXT="${TASK_ID}"
  fi

  COLOR_FG='#{color/base00/hex}'
  COLOR_BG='#{color/info/hex}'
else
  TEXT='no task'
  COLOR_FG='#{color/base00/hex}'
  COLOR_BG='#{color/warning/hex}'
fi

printf '%s\n\n%s\n%s\n' "  ${TEXT}  " "${COLOR_FG}" "${COLOR_BG}"
