#!/bin/sh
# commands used:
# - i3blocks-mode
# - wpctl

MODE="$( i3blocks-mode )"

VOLUME="$( wpctl get-volume @DEFAULT_AUDIO_SINK@ )"

VOLUME_PERCENT=$(
  echo "${VOLUME}" \
    | sed 's/Volume: \([0-9\.]*\).*/\1/' \
    | sed -e 's/^0//' -e 's/\.//'
)

if [ "${VOLUME_PERCENT}" -lt 50 ]; then
  VOLUME_ICON=''
else
  VOLUME_ICON=''
fi

if echo "${VOLUME}" | grep -q 'MUTED'; then
  COLOR='#{color/notice/hex}'

  if [ "${MODE}" = 'full' ]; then
    TEXT='  Muted'
  else
    TEXT=''
  fi
else
  if [ "${MODE}" = 'full' ]; then
    TEXT="${VOLUME_ICON}  ${VOLUME_PERCENT}%"
  else
    TEXT="${VOLUME_ICON}"
  fi
fi

printf '%s\n\n%s\n' "${TEXT}" "${COLOR}"
