#!/bin/sh
# commands used:
# - do-not-disturb

if [ "$( do-not-disturb status )" = 'enabled' ]; then
  echo "<span foreground='#{color/notice/hex}'></span>"
else
  echo "<span foreground='#{color/base0C/hex}'></span>"
fi
