#!/bin/sh
# commands used:
# - pomodoro

SESSION_STATUS=$( pomodoro status 2> /dev/null )

[ -n "${SESSION_STATUS}" ] || exit 0

TEXT="( ${SESSION_STATUS} )"

printf '%s\n\n%s\n' "${TEXT}" "${COLOR}"
