#!/bin/sh
# commands used:
# - i3blocks-mode
# - pactl

MODE="$( i3blocks-mode )"

VOLUME_PERCENT=$(
  pactl get-sink-volume @DEFAULT_SINK@ \
    | sed -n 's/.* \([0-9]\{1,3\}\)% .*/\1/p'
)

if [ "${VOLUME_PERCENT}" -lt 50 ]; then
  VOLUME_ICON=''
else
  VOLUME_ICON=''
fi

if pactl get-sink-mute @DEFAULT_SINK@ | grep -q ' yes$'; then
  COLOR='#{color/notice/hex}'

  if [ "${MODE}" = 'full' ]; then
    TEXT='  Muted'
  else
    TEXT=''
  fi
else
  if [ "${MODE}" = 'full' ]; then
    TEXT="${VOLUME_ICON}  ${VOLUME_PERCENT}%"
  else
    TEXT="${VOLUME_ICON}"
  fi
fi

printf '%s\n\n%s\n' "${TEXT}" "${COLOR}"
