#!/bin/sh
# commands used:
# - i3blocks-mode
# - pidof

COUNT_FILE_PATH="${XDG_RUNTIME_DIR:-/tmp}/chat_count"

MODE="$( i3blocks-mode )"

# don't show anything if weechat is not running
pidof weechat > /dev/null || exit 0

if [ ! -f "${COUNT_FILE_PATH}" ]; then
  # show 0 notification if there is no file
  # just to let us know at least that weechat is running
  COUNT=0
else
  COUNT=$( cat "${COUNT_FILE_PATH}" )
fi

if [ "${COUNT}" -gt 0 ]; then
  COLOR='#{color/notice/hex}'
fi

if [ "${MODE}" = 'full' ]; then
  TEXT="  ${COUNT}"
else
  TEXT=''
fi

printf '%s\n\n%s\n' "${TEXT}" "${COLOR}"
