all: i3blocks-scripts

i3blocks-scripts:
	mkdir -p $(DESTDIR)$(BIN_DIR)

	$(setup_file)/scripts/i3blocks/i3blocks-bluetooth      > $(DESTDIR)$(BIN_DIR)/i3blocks-bluetooth
	$(setup_file)/scripts/i3blocks/i3blocks-chat           > $(DESTDIR)$(BIN_DIR)/i3blocks-chat
	$(setup_file)/scripts/i3blocks/i3blocks-do-not-disturb > $(DESTDIR)$(BIN_DIR)/i3blocks-do-not-disturb
	$(setup_file)/scripts/i3blocks/i3blocks-idle-inhibitor > $(DESTDIR)$(BIN_DIR)/i3blocks-idle-inhibitor
	$(setup_file)/scripts/i3blocks/i3blocks-microphone     > $(DESTDIR)$(BIN_DIR)/i3blocks-microphone
	$(setup_file)/scripts/i3blocks/i3blocks-music          > $(DESTDIR)$(BIN_DIR)/i3blocks-music
	$(setup_file)/scripts/i3blocks/i3blocks-network        > $(DESTDIR)$(BIN_DIR)/i3blocks-network
	$(setup_file)/scripts/i3blocks/i3blocks-night-mode     > $(DESTDIR)$(BIN_DIR)/i3blocks-night-mode
	$(setup_file)/scripts/i3blocks/i3blocks-pomodoro       > $(DESTDIR)$(BIN_DIR)/i3blocks-pomodoro
	$(setup_file)/scripts/i3blocks/i3blocks-power          > $(DESTDIR)$(BIN_DIR)/i3blocks-power
	$(setup_file)/scripts/i3blocks/i3blocks-time-tracker   > $(DESTDIR)$(BIN_DIR)/i3blocks-time-tracker
	$(setup_file)/scripts/i3blocks/i3blocks-volume         > $(DESTDIR)$(BIN_DIR)/i3blocks-volume
	$(setup_file)/scripts/i3blocks/i3blocks-webcam         > $(DESTDIR)$(BIN_DIR)/i3blocks-webcam
