#!/bin/sh

init_variables() {
  COMMAND=${0##*/}

  TMP_FILE="$( mktemp )"
  trap 'rm -f "${TMP_FILE}"' EXIT

  SCRIPT=
  PATHS=
}

parse_command_line() {
  SCRIPT="$1"
  shift 2> /dev/null
  PATHS="$*"
}

validate_command_line() {
  if [ -z "${SCRIPT}" ]; then
    exit_error "missing sed script argument"
  fi
}

exit_error() {
  [ -z "$1" ] || echo "${COMMAND}: $1"
  exit 1
} >&2

run_sed() {
  # exclude symlinks and binary files
  # shellcheck disable=SC2086
  git grep -I -l '' -- ${PATHS} \
    | xargs -I {} \
      sh -c "sed \"${SCRIPT}\" {} > \"${TMP_FILE}\" \
             && cp \"${TMP_FILE}\" {}"
}

init_variables
parse_command_line "$@"
validate_command_line

run_sed
