#!/bin/sh

init_variables() {
  COMMAND=${0##*/}

  TMP_FILE=$( mktemp )
  trap 'rm "${TMP_FILE}"' EXIT

  SCRIPT=
}

parse_command_line() {
  SCRIPT="$*"
}

validate_command_line() {
  if [ -z "${SCRIPT}" ]; then
    exit_error "missing sed script argument"
  fi
}

exit_error() {
  [ -z "$1" ] || echo "${COMMAND}: $1"
  exit 1
} >&2

run_sed() {
  # exclude symlinks and binary files
  git grep -I -l '' \
    | xargs -I {} \
      sh -c "sed \"${SCRIPT}\" {} > \"${TMP_FILE}\" \
             && cp \"${TMP_FILE}\" {}"
}

init_variables
parse_command_line "$@"
validate_command_line

run_sed
