#!/bin/sh
# commands used:
# - git (includes own command: root)

TODO_FILE="$( git root )/TODO.md"

# groups are ordered by importance
cat <<- EOF > "${TODO_FILE}"
	# TODO

	## Periodic

	## Cleaning

	## Bugs

	## Testing

	## Improvements

	## New Features

	## Research

EOF

git add "${TODO_FILE}"

git commit "${TODO_FILE}" -m 'add TODO file skeleton'
