#!/bin/sh

init_variables() {
  COMMAND=${0##*/}

  INITIAL_REV=
  REV_RANGE=
  RUN_COMMAND=
  QUIET=false
}

parse_command_line() {
  while getopts q OPT; do
    case "${OPT}" in
      q) QUIET=true ;;
      ?) exit_error ;;
    esac
  done

  shift $(( OPTIND - 1 ))

  if [ $# -gt 0 ]; then
    REV_RANGE="$1"
    shift
    RUN_COMMAND="$*"
  fi
}

validate_command_line() {
  if [ -z "${REV_RANGE}" ]; then
    exit_error 'no revisions range'
  fi

  if [ -z "${RUN_COMMAND}" ]; then
    exit_error 'no command to run'
  fi
}

exit_error() {
  [ -z "$1" ] || echo "${COMMAND}: $1"
  exit 1
} >&2

abort_if_dirty_repo() {
  if ! git rev-parse --git-dir > /dev/null 2>&1; then
    exit_error 'not in a git repository'
  fi

  if ! git diff-index --quiet --cached HEAD; then
    exit_error 'you have staged but not committed changes that would be lost'
  fi

  if ! git diff-files --quiet; then
    exit_error 'you have unstaged changes that would be lost'
  fi

  UNTRACKED=$( git ls-files --exclude-standard --others )
  if [ -n "${UNTRACKED}" ]; then
    exit_error 'you have untracked files that could be overwritten'
  fi
}

save_initial_rev() {
  if git symbolic-ref HEAD > /dev/null 2>&1; then
    INITIAL_REV=$( git symbolic-ref --short HEAD )
  else
    INITIAL_REV=$( git rev-parse HEAD )
  fi
}

restore_initial_rev() {
  git checkout -q "${INITIAL_REV}"
}

run_command_over_range() {
  for REVISION in $( git rev-list --reverse "${REV_RANGE}" ); do
    [ "${QUIET}" = 'false' ] && echo "Checking out: $( git log --oneline -1 "${REVISION}" )"
    git checkout -q "${REVISION}"
    eval "${RUN_COMMAND}"
    git reset --hard -q
  done
}

init_variables
parse_command_line "$@"
validate_command_line

abort_if_dirty_repo
save_initial_rev
run_command_over_range
restore_initial_rev
