#!/bin/sh

init_variables() {
  COMMAND=${0##*/}

  TYPE=repo
  COMMIT=HEAD
  REMOTE=$( git config --default origin browse.remote )
}

parse_command_line() {
  while getopts c:r:t: OPT; do
    case "${OPT}" in
      c) COMMIT="${OPTARG}" ;;
      r) REMOTE="${OPTARG}" ;;
      t) TYPE="${OPTARG}" ;;
      ?) exit_error ;;
    esac
  done

  shift $(( OPTIND - 1 ))
}

validate_command_line() {
  if [ "${TYPE}" != 'repo' ] \
     && [ "${TYPE}" != 'commit' ] \
     && [ "${TYPE}" != 'issue' ] \
     && [ "${TYPE}" != 'review' ]; then
    exit_error "invalid type argument '${TYPE}'"
  fi

  if ! git rev-parse -q --verify "${COMMIT}^{commit}" > /dev/null; then
    exit_error "invalid commit '${COMMIT}'"
  fi

  if ! git remote | grep -q "${REMOTE}"; then
    exit_error "invalid remote '${REMOTE}'"
  fi
}

exit_error() {
  [ -z "$1" ] || echo "${COMMAND}: $1"
  exit 1
} >&2

display_url() {
  REMOTE_ALIAS=$(
    git config "remote.${REMOTE}.url" \
    | sed 's/:.*//'
  )

  REPO_PATH_SED=$(
    git config "browse.${REMOTE_ALIAS}.repoPathSed"
  )
  [ -z "${REPO_PATH_SED}" ] && exit_error 'remote does not use a valid URL alias for browsing'

  REPO_PATH=$(
    git config "remote.${REMOTE}.url" \
    | sed "${REPO_PATH_SED}"
  )

  URL=$(
    git config "browse.${REMOTE_ALIAS}.${TYPE}Url" \
    | sed "s|{repo_path}|${REPO_PATH}|"
  )
  [ -z "${URL}" ] && exit_error 'remote does not support this type of URL for browsing'

  case "${TYPE}" in
    repo)
      echo "${URL}"
      ;;
    commit)
      COMMIT_ID=$( git rev-parse "${COMMIT}" )
      echo "${URL}" | sed "s/{commit_id}/${COMMIT_ID}/"
      ;;
    issue)
      ISSUE_ID=$( git commit-issue-id "${COMMIT}" )
      [ -z "${ISSUE_ID}" ] && exit_error 'commit has no issue id linked to it'
      echo "${URL}" | sed "s/{issue_id}/${ISSUE_ID}/"
      ;;
    review)
      REVIEW_ID=$( git commit-review-id "${COMMIT}" )
      [ -z "${REVIEW_ID}" ] &&  exit_error 'commit has no review id linked to it'
      echo "${URL}" | sed "s/{review_id}/${REVIEW_ID}/"
      ;;
  esac
}

init_variables
parse_command_line "$@"
validate_command_line

display_url
