#!/bin/sh

init_variables() {
  COMMAND=${0##*/}

  CONFIG=false
  ALL=false
  unset OLD_EMAIL
  unset CORRECT_EMAIL
  unset CORRECT_NAME
  TYPE='both'
}

parse_command_line() {
  while getopts ace:n:o:t: OPT; do
    case "${OPT}" in
      a) ALL=true ;;
      c) CONFIG=true ;;
      e) CORRECT_EMAIL="${OPTARG}" ;;
      n) CORRECT_NAME="${OPTARG}" ;;
      o) OLD_EMAIL="${OPTARG}" ;;
      t) TYPE="${OPTARG}" ;;
      ?) exit_error ;;
    esac
  done

  shift $(( OPTIND - 1 ))

  if [ "${CONFIG}" = 'true' ]; then
    # use config values if not explicitly already defined
    [ -n "${CORRECT_EMAIL+x}" ] || CORRECT_EMAIL=$( git config user.email )
    [ -n "${CORRECT_NAME+x}" ] || CORRECT_NAME=$( git config user.name )
  fi
}

validate_command_line() {
  # Either OLD_EMAIL should be set or ALL should be true
  if [ -z "${OLD_EMAIL+x}" ] && [ "${ALL}" = 'false' ]; then
    msg="missing target of the rewrite"
    msg="${msg}\nuse either -o option or -a flag"
    exit_error "${msg}"
  fi

  # OLD_EMAIL shouldn't be set if ALL is true as well to prevent misuse
  if [ -n "${OLD_EMAIL+x}" ] && [ "${ALL}" = 'true' ]; then
    msg="ambiguous target of the rewrite"
    msg="${msg}\nuse either -o option or -a flag"
    exit_error "${msg}"
  fi

  # CORRECT_NAME should be either unset or set to non-empty string
  [ -n "${CORRECT_NAME-x}" ] || exit_error "empty name is not allowed"

  # Either CORRECT_EMAIL or CORRECT_NAME should be set
  if [ -z "${CORRECT_EMAIL+x}" ] && [ -z "${CORRECT_NAME+x}" ]; then
    msg="missing correct email and/or name to set"
    msg="${msg}\nuse -e and/or -n options"
    msg="${msg}\nor -c flag with user values set in Git config"
    exit_error "${msg}"
  fi

  # TYPE should be a valid identifier
  if [ "${TYPE}" != 'both' ] \
     && [ "${TYPE}" != 'author' ] \
     && [ "${TYPE}" != 'committer' ]; then
    exit_error "invalid type '${TYPE}'"
  fi
}

exit_error() {
  [ -z "$1" ] || echo "${COMMAND}: $1"
  exit 1
} >&2

reauthor() {
  AUTHOR='
    if [ "${ALL}" = "true" ] || [ "${GIT_AUTHOR_EMAIL}" = "${OLD_EMAIL}" ]; then
      [ -z "${CORRECT_EMAIL+x}" ] || export GIT_AUTHOR_EMAIL="${CORRECT_EMAIL}"
      [ -z "${CORRECT_NAME+x}" ] || export GIT_AUTHOR_NAME="${CORRECT_NAME}"
    fi
  '
  COMMITTER='
    if [ "${ALL}" = "true" ] || [ "${GIT_COMMITTER_EMAIL}" = "${OLD_EMAIL}" ]; then
      [ -z "${CORRECT_EMAIL+x}" ] || export GIT_COMMITTER_EMAIL="${CORRECT_EMAIL}"
      [ -z "${CORRECT_NAME+x}" ] || export GIT_COMMITTER_NAME="${CORRECT_NAME}"
    fi
  '

  case "${TYPE}" in
    author) FILTER="${AUTHOR}" ;;
    committer) FILTER="${COMMITTER}" ;;
    both) FILTER="${AUTHOR} ${COMMITTER}" ;;
  esac

  export ALL
  export OLD_EMAIL
  export CORRECT_EMAIL
  export CORRECT_NAME

  git filter-branch -f --env-filter "${FILTER}" \
  --tag-name-filter cat -- --branches --tags
}

init_variables
parse_command_line "$@"
validate_command_line

reauthor
