all: tmux-scripts

tmux-scripts:
	setup/setup-script tmux/tmux-extract-tokens
	setup/setup-script tmux/tmux-move-pane-window-index
	setup/setup-script tmux/tmux-move-window-index
	setup/setup-script tmux/tmux-notify-alert
	setup/setup-script tmux/tmux-select-pane-nvim
	setup/setup-script tmux/tmux-send-nvim
	setup/setup-script tmux/tmux-switch
	setup/setup-script tmux/tmux-toggle-monitoring
	setup/setup-script tmux/tmux-toggle-no-distraction
