#!/bin/sh

EVENT="$1"
DURATION="$2"
SOCKET_PATH="$3"
SESSION_ID="$4"
WINDOW_ID="$5"

SILENCE_THRESHOLD=10

STATUS=
ON='on'
OFF='off'

MONITORING_ID='tmux_alert_'
MONITORING_ID="${MONITORING_ID}_${SOCKET_PATH##*/}"
MONITORING_ID="${MONITORING_ID}_${SESSION_ID#$}"
MONITORING_ID="${MONITORING_ID}_${WINDOW_ID#@}"

MONITORING_FILE="${XDG_RUNTIME_DIR:-/tmp}/${MONITORING_ID}"

if [ "${EVENT}" = 'silence' ]; then
  ON="${SILENCE_THRESHOLD}"
  OFF='0'
fi

if tmux show-window-options | grep -q "monitor-${EVENT} ${ON}"; then
  tmux set-window-option "monitor-${EVENT}" "${OFF}"
  rm -f "${MONITORING_FILE}"
  tmux display-message "Monitoring ${EVENT}: disabled"
else
  tmux set-window-option "monitor-${EVENT}" "${ON}"
  echo "${DURATION}" > "${MONITORING_FILE}"
  tmux display-message "Monitoring ${EVENT} (${DURATION}): enabled"

  if [ -n "${DISPLAY}" ]; then
    swaymsg -q "mark --add ${MONITORING_ID}"
  fi
fi
