#!/bin/sh

ALERT_TYPE="$1"
ALERT_SOCKET_PATH="$2"
ALERT_SESSION_ID="$3"
ALERT_WINDOW_ID="$4"

# disable alerts after trigger
tmux \
  set-window-option \
    -t "${ALERT_SESSION_ID}:${ALERT_WINDOW_ID}" \
    monitor-activity off \; \
  set-window-option \
    -t "${ALERT_SESSION_ID}:${ALERT_WINDOW_ID}" \
    monitor-silence 0

ALERT_SESSION_NAME=$(
  tmux list-sessions -F '#{session_id} #{session_name}' \
    | grep "^${ALERT_SESSION_ID} " \
    | cut -f 2- -d ' '
)
ALERT_WINDOW_NAME=$(
  tmux list-windows -t "${ALERT_SESSION_ID}" -F '#{window_id} #{window_name}' \
    | grep "^${ALERT_WINDOW_ID} " \
    | cut -f 2- -d ' '
)

MESSAGE="${ALERT_TYPE}"
MESSAGE="${MESSAGE} in session \"${ALERT_SESSION_NAME}\""
MESSAGE="${MESSAGE} window \"${ALERT_WINDOW_NAME}\""

tmux display-message "${MESSAGE}"

if [ -n "${DISPLAY}" ]; then
  notify-tmux-alert \
    "${ALERT_TYPE}" \
    "${ALERT_SOCKET_PATH##*/}" \
    "${ALERT_SESSION_ID#$}" \
    "${ALERT_SESSION_NAME}" \
    "${ALERT_WINDOW_ID#@}" \
    "${ALERT_WINDOW_NAME}"
fi
