#!/bin/sh

TARGET="$1"
TOKEN_TYPE="$2"

SPLIT_HEIGHT=20

capture_text() {
  if [ "${TARGET}" = 'pane' ]; then
    capture_pane "$( tmux display -p -F '#{pane_id}' )"
  elif [ "${TARGET}" = 'window' ]; then
    for PANE_ID in $( tmux list-panes -F '#{pane_id}' ); do
      capture_pane "${PANE_ID}"
    done
  fi
}

capture_pane() {
  PANE_ID="$1"

  HEIGHT=$( tmux display -t ":.${PANE_ID}" -p -F '#{pane_height}')
  SCROLL_POSITION=$( tmux display -t ":.${PANE_ID}" -p -F '#{scroll_position}')

  if [ -z "${SCROLL_POSITION}" ]; then
    SCROLL_POSITION=0
  fi

  START="-${SCROLL_POSITION}"
  END=$(( HEIGHT - SCROLL_POSITION - 1 ))

  tmux capture-pane -t ":.${PANE_ID}" -pJ -S "${START}" -E "${END}"
}

ITEM=$(
  capture_text \
    | extract-tokens "${TOKEN_TYPE}" \
    | sort -u \
    | fzf-tmux -d "${SPLIT_HEIGHT}" -- \
        --prompt "${TOKEN_TYPE}> " \
        --expect={key/enter},ctrl-{key/open/low},ctrl-{key/search/low},ctrl-{key/yank/low} \
)

[ -n "${ITEM}" ] || exit 0

KEY=$( echo "${ITEM}" | head -n 1 )
TEXT=$( echo "${ITEM}" | tail -n +2 )

case "${KEY}" in
  {key/enter})
    tmux set-buffer -- "${TEXT}"
    tmux paste-buffer
    ;;
  ctrl-{key/open/low})
    xdg-open "${TEXT}" > /dev/null
    ;;
  ctrl-{key/search/low})
    xdg-open "https://www.google.com/search?q=${TEXT}" > /dev/null
    ;;
  ctrl-{key/yank/low})
    wl-copy "${TEXT}" > /dev/null
    ;;
esac

exit 0
