#!/bin/sh

TARGET="$1"
TOKEN_TYPE="$2"

SPLIT_HEIGHT=20

GREP_FUNCTION=

case "${TOKEN_TYPE}" in
  hashes) GREP_FUNCTION=grep_hashes ;;
  lines) GREP_FUNCTION=grep_lines ;;
  paths) GREP_FUNCTION=grep_paths ;;
  urls)  GREP_FUNCTION=grep_urls ;;
  words) GREP_FUNCTION=grep_words ;;
  WORDS) GREP_FUNCTION=grep_WORDS ;;
  *) exit 1
esac

capture_text() {
  if [ "${TARGET}" = 'pane' ]; then
    capture_pane "$( tmux display -p -F '#{pane_id}' )"
  elif [ "${TARGET}" = 'window' ]; then
    for PANE_ID in $( tmux list-panes -F '#{pane_id}' ); do
      capture_pane "${PANE_ID}"
    done
  fi
}

capture_pane() {
  PANE_ID="$1"

  HEIGHT=$( tmux display -t ":.${PANE_ID}" -p -F '#{pane_height}')
  SCROLL_POSITION=$( tmux display -t ":.${PANE_ID}" -p -F '#{scroll_position}')

  if [ -z "${SCROLL_POSITION}" ]; then
    SCROLL_POSITION=0
  fi

  START="-${SCROLL_POSITION}"
  END=$(( HEIGHT - SCROLL_POSITION - 1 ))

  tmux capture-pane -t ":.${PANE_ID}" -pJ -S "${START}" -E "${END}"
}

grep_hashes() {
  grep -E -o '[[:digit:]a-fA-F][-[:digit:]a-fA-F]{5,}'
}

grep_lines() {
  grep '.' | sed -e 's/^[ \t]*//' -e 's/[ \t]*$//'
}

grep_paths() {
  grep -E -o '[-_.~[:alnum:]]*/[-_.%~/[:alnum:]]+'
}

grep_urls() {
  grep -E -o 'https?://[[:alnum:]?=%/_.:,;~@!#$&*+-]*'
}

grep_words() {
  grep -E -o '[-_.[:alnum:]]+'
}

grep_WORDS() {
  grep -E -o '[^ ]+'
}

ITEM=$(
  capture_text \
    | "${GREP_FUNCTION}" \
    | sort -u \
    | fzf-tmux -d "${SPLIT_HEIGHT}" -- \
        --prompt "${TOKEN_TYPE}> " \
        --expect={key/enter},ctrl-{key/open/low},ctrl-{key/search/low},ctrl-{key/yank/low} \
)

[ -n "${ITEM}" ] || exit 0

KEY=$( echo "${ITEM}" | head -n 1 )
TEXT=$( echo "${ITEM}" | tail -n +2 )

case "${KEY}" in
  {key/enter})
    tmux set-buffer -- "${TEXT}"
    tmux paste-buffer
    ;;
  ctrl-{key/open/low})
    xdg-open "${TEXT}" > /dev/null
    ;;
  ctrl-{key/search/low})
    xdg-open "https://www.google.com/search?q=${TEXT}" > /dev/null
    ;;
  ctrl-{key/yank/low})
    wl-copy "${TEXT}" > /dev/null
    ;;
esac

exit 0
