#!/bin/sh

# shellcheck disable=SC1083

TARGET="$1"
TOKEN_TYPE="$2"

LAYOUT='-w 30% -h 30%'

capture_text() {
  if [ "${TARGET}" = 'pane' ]; then
    capture_pane "$( tmux display -p -F '#{pane_id}' )"
  elif [ "${TARGET}" = 'window' ]; then
    for PANE_ID in $( tmux list-panes -F '#{pane_id}' ); do
      capture_pane "${PANE_ID}"
    done
  fi
}

capture_pane() {
  PANE_ID="$1"

  HEIGHT=$( tmux display -t ":.${PANE_ID}" -p -F '#{pane_height}' )
  SCROLL_POSITION=$( tmux display -t ":.${PANE_ID}" -p -F '#{scroll_position}' )

  if [ -z "${SCROLL_POSITION}" ]; then
    SCROLL_POSITION=0
  fi

  START="-${SCROLL_POSITION}"
  END=$(( HEIGHT - SCROLL_POSITION - 1 ))

  tmux capture-pane -t ":.${PANE_ID}" -pJ -S "${START}" -E "${END}"
}

ITEM=$(
  capture_text \
    | extract-tokens "${TOKEN_TYPE}" \
    | sort -u \
    | fzf-tmux "${LAYOUT}" -- \
        --header "$( printf 'Extract %s from %s\n ' "${TOKEN_TYPE}" "${TARGET}" )" \
        --header-first \
        --info hidden \
        --border sharp \
        --reverse \
        --expect={key/return/return},ctrl-{key/open/low},ctrl-{key/search/low},ctrl-{key/yank/low}
)

[ -n "${ITEM}" ] || exit 0

KEY=$( echo "${ITEM}" | head -n 1 )
TEXT=$( echo "${ITEM}" | tail -n +2 )

case "${KEY}" in
  {key/return/return})
    tmux set-buffer -w -- "${TEXT}"
    tmux paste-buffer
    ;;
  ctrl-{key/open/low})
    tmux set-buffer -w -- "${TEXT}"
    xdg-open "${TEXT}" > /dev/null
    ;;
  ctrl-{key/search/low})
    tmux set-buffer -w -- "${TEXT}"
    xdg-open "https://www.google.com/search?q=${TEXT}" > /dev/null
    ;;
  ctrl-{key/yank/low})
    tmux set-buffer -w -- "${TEXT}"
    ;;
esac

exit 0
