#!/bin/sh

TARGET="$1"

init_variables() {
  FILE_PATH="${XDG_RUNTIME_DIR:-/tmp}/tmux_no_distraction"

  [ -n "${DISPLAY}" ] || return

  CURRENT_SWAY_WINDOW=$(
    swaymsg -t get_tree \
      | jq 'recurse(.nodes[]?) | select(.focused == true)'
  )

  CURRENT_SWAY_WINDOW_ID=$( echo "${CURRENT_SWAY_WINDOW}" | jq '.id' )

  FILE_PATH="${FILE_PATH}_${CURRENT_SWAY_WINDOW_ID}"
}

sway_fullscreen() {
  [ -n "${DISPLAY}" ] || return

  ACTION="$1"

  swaymsg -q fullscreen "${ACTION}"
}

tmux_pane_zoom() {
  ACTION="$1"

  ZOOM_STATUS=$( tmux display -p '#{window_zoomed_flag}' )

  if { [ "${ACTION}" = 'enable' ] && [ "${ZOOM_STATUS}" = '0' ]; } \
    || { [ "${ACTION}" = 'disable' ] && [ "${ZOOM_STATUS}" = '1' ]; }; then
    tmux resize-pane -Z
  fi
}

tmux_status_line() {
  ACTION="$1"

  if [ "${ACTION}" = 'hide' ]; then
    tmux set -g status off
  elif [ "${ACTION}" = 'show' ]; then
    tmux set -g status on
  fi
}

is_no_distraction_mode_enabled() {
  [ -f "${FILE_PATH}" ]
}

no_distraction_mode_enable() {
  tmux_status_line 'hide'
  sway_fullscreen 'enable'

  if [ "${TARGET}" = 'pane' ]; then
    tmux_pane_zoom 'enable'
  fi

  touch "${FILE_PATH}"
}

no_distraction_mode_disable() {
  tmux_status_line 'show'
  sway_fullscreen 'disable'
  tmux_pane_zoom 'disable'

  rm -f "${FILE_PATH}"
}

init_variables

if is_no_distraction_mode_enabled; then
  no_distraction_mode_disable
else
  no_distraction_mode_enable
fi
