#!/bin/sh

tmux list-sessions -F '#{session_id} #{session_name}' \
  | fzf-tmux "$@" --\
      --with-nth 2 \
      --prompt 'Switch to ' \
      --header "$( printf '\n' )" \
      --info hidden \
      --reverse \
  | cut -d' ' -f1 \
  | xargs tmux switch-client -t 2> /dev/null

exit 0
