#!/bin/sh

ALERT_TYPE="$1"
ALERT_SOCKET_PATH="$2"
ALERT_SESSION_ID="$3"
ALERT_WINDOW_ID="$4"

MONITORING_ID='tmux_alert_'
MONITORING_ID="${MONITORING_ID}_${ALERT_SOCKET_PATH##*/}"
MONITORING_ID="${MONITORING_ID}_${ALERT_SESSION_ID#$}"
MONITORING_ID="${MONITORING_ID}_${ALERT_WINDOW_ID#@}"

MONITORING_FILE="${XDG_RUNTIME_DIR:-/tmp}/${MONITORING_ID}"
DURATION="$( cat "${MONITORING_FILE}" 2> /dev/null )"

if [ "${DURATION}" != 'continuous' ]; then
  tmux \
    set-window-option \
      -t "${ALERT_SESSION_ID}:${ALERT_WINDOW_ID}" \
      monitor-activity off \; \
    set-window-option \
      -t "${ALERT_SESSION_ID}:${ALERT_WINDOW_ID}" \
      monitor-bell off \; \
    set-window-option \
      -t "${ALERT_SESSION_ID}:${ALERT_WINDOW_ID}" \
      monitor-silence 0
fi

ALERT_SESSION_NAME=$(
  tmux list-sessions -F '#{session_id} #{session_name}' \
    | grep "^${ALERT_SESSION_ID} " \
    | cut -f 2- -d ' '
)
ALERT_WINDOW_NAME=$(
  tmux list-windows -t "${ALERT_SESSION_ID}" -F '#{window_id} #{window_name}' \
    | grep "^${ALERT_WINDOW_ID} " \
    | cut -f 2- -d ' '
)

MESSAGE="${ALERT_TYPE}"
MESSAGE="${MESSAGE} in session \"${ALERT_SESSION_NAME}\""
MESSAGE="${MESSAGE} window \"${ALERT_WINDOW_NAME}\""

tmux display-message "${MESSAGE}"

if [ -n "${DISPLAY}" ]; then
  MESSAGE="socket: ${ALERT_SOCKET_PATH##*/}\n"
  MESSAGE="${MESSAGE}session: ${ALERT_SESSION_NAME}\n"
  MESSAGE="${MESSAGE}window: ${ALERT_WINDOW_NAME}"

  notify \
    -c 'notice' \
    -i "${MONITORING_ID}" \
    "tmux ${ALERT_TYPE} detected" \
    "${MESSAGE}"

  swaymsg -q "[con_mark=\"${MONITORING_ID}\"]" urgent enable
fi
