#!/bin/sh

SESSION=$(
  tmux list-sessions -F '#{session_id} #{session_name}' \
    | fzf-tmux "$@" -- \
        --with-nth 2 \
        --prompt 'Switch to ' \
        --header "$( printf '\n' )" \
        --info hidden \
        --reverse \
    | cut -d' ' -f1 \
)

[ -n "${SESSION}" ] || exit 0

tmux switch-client -t "${SESSION}"
