all: applications

applications:
	mkdir -p $(DESTDIR)$(DATA_DIR)/applications

	cp files/data/applications/chat_client.desktop     $(DESTDIR)$(DATA_DIR)/applications/chat_client.desktop
	cp files/data/applications/document_viewer.desktop $(DESTDIR)$(DATA_DIR)/applications/document_viewer.desktop
	cp files/data/applications/mail_client.desktop     $(DESTDIR)$(DATA_DIR)/applications/mail_client.desktop
	cp files/data/applications/news_reader.desktop     $(DESTDIR)$(DATA_DIR)/applications/news_reader.desktop
	cp files/data/applications/web_browser.desktop     $(DESTDIR)$(DATA_DIR)/applications/web_browser.desktop
	cp files/data/applications/system_monitor.desktop  $(DESTDIR)$(DATA_DIR)/applications/system_monitor.desktop
	cp files/data/applications/terminal.desktop        $(DESTDIR)$(DATA_DIR)/applications/terminal.desktop
