all: applications

applications:
	$(start_setup)

	mkdir -p $(DESTDIR)$(DATA_DIR)/applications

	cp data/applications/chat_client.desktop             $(DESTDIR)$(DATA_DIR)/applications/chat_client.desktop
	cp data/applications/chromium_web_browser.desktop    $(DESTDIR)$(DATA_DIR)/applications/chromium_web_browser.desktop
	cp data/applications/document_viewer.desktop         $(DESTDIR)$(DATA_DIR)/applications/document_viewer.desktop
	cp data/applications/firefox_web_browser.desktop     $(DESTDIR)$(DATA_DIR)/applications/firefox_web_browser.desktop
	cp data/applications/mail_client.desktop             $(DESTDIR)$(DATA_DIR)/applications/mail_client.desktop
	cp data/applications/music_player.desktop            $(DESTDIR)$(DATA_DIR)/applications/music_player.desktop
	cp data/applications/news_reader.desktop             $(DESTDIR)$(DATA_DIR)/applications/news_reader.desktop
	cp data/applications/qutebrowser_web_browser.desktop $(DESTDIR)$(DATA_DIR)/applications/qutebrowser_web_browser.desktop
	cp data/applications/raster_graphics_editor.desktop  $(DESTDIR)$(DATA_DIR)/applications/raster_graphics_editor.desktop
	cp data/applications/system_monitor.desktop          $(DESTDIR)$(DATA_DIR)/applications/system_monitor.desktop
	cp data/applications/terminal.desktop                $(DESTDIR)$(DATA_DIR)/applications/terminal.desktop
	cp data/applications/vector_graphics_editor.desktop  $(DESTDIR)$(DATA_DIR)/applications/vector_graphics_editor.desktop
	cp data/applications/video_player.desktop            $(DESTDIR)$(DATA_DIR)/applications/video_player.desktop
