all: tofi-configs

tofi-configs:
	setup/setup-config tofi/config           $(CONFIG_DIR)/tofi/config
	setup/setup-config tofi/config.d/general $(CONFIG_DIR)/tofi/config.d/general
	setup/setup-config tofi/config.d/style   $(CONFIG_DIR)/tofi/config.d/style
