newsboat:
	$(start_setup)

	$(call copy_file,newsboat/urls,$(CONFIG_DIR)/newsboat/urls)
	$(call copy_file,newsboat/config,$(CONFIG_DIR)/newsboat/config)
	$(call copy_folder,newsboat/conf,$(CONFIG_DIR)/newsboat/conf)

	$(end_setup)
