newsboat:
	$(start_setup)

	$(call copy_file,urls,$(CONFIG_DIR)/newsboat/urls)
	$(call copy_file,config,$(CONFIG_DIR)/newsboat/config)
	$(call copy_folder,conf,$(CONFIG_DIR)/newsboat/conf)

	$(end_setup)
