backup-task-logs(1perso)

# NAME

backup-task-logs - Backup task logs to remote server

# SYNOPSIS

backup-task-logs

# DESCRIPTION

Backup task logs to remote server

# OPTIONS

None

# OPERANDS

None

# ENVIRONMENT VARIABLES

_XDG_DATA_HOME_
	Path to user-specific base directory to store data files++
If unset, defaults to $HOME/.local/share

# FILES

_$XDG_DATA_HOME/task_
	Directory containing task logs

# DEPENDENCIES

- rsync
