backup-contacts(1perso)

# NAME

backup-contacts - Backup contacts to remote server

# SYNOPSIS

backup-contacts

# DESCRIPTION

Backup contacts to remote server

# OPTIONS

None

# OPERANDS

None

# ENVIRONMENT VARIABLES

_XDG_CONTACTS_DIR_
	Path to user-specific contacts directory++
If unset, defaults to $HOME/Contacts

# FILES

_$XDG_CONTACTS_DIR_
	Directory containing the contacts

# DEPENDENCIES

- rsync
