backup-time-tracker-logs(1perso)

# NAME

backup-time-tracker-logs - Backup time tracker logs to remote server

# SYNOPSIS

backup-time-tracker-logs

# DESCRIPTION

Backup time tracker logs to remote server

# OPTIONS

None

# OPERANDS

None

# ENVIRONMENT VARIABLES

_XDG_DATA_HOME_
	Path to user-specific base directory to store data files++
If unset, defaults to $HOME/.local/share

# FILES

_$XDG_DATA_HOME/time_tracker_
	Directory containing time tracker logs

# DEPENDENCIES

- rsync
