battery-status(1perso)

# NAME

battery-status - Report status of battery

# SYNOPSIS

battery-status

# DESCRIPTION

Print general status info about the battery

We assume all the batteries present report the same type of capacity,
either charge or energy (no mix)

# OPTIONS

None

# OPERANDS

None

# ENVIRONMENT VARIABLES

None

# FILES

_/sys/class/power_supply/AC/\*_++
_/sys/class/power_supply/BAT\*/\*_
	Power supply files

# DEPENDENCIES

None
