all: shell-docs

shell-docs:
	mkdir -p $(DESTDIR)$(DATA_DIR)/man/man1

	$(setup_file)/docs/shell/backup.scd                   | scdoc > $(DESTDIR)$(DATA_DIR)/man/man1/backup.1perso
	$(setup_file)/docs/shell/base.scd                     | scdoc > $(DESTDIR)$(DATA_DIR)/man/man1/base.1perso
	$(setup_file)/docs/shell/battery-status.scd           | scdoc > $(DESTDIR)$(DATA_DIR)/man/man1/battery-status.1perso
	$(setup_file)/docs/shell/calculate.scd                | scdoc > $(DESTDIR)$(DATA_DIR)/man/man1/calculate.1perso
	$(setup_file)/docs/shell/check-notify-low-battery.scd | scdoc > $(DESTDIR)$(DATA_DIR)/man/man1/check-notify-low-battery.1perso
	$(setup_file)/docs/shell/color-picker.scd             | scdoc > $(DESTDIR)$(DATA_DIR)/man/man1/color-picker.1perso
	$(setup_file)/docs/shell/copy-otp.scd                 | scdoc > $(DESTDIR)$(DATA_DIR)/man/man1/copy-otp.1perso
	$(setup_file)/docs/shell/copy-password.scd            | scdoc > $(DESTDIR)$(DATA_DIR)/man/man1/copy-password.1perso
	$(setup_file)/docs/shell/do-not-disturb.scd           | scdoc > $(DESTDIR)$(DATA_DIR)/man/man1/do-not-disturb.1perso
	$(setup_file)/docs/shell/documentation-all.scd        | scdoc > $(DESTDIR)$(DATA_DIR)/man/man1/documentation-all.1perso
	$(setup_file)/docs/shell/documentation.scd            | scdoc > $(DESTDIR)$(DATA_DIR)/man/man1/documentation.1perso
	$(setup_file)/docs/shell/extract-tokens.scd           | scdoc > $(DESTDIR)$(DATA_DIR)/man/man1/extract-tokens.1perso
	$(setup_file)/docs/shell/http-env.scd                 | scdoc > $(DESTDIR)$(DATA_DIR)/man/man1/http-env.1perso
	$(setup_file)/docs/shell/http-stats.scd               | scdoc > $(DESTDIR)$(DATA_DIR)/man/man1/http-stats.1perso
	$(setup_file)/docs/shell/i3blocks-mode.scd            | scdoc > $(DESTDIR)$(DATA_DIR)/man/man1/i3blocks-mode.1perso
	$(setup_file)/docs/shell/influx-env.scd               | scdoc > $(DESTDIR)$(DATA_DIR)/man/man1/influx-env.1perso
	$(setup_file)/docs/shell/launch-tmux-env.scd          | scdoc > $(DESTDIR)$(DATA_DIR)/man/man1/launch-tmux-env.1perso
	$(setup_file)/docs/shell/line-by-line.scd             | scdoc > $(DESTDIR)$(DATA_DIR)/man/man1/line-by-line.1perso
	$(setup_file)/docs/shell/loop.scd                     | scdoc > $(DESTDIR)$(DATA_DIR)/man/man1/loop.1perso
	$(setup_file)/docs/shell/man.scd                      | scdoc > $(DESTDIR)$(DATA_DIR)/man/man1/man.1perso
	$(setup_file)/docs/shell/mount-device.scd             | scdoc > $(DESTDIR)$(DATA_DIR)/man/man1/mount-device.1perso
	$(setup_file)/docs/shell/mysql-env.scd                | scdoc > $(DESTDIR)$(DATA_DIR)/man/man1/mysql-env.1perso
	$(setup_file)/docs/shell/night-mode.scd               | scdoc > $(DESTDIR)$(DATA_DIR)/man/man1/night-mode.1perso
	$(setup_file)/docs/shell/notify.scd                   | scdoc > $(DESTDIR)$(DATA_DIR)/man/man1/notify.1perso
	$(setup_file)/docs/shell/open-document.scd            | scdoc > $(DESTDIR)$(DATA_DIR)/man/man1/open-document.1perso
	$(setup_file)/docs/shell/play-somafm.scd              | scdoc > $(DESTDIR)$(DATA_DIR)/man/man1/play-somafm.1perso
	$(setup_file)/docs/shell/pomodoro.scd                 | scdoc > $(DESTDIR)$(DATA_DIR)/man/man1/pomodoro.1perso
	$(setup_file)/docs/shell/presentation-mode.scd        | scdoc > $(DESTDIR)$(DATA_DIR)/man/man1/presentation-mode.1perso
	$(setup_file)/docs/shell/project-path.scd             | scdoc > $(DESTDIR)$(DATA_DIR)/man/man1/project-path.1perso
	$(setup_file)/docs/shell/query-hosts-tags.scd         | scdoc > $(DESTDIR)$(DATA_DIR)/man/man1/query-hosts-tags.1perso
	$(setup_file)/docs/shell/read-news.scd                | scdoc > $(DESTDIR)$(DATA_DIR)/man/man1/read-news.1perso
	$(setup_file)/docs/shell/redis-env.scd                | scdoc > $(DESTDIR)$(DATA_DIR)/man/man1/redis-env.1perso
	$(setup_file)/docs/shell/screenshot.scd               | scdoc > $(DESTDIR)$(DATA_DIR)/man/man1/screenshot.1perso
	$(setup_file)/docs/shell/somafm.scd                   | scdoc > $(DESTDIR)$(DATA_DIR)/man/man1/somafm.1perso
	$(setup_file)/docs/shell/ssh-tags.scd                 | scdoc > $(DESTDIR)$(DATA_DIR)/man/man1/ssh-tags.1perso
	$(setup_file)/docs/shell/start-task.scd               | scdoc > $(DESTDIR)$(DATA_DIR)/man/man1/start-task.1perso
	$(setup_file)/docs/shell/status.scd                   | scdoc > $(DESTDIR)$(DATA_DIR)/man/man1/status.1perso
	$(setup_file)/docs/shell/system-menu.scd              | scdoc > $(DESTDIR)$(DATA_DIR)/man/man1/system-menu.1perso
	$(setup_file)/docs/shell/task.scd                     | scdoc > $(DESTDIR)$(DATA_DIR)/man/man1/task.1perso
	$(setup_file)/docs/shell/tmux-env.scd                 | scdoc > $(DESTDIR)$(DATA_DIR)/man/man1/tmux-env.1perso
	$(setup_file)/docs/shell/url.scd                      | scdoc > $(DESTDIR)$(DATA_DIR)/man/man1/url.1perso
	$(setup_file)/docs/shell/weechat-fifo.scd             | scdoc > $(DESTDIR)$(DATA_DIR)/man/man1/weechat-fifo.1perso
	$(setup_file)/docs/shell/xdg-open.scd                 | scdoc > $(DESTDIR)$(DATA_DIR)/man/man1/xdg-open.1perso
