all: shell-docs

shell-docs:
	mkdir -p $(DESTDIR)$(DATA_DIR)/man/man1

	scdoc < files/docs/shell/backup-bookmarks.scd             > $(DESTDIR)$(DATA_DIR)/man/man1/backup-bookmarks.1
	scdoc < files/docs/shell/backup-notes.scd                 > $(DESTDIR)$(DATA_DIR)/man/man1/backup-notes.1
	scdoc < files/docs/shell/battery-status.scd               > $(DESTDIR)$(DATA_DIR)/man/man1/battery-status.1
	scdoc < files/docs/shell/check-notify-low-battery.scd     > $(DESTDIR)$(DATA_DIR)/man/man1/check-notify-low-battery.1
	scdoc < files/docs/shell/check-notify-package-updates.scd > $(DESTDIR)$(DATA_DIR)/man/man1/check-notify-package-updates.1
	scdoc < files/docs/shell/color-picker.scd                 > $(DESTDIR)$(DATA_DIR)/man/man1/color-picker.1
	scdoc < files/docs/shell/colored-man.scd                  > $(DESTDIR)$(DATA_DIR)/man/man1/colored-man.1
	scdoc < files/docs/shell/do-not-disturb.scd               > $(DESTDIR)$(DATA_DIR)/man/man1/do-not-disturb.1
	scdoc < files/docs/shell/documentation-all.scd            > $(DESTDIR)$(DATA_DIR)/man/man1/documentation-all.1
	scdoc < files/docs/shell/documentation.scd                > $(DESTDIR)$(DATA_DIR)/man/man1/documentation.1
	scdoc < files/docs/shell/exec-desktop-entry.scd           > $(DESTDIR)$(DATA_DIR)/man/man1/exec-desktop-entry.1
	scdoc < files/docs/shell/http-env.scd                     > $(DESTDIR)$(DATA_DIR)/man/man1/http-env.1
	scdoc < files/docs/shell/i3blocks-mode.scd                > $(DESTDIR)$(DATA_DIR)/man/man1/i3blocks-mode.1
	scdoc < files/docs/shell/influx-env.scd                   > $(DESTDIR)$(DATA_DIR)/man/man1/influx-env.1
	scdoc < files/docs/shell/loop.scd                         > $(DESTDIR)$(DATA_DIR)/man/man1/loop.1
	scdoc < files/docs/shell/mysql-env.scd                    > $(DESTDIR)$(DATA_DIR)/man/man1/mysql-env.1
	scdoc < files/docs/shell/notify-end-pomodoro.scd          > $(DESTDIR)$(DATA_DIR)/man/man1/notify-end-pomodoro.1
	scdoc < files/docs/shell/notify-tmux-alert.scd            > $(DESTDIR)$(DATA_DIR)/man/man1/notify-tmux-alert.1
	scdoc < files/docs/shell/notify.scd                       > $(DESTDIR)$(DATA_DIR)/man/man1/notify.1
	scdoc < files/docs/shell/packages-updates.scd             > $(DESTDIR)$(DATA_DIR)/man/man1/packages-updates.1
	scdoc < files/docs/shell/pacman-pkgdiff.scd               > $(DESTDIR)$(DATA_DIR)/man/man1/pacman-pkgdiff.1
	scdoc < files/docs/shell/plot.scd                         > $(DESTDIR)$(DATA_DIR)/man/man1/plot.1
	scdoc < files/docs/shell/pomodoro.scd                     > $(DESTDIR)$(DATA_DIR)/man/man1/pomodoro.1
	scdoc < files/docs/shell/project-path.scd                 > $(DESTDIR)$(DATA_DIR)/man/man1/project-path.1
	scdoc < files/docs/shell/query-hosts-tags.scd             > $(DESTDIR)$(DATA_DIR)/man/man1/query-hosts-tags.1
	scdoc < files/docs/shell/read-news.scd                    > $(DESTDIR)$(DATA_DIR)/man/man1/read-news.1
	scdoc < files/docs/shell/redis-env.scd                    > $(DESTDIR)$(DATA_DIR)/man/man1/redis-env.1
	scdoc < files/docs/shell/repo.scd                         > $(DESTDIR)$(DATA_DIR)/man/man1/repo.1
	scdoc < files/docs/shell/screenshot.scd                   > $(DESTDIR)$(DATA_DIR)/man/man1/screenshot.1
	scdoc < files/docs/shell/somafm.scd                       > $(DESTDIR)$(DATA_DIR)/man/man1/somafm.1
	scdoc < files/docs/shell/ssh-tags.scd                     > $(DESTDIR)$(DATA_DIR)/man/man1/ssh-tags.1
	scdoc < files/docs/shell/status.scd                       > $(DESTDIR)$(DATA_DIR)/man/man1/status.1
	scdoc < files/docs/shell/tmux-env.scd                     > $(DESTDIR)$(DATA_DIR)/man/man1/tmux-env.1
	scdoc < files/docs/shell/weechat-fifo.scd                 > $(DESTDIR)$(DATA_DIR)/man/man1/weechat-fifo.1
