NIGHT-MODE(1perso)

# NAME

night-mode - Manage night mode

# SYNOPSIS

night-mode [ *status* | *enable* | *disable* | *toggle* ]

# DESCRIPTION

Manage night mode

# OPTIONS

None

# OPERANDS

*status*
	Display whether the night mode is "enabled" or "disabled"++
This is the default action if none is specified

*enable*
	Enable night mode

*disable*
	Disable night mode

*toggle*
	Toggle night mode

# ENVIRONMENT VARIABLES

None

# FILES

None

# DEPENDENCIES

- gammastep
- pidof
- pkill
