open-document(1perso)

# NAME

open-document - Interactive selection to open document

# SYNOPSIS

open-document

# DESCRIPTION

Open interface to select a document and open it.

The document are searched within the home folder.
Hidden root folders are excluded from the search.

A document is defined as having a "pdf" extension.

# OPTIONS

None

# OPERANDS

None

# ENVIRONMENT VARIABLES

None

# FILES

None

# DEPENDENCIES

- bemenu
- xdg-open
