pick-task(1perso)

# NAME

pick-task - Interactive pick of a task

# SYNOPSIS

pick-task

# DESCRIPTION

Open interface to pick a task:
- choose whether to log it or not at the end
- start a pomodoro session (optional)
- enable "Do not disturb" mode (optional)

# OPTIONS

None

# OPERANDS

None

# ENVIRONMENT VARIABLES

None

# FILES

None

# DEPENDENCIES

- do-not-disturb
- fzf
- pomodoro
- task
