screenshot(1perso)

# NAME

screenshot - Take a screenshot of a region

# SYNOPSIS

screenshot

# DESCRIPTION

Open screen overlay to select a region to screenshot. The image is saved in the
Desktop folder.

# OPTIONS

None

# OPERANDS

None

# ENVIRONMENT VARIABLES

_XDG_DESKTOP_DIR_
	Path to user-specific desktop directory++
If unset, defaults to $HOME/Desktop

# FILES

_$XDG_DESKTOP_DIR_
	Target directory to contain the images

# DEPENDENCIES

- grim
- slurp
