start-task(1perso)

# NAME

start-task - Interactive start of a task

# SYNOPSIS

start-task

# DESCRIPTION

Open interface to start a task:
- choose whether to log it or not at the end
- start a pomodoro session (optional)
- enable "Do not disturb" mode (optional)

# OPTIONS

None

# OPERANDS

None

# ENVIRONMENT VARIABLES

None

# FILES

None

# DEPENDENCIES

- do-not-disturb
- fzf
- pomodoro
- task
