start-task(1)

# NAME

start-task - Interactive start of a task

# SYNOPSIS

start-task [_fzf_options_...]

# DESCRIPTION

Open interface to start a task:
- start time tracker
- start a pomodoro session (optional)
- enable "Do not disturb" mode (optional)

# OPTIONS

None

# OPERANDS

_fzf_option_
	*fzf* option

# ENVIRONMENT VARIABLES

None

# FILES

None

# DEPENDENCIES

- do-not-disturb
- fzf
- pomodoro
- time-tracker
