time-tracker(1)

# NAME

time-tracker - Track tasks duration

# SYNOPSIS

time-tracker *start* _id_ [ _description_ ]

time-tracker [ *ids* | *status* | *stop* ]

# DESCRIPTION

Manager tasks duration tracking

# OPERANDS

*ids*
	List all existing task identifiers

*start*
	Start session

*status*
	Display current task if session active++
This is the default action if none is specified

*stop*
	End session

_id_
	Task identifier

_description_
	Task description
