all: zathura-configs

zathura-configs:
	setup/setup-config zathura/zathurarc               $(CONFIG_DIR)/zathura/zathurarc
	setup/setup-config zathura/config.d/bindings       $(CONFIG_DIR)/zathura/config.d/bindings
	setup/setup-config zathura/config.d/clean-bindings $(CONFIG_DIR)/zathura/config.d/clean-bindings
	setup/setup-config zathura/config.d/general        $(CONFIG_DIR)/zathura/config.d/general
	setup/setup-config zathura/config.d/style          $(CONFIG_DIR)/zathura/config.d/style
