all: fuzzel-configs

fuzzel-configs:
	setup/setup-config fuzzel/fuzzel.ini            $(CONFIG_DIR)/fuzzel/fuzzel.ini
	setup/setup-config fuzzel/config.d/bindings.ini $(CONFIG_DIR)/fuzzel/config.d/bindings.ini
	setup/setup-config fuzzel/config.d/general.ini  $(CONFIG_DIR)/fuzzel/config.d/general.ini
	setup/setup-config fuzzel/config.d/style.ini    $(CONFIG_DIR)/fuzzel/config.d/style.ini
