notes:
	@echo -n "… setup notes"

    # create necessary directories
	@mkdir -p "$(CONFIG_DIR)/notes"

    # copy config files
	@cp "notes/config" "$(CONFIG_DIR)/notes/config"

	@echo -e "\r✔ setup notes"
