# tabs management
config.unbind('K', mode='normal')
config.unbind('J', mode='normal')
config.unbind('d', mode='normal')
config.unbind('D', mode='normal')
config.unbind('<Ctrl-W>', mode='normal')
config.bind('<Alt-1>', 'tab-focus 1', mode='normal')
config.bind('<Alt-2>', 'tab-focus 2', mode='normal')
config.bind('<Alt-3>', 'tab-focus 3', mode='normal')
config.bind('<Alt-4>', 'tab-focus 4', mode='normal')
config.bind('<Alt-5>', 'tab-focus 5', mode='normal')
config.bind('<Alt-6>', 'tab-focus 6', mode='normal')
config.bind('<Alt-7>', 'tab-focus 7', mode='normal')
config.bind('<Alt-8>', 'tab-focus 8', mode='normal')
config.bind('<Alt-9>', 'tab-focus 9', mode='normal')
config.bind('<Alt-0>', 'tab-focus 10', mode='normal')
config.bind('<Space>ta', 'tab-focus last', mode='normal')
config.bind('<Space>tp', 'tab-prev', mode='normal')
config.bind('<Space>tn', 'tab-next', mode='normal')
config.bind('<Space>tc', 'set-cmd-text -s :open -t ', mode='normal')
config.bind('<Space>tx', 'tab-close', mode='normal')
config.bind('<Space>tr', 'set-cmd-text -s :open ', mode='normal')
config.bind('gt', 'tab-focus', mode='normal')
config.bind('gT', 'tab-prev', mode='normal')
config.bind('X', 'tab-close', mode='normal')

# zooming
config.unbind('-', mode='normal')
config.unbind('+', mode='normal')
config.unbind('=', mode='normal')
config.bind('<Ctrl-->', 'zoom-out', mode='normal')
config.bind('<Ctrl-Shift-+>', 'zoom-in', mode='normal')
config.bind('<Ctrl-=>', 'zoom', mode='normal')
