# tabs closing
config.unbind('d', mode='normal')
config.unbind('D', mode='normal')
config.unbind('<Ctrl-W>', mode='normal')
config.bind('X', 'tab-close', mode='normal')

# tabs navigation
config.unbind('K', mode='normal')
config.unbind('J', mode='normal')
config.bind('<Alt-H>', 'tab-prev', mode='normal')
config.bind('<Alt-L>', 'tab-next', mode='normal')
config.bind('<Alt-1>', 'tab-focus 1', mode='normal')
config.bind('<Alt-2>', 'tab-focus 2', mode='normal')
config.bind('<Alt-3>', 'tab-focus 3', mode='normal')
config.bind('<Alt-4>', 'tab-focus 4', mode='normal')
config.bind('<Alt-5>', 'tab-focus 5', mode='normal')
config.bind('<Alt-6>', 'tab-focus 6', mode='normal')
config.bind('<Alt-7>', 'tab-focus 7', mode='normal')
config.bind('<Alt-8>', 'tab-focus 8', mode='normal')
config.bind('<Alt-9>', 'tab-focus 9', mode='normal')
config.bind('<Alt-0>', 'tab-focus 10', mode='normal')
config.bind('<Alt-`>', 'tab-focus last', mode='normal')
config.bind('gt', 'tab-focus', mode='normal')
config.bind('gT', 'tab-prev', mode='normal')
