translate-shell:
	$(start_setup)

    # create necessary directories
	@mkdir -p "$(CONFIG_DIR)/translate-shell"

    # copy config files
	@cp "translate-shell/init.trans" "$(CONFIG_DIR)/translate-shell/init.trans"

	$(end_setup)
