translate-shell:
	@echo -n "… setup translate-shell"

    # create necessary directories
	@mkdir -p "$(CONFIG_DIR)/translate-shell"

    # copy config files
	@cp "translate-shell/init.trans" "$(CONFIG_DIR)/translate-shell/init.trans"

	@echo -e "\r✔ setup translate-shell"
