all: keywords

keywords:
	mkdir -p $(DESTDIR)$(DATA_DIR)/keywords

	cp files/data/keywords/http   $(DESTDIR)$(DATA_DIR)/keywords/http
	cp files/data/keywords/mysql  $(DESTDIR)$(DATA_DIR)/keywords/mysql
