all: keywords

keywords:
	mkdir -p $(DESTDIR)$(DATA_DIR)/keywords

	cp files/data/keywords/http   $(DESTDIR)$(DATA_DIR)/keywords/http
	cp files/data/keywords/influx $(DESTDIR)$(DATA_DIR)/keywords/influx
	cp files/data/keywords/mysql  $(DESTDIR)$(DATA_DIR)/keywords/mysql
	cp files/data/keywords/redis  $(DESTDIR)$(DATA_DIR)/keywords/redis
