aria2: aria2-configs
coreutils: coreutils-configs
fontconfig: fontconfig-configs
git: git-configs git-docs git-scripts
gnupg: gnupg-configs
htop: htop-configs
httpie: httpie-configs
i3blocks: i3blocks-configs i3blocks-docs i3blocks-scripts
less: less-configs
libqalculate: libqalculate-configs
mako: mako-configs
mopidy: mopidy-configs
ncmpcpp: ncmpcpp-configs
neomutt: neomutt-configs
newsboat: newsboat-configs
openssh: openssh-configs
qutebrowser: qutebrowser-configs
sway: sway-configs sway-docs sway-scripts
swaylock: swaylock-configs
systemd: systemd-configs
termite: termite-configs
tmux: tmux-configs tmux-docs tmux-scripts
translate-shell: translate-shell-configs
universal-ctags: universal-ctags-configs
util-linux: util-linux-configs
vim: vim-configs
weechat: weechat-configs
xdg-user-dirs: xdg-user-dirs-configs
xdg-utils: xdg-utils-configs
zathura: zathura-configs
zsh: zsh-configs shell-docs shell-scripts
