aerc: aerc-configs
aria2: aria2-configs
bat: bat-configs
coreutils: coreutils-configs
ctags: ctags-configs
fontconfig: fontconfig-configs
foot: foot-configs
fuzzel: fuzzel-configs
gammastep: gammastep-configs
git: git-configs git-docs git-scripts
gnupg: gnupg-configs
htop: htop-configs
httpie: httpie-configs
i3blocks: i3blocks-configs i3blocks-scripts
imv: imv-configs
isync: isync-configs
khard: khard-configs
less: less-configs
libqalculate: libqalculate-configs
mako: mako-configs
misc: misc-configs
mpd: mpd-configs
neovim: neovim-configs
openssh: openssh-configs
pulsemixer: pulsemixer-configs
qutebrowser: qutebrowser-configs
remind: remind-configs
ripgrep: ripgrep-configs
sfeed: sfeed-configs
sway: sway-configs sway-docs sway-scripts
swayidle: swayidle-configs
swaylock: swaylock-configs
systemd: systemd-configs
tmux: tmux-configs tmux-docs tmux-scripts
tofi: tofi-configs
translate-shell: translate-shell-configs
vdirsyncer: vdirsyncer-configs
w3m: w3m-configs
wayprompt: wayprompt-configs
weechat: weechat-configs
zathura: zathura-configs
zsh: zsh-configs shell-docs shell-scripts
