all: mako-configs

mako-configs:
	setup/setup-config mako/config           $(CONFIG_DIR)/mako/config
	setup/setup-config mako/config.d/general $(CONFIG_DIR)/mako/config.d/general
	setup/setup-config mako/config.d/style   $(CONFIG_DIR)/mako/config.d/style
