window:
  padding:
    x: 2
    y: 2

font:
  size: 18.0

draw_bold_text_with_bright_colors: false

colors:
  primary:
    background: '0x{color/base09/hex}'
    foreground: '0x{color/base00/hex}'
  selection:
    text:       '0x{color/base09/hex}'
    background: '0x{color/base00/hex}'

mouse:
  hide_when_typing: true
  url:
    modifiers: Control

selection:
  semantic_escape_chars: "/-,│`|:\"' ()[]{}<>"

key_bindings:
  - { key: Q,        mods: Control|Shift, action: Quit             }

  - { key: Equals,   mods: Control,       action: ResetFontSize    }
  - { key: Add,      mods: Control|Shift, action: IncreaseFontSize }
  - { key: Subtract, mods: Control,       action: DecreaseFontSize }

  - { key: V,        mods: Control|Shift, action: Paste            }
  - { key: C,        mods: Control|Shift, action: Copy             }
