all: alacritty-configs

alacritty-configs:
	$(start_setup)

	mkdir -p $(DESTDIR)$(CONFIG_DIR)/alacritty

	$(setup_file)/configs/alacritty/alacritty.yml > $(DESTDIR)$(CONFIG_DIR)/alacritty/alacritty.yml
