#!/usr/bin/env zsh

NAME="$1"
EXTRA="${@:2}"


function frame {
  # put some whitespaces before
  # so that the cursor is not over the display
  echo -ne "    $1\033[0K\r"
  sleep 0.2
}

function fliptable {
  local text="$1"
  local upside_down_text=$( upside_down ${text} )

  if [[ -n "${text}" ]]; then
    frame "( °-°) ${text}"
    frame "( °-°) ${text}"
    frame "( °-°) ${text}"
    frame "( °-°) ${text}"
    frame "( °□°) ${text}"
    frame "(╯°□°)╯${text}"
    frame "(╯°□°)╯︵ ${upside_down_text}"
    frame "(╯°□°)╯        ${upside_down_text}"
    frame "(╯°□°)╯           ${upside_down_text}"
  else
    frame '( °-°) ┬─┬'
    frame '( °-°) ┬─┬'
    frame '( °-°) ┬─┬'
    frame '( °-°) ┬─┬'
    frame '( °□°) ┬─┬'
    frame '(╯°□°)╯┬─┬'
    frame '(╯°□°)╯︵ ┻━┻'
    frame '(╯°□°)╯        ┻━┻'
    frame '(╯°□°)╯           ┻━┻'
  fi

  echo
}

function cool {
  frame '( •_•)'
  frame '( •_•)'
  frame '( •_•)'
  frame '( •_•)'
  frame '( •_•)     ⌐■-■'
  frame '( •_•)   ⌐■-■'
  frame '( •_•)>⌐■-■'
  frame '(⌐■_■)'
  echo
}

function shrug {
  frame '_╭-(ツ)-╮_'
  frame '_╭-(ツ)-╮_'
  frame '_╭-(ツ)-╮_'
  frame '_╭-(ツ)-╮_'
  frame '¯\_(ツ)_/¯'
  echo
}

function disapprove {
  frame 'ʘ‿ʘ'
  frame 'ʘ‿ʘ'
  frame 'ʘ‿ʘ'
  frame 'ʘ‿ʘ'
  frame 'ʘ_ʘ'
  frame 'ʘ_ʘ'
  frame 'ಠ_ಠ'
  echo
}

function happygary {
  frame 'ᕕ(ᐛ)ᕗ'
  frame 'ᕕ(ᐛ)ᕗ'
  frame 'ᕙ(ᐖ)ᕡ'
  frame 'ᕙ(ᐖ)ᕡ'
  frame 'ᕕ(ᐛ)ᕗ'
  frame 'ᕕ(ᐛ)ᕗ'
  frame 'ᕙ(ᐖ)ᕡ'
  frame 'ᕙ(ᐖ)ᕡ'
  frame 'ᕕ(ᐛ)ᕗ'
  echo
}


$NAME $EXTRA 2> /dev/null
