#!/usr/bin/env zsh

COMMAND=${0:t}

init_variables() {
  ENV_DIR_PATH="${XDG_CONFIG_HOME:-$HOME/.config}/http-prompt/env"

  ENV_PATH=
}


usage() {
  cat << EOF
usage: ${COMMAND} [<options>] project [environment]

Start http-prompt with a custom project environment

Options:
  -h,  --help    show this message only
EOF
}


error() {
  [[ -z "$1" ]] || echo "$1" >&2
  usage
  exit 1
}


parse_options() {
  while [[ "$#" -gt 0 ]]; do
    case "$1" in
      -h|--help)
        usage
        exit 0
        ;;
      *)
        break 2
        ;;
    esac
  done

  if [[ -n "$2" ]]; then
    ENV_PATH="${ENV_DIR_PATH}/$1/$2.hp"
  else
    ENV_PATH="${ENV_DIR_PATH}/$1.hp"
  fi
}


validate_options() {
  if [[ ! -f "${ENV_PATH}" ]]; then
    error 'invalid project or environment'
  fi
}


init_variables
parse_options "$@"
validate_options

http-prompt --env "${ENV_PATH}"
