#!/usr/bin/env zsh

COMMAND=${0:t}

init_variables() {
  ENV_DIR_PATH="${XDG_CONFIG_HOME:-$HOME/.config}/http-prompt/env"

  PROJECT=
  ENVIRONMENT=
  ENV_PATH=
}


usage() {
  cat << EOF
usage: ${COMMAND} [<options>] project environment

Start http-prompt with a custom project environment

Options:
  -h,  --help    show this message only
EOF
}


error() {
  [[ -z "$1" ]] || echo "${COMMAND}: $1" >&2
  echo "Try '${COMMAND} --help' for more information."
  exit 1
}


parse_options() {
  while [[ "$#" -gt 0 ]]; do
    case "$1" in
      -h|--help)
        usage
        exit 0
        ;;
      *)
        break 2
        ;;
    esac
  done

  PROJECT="$1"
  ENVIRONMENT="$2"
}


validate_options() {
  if [[ -z "${PROJECT}" ]]; then
    error 'missing project'
  fi

  if [[ -z "${ENVIRONMENT}" ]]; then
    error 'missing environment'
  fi

  ENV_PATH="${ENV_DIR_PATH}/${PROJECT}/${ENVIRONMENT}.hp"

  if [[ ! -f "${ENV_PATH}" ]]; then
    error 'invalid project/environment'
  fi
}


init_variables
parse_options "$@"
validate_options

http-prompt --env "${ENV_PATH}"
