#! /usr/bin/env zsh

TEXT="$@"

RESULT_TEXT=

# can't use tr on non ascii characters...
for (( i=0; i<${#TEXT}; i++ )); do
  case "${TEXT:$i:1}" in
    'a') RESULT_TEXT+='ɐ' ;;
    'b') RESULT_TEXT+='q' ;;
    'c') RESULT_TEXT+='ɔ' ;;
    'd') RESULT_TEXT+='p' ;;
    'e') RESULT_TEXT+='ǝ' ;;
    'f') RESULT_TEXT+='ɟ' ;;
    'g') RESULT_TEXT+='ɓ' ;;
    'h') RESULT_TEXT+='ɥ' ;;
    'i') RESULT_TEXT+='ᴉ' ;;
    'j') RESULT_TEXT+='ɾ' ;;
    'k') RESULT_TEXT+='ʞ' ;;
    'l') RESULT_TEXT+='l' ;;
    'm') RESULT_TEXT+='ɯ' ;;
    'n') RESULT_TEXT+='u' ;;
    'o') RESULT_TEXT+='o' ;;
    'p') RESULT_TEXT+='d' ;;
    'q') RESULT_TEXT+='b' ;;
    'r') RESULT_TEXT+='ɹ' ;;
    's') RESULT_TEXT+='s' ;;
    't') RESULT_TEXT+='ʇ' ;;
    'u') RESULT_TEXT+='n' ;;
    'v') RESULT_TEXT+='ʌ' ;;
    'w') RESULT_TEXT+='ʍ' ;;
    'x') RESULT_TEXT+='x' ;;
    'y') RESULT_TEXT+='ʎ' ;;
    'z') RESULT_TEXT+='z' ;;
    ' ') RESULT_TEXT+=' ' ;;
  esac
done

echo "$RESULT_TEXT" | rev
