# ensure we have the correct locale set
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# needed for use of GnuPG Curses based Pinentry
export GPG_TTY=$(tty)

# Skip Ubuntu main compinit
skip_global_compinit=1
