# ensure we have the correct locale set
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# Skip Ubuntu main compinit
skip_global_compinit=1

# following configs could be in zshrc config file
# but they are moved here mainly for some tmux use cases
# where a non interactive shell is invoked for running commands

# needed for use of GnuPG Curses based Pinentry
export GPG_TTY=$(tty)

# enable extended globbing features
setopt extended_glob

# add personal functions directories
fpath=(
  "${HOME}/.zsh/functions"/**/
  $fpath
)

# autoload all functions
for func in "${HOME}/.zsh/functions"/**/*(.); do
  autoload -Uz "${func##*/}"
done
