# define and load plugins
source "${HOME}/.zsh/plugins.zsh"

# enable extended globbing features
setopt extended_glob

# load all individual configs with their possible
# local extension/override immediately afterwards
function load_conf() {
  local local_conf
  for conf in "${HOME}/.zsh/conf/"*[^.local].zsh; do
    source "${conf}"

    local_conf="${conf%.*}.local.zsh"
    if [[ -f "${local_conf}" ]]; then
      source "${local_conf}"
    fi
  done
}

load_conf

unset -f load_conf

eval $( dircolors "${HOME}/.dircolors" )

# enable changing directories without typing cd
setopt auto_cd

# Disable flow control (Ctrl-q/Ctrl-s)
setopt no_flow_control
# setopt doesn't seem to be enough when using vim within tmux...
stty -ixon

# reuse ssh-agent across ttys
ssh-add -l &>/dev/null
if [ "$?" -eq 2 ]; then
  test -r ~/.cache/ssh-agent && \
  eval "$(<~/.cache/ssh-agent)" >/dev/null

  ssh-add -l &>/dev/null
  if [ "$?" -eq 2 ]; then
    (umask 066; ssh-agent > ~/.cache/ssh-agent)
    eval "$(<~/.cache/ssh-agent)" >/dev/null
  fi
fi

# Fish-like autosuggestions
source /usr/local/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE=fg=10

# important to source the syntax highlighting at the end
# because it needs all widgets to be already created
source /usr/local/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
