# load plugins manager
source ~/.zplug/init.zsh

# enable extended globbing features
setopt extendedglob

# load all individual configs with their possible
# local extension/override immediately afterwards
function load_conf() {
  local local_conf
  for conf in ~/.zsh/*[^.local].zsh; do
    source "${conf}"

    local_conf="${conf%.*}.local.zsh"
    if [[ -f "${local_conf}" ]]; then
      source "${local_conf}"
    fi
  done
}

load_conf

unset -f load_conf

# Disable flow control (Ctrl-q/Ctrl-s)
setopt noflowcontrol
