# load plugins manager
source ~/.zplug/init.zsh

# load all individual configs
# with their possible local extension/override
function load_conf() {
  local local_conf
  for conf in ~/.zsh/*.zsh; do
    source "${conf}"

    local_conf="${conf%.*}.local.zsh"
    if [[ -f "${local_conf}" ]]; then
      source "${local_conf}"
    fi
  done
}

load_conf

unset -f load_conf
