#!/bin/sh
# commands used:
# - curl
# - git

NAME="$1"
DESTDIR="$2"
TYPE="$3"
URL="$4"
ARG="$5"

PLUGIN_DIR="${DESTDIR}${HOME}/.vim/pack/${NAME}/start/${NAME}"

mkdir -p "${PLUGIN_DIR%/*}"

install_git_plugin() {
  if [ ! -d "${PLUGIN_DIR}" ]; then
    git clone -q "${URL}" "${PLUGIN_DIR}"
  elif [ ! -d "${PLUGIN_DIR}/.git" ]; then
    rm -rf "${PLUGIN_DIR}"
    git clone -q "${URL}" "${PLUGIN_DIR}"
  else
    git -C "${PLUGIN_DIR}" fetch -q
  fi \
    && git -C "${PLUGIN_DIR}" checkout -q "${ARG}"

  if [ "$?" -ne 0 ]; then
    return 1
  fi

  if [ -n "${DESTDIR}" ]; then
    # remove .git history on remote installations
    rm -rf "${PLUGIN_DIR}/.git"
  fi
}

install_file_plugin() {
  mkdir -p "${PLUGIN_DIR}/${ARG%/*}"
  curl -sL "${URL}" -o "${PLUGIN_DIR}/${ARG}"
}

case "${TYPE}" in
  git)  install_git_plugin ;;
  file) install_file_plugin ;;
  *) exit 1
esac
