#!/bin/sh
# commands used:
# - curl
# - git

NAME="$1"
TYPE="$2"
URL="$3"
ARG="$4"

PLUGIN_DIR="${HOME}/.vim/pack/${NAME}/start/${NAME}"

install_git_plugin() {
  if [ ! -d "${PLUGIN_DIR}" ]; then
    git clone -q "${URL}" "${PLUGIN_DIR}"
  else
    git -C "${PLUGIN_DIR}" fetch -q
  fi

  git -C "${PLUGIN_DIR}" checkout -q "${ARG}"
}

install_file_plugin() {
  mkdir -p "${PLUGIN_DIR}/${ARG%/*}"
  curl -sL "${URL}" -o "${PLUGIN_DIR}/${ARG}"
}

case "${TYPE}" in
  git)  install_git_plugin ;;
  file) install_file_plugin ;;
  *) exit 1
esac
