#!/bin/sh

BIN_DIR="${DESTDIR}${HOME}/.local/bin"
SCRIPT_NAME="$( basename "$1" )"

mkdir -p "${BIN_DIR}"

if grep -q '{color/' "files/scripts/$1"; then
  THEME=dark setup/process-file "scripts/$1" > "${BIN_DIR}/${SCRIPT_NAME}-dark"
  chmod +x "${BIN_DIR}/${SCRIPT_NAME}-dark"
  THEME=light setup/process-file "scripts/$1" > "${BIN_DIR}/${SCRIPT_NAME}-light"
  chmod +x "${BIN_DIR}/${SCRIPT_NAME}-light"
  ln -sf "${BIN_DIR}/${SCRIPT_NAME}-${THEME}" "${BIN_DIR}/${SCRIPT_NAME}"
else
  setup/process-file "scripts/$1" > "${BIN_DIR}/${SCRIPT_NAME}"
  chmod +x "${BIN_DIR}/${SCRIPT_NAME}"
fi
