#!/bin/sh

BIN_DIR="${HOME}/.local/bin"
SCRIPT_NAME="$( basename "$1" )"

mkdir -p "${DESTDIR}${BIN_DIR}"

if grep -q '{color/' "files/scripts/$1"; then
  THEME=dark setup/process-file "scripts/$1" > "${DESTDIR}${BIN_DIR}/${SCRIPT_NAME}-dark"
  chmod +x "${DESTDIR}${BIN_DIR}/${SCRIPT_NAME}-dark"
  THEME=light setup/process-file "scripts/$1" > "${DESTDIR}${BIN_DIR}/${SCRIPT_NAME}-light"
  chmod +x "${DESTDIR}${BIN_DIR}/${SCRIPT_NAME}-light"
  ln -sf "${SCRIPT_NAME}-${THEME}" "${DESTDIR}${BIN_DIR}/${SCRIPT_NAME}"

  if ! grep -qsxF "$2" "${THEME_FILES}"; then
    mkdir -p "$( dirname "${THEME_FILES}" )"
    echo "${BIN_DIR}/${SCRIPT_NAME}" >> "${THEME_FILES}"
  fi
else
  setup/process-file "scripts/$1" > "${DESTDIR}${BIN_DIR}/${SCRIPT_NAME}"
  chmod +x "${DESTDIR}${BIN_DIR}/${SCRIPT_NAME}"
fi
