#!/bin/sh

mkdir -p "${DESTDIR}$( dirname "$2" )"

if grep -q '{color/' "files/configs/$1"; then
  THEME=dark setup/setup-file "configs/$1" > "${DESTDIR}$2-dark"
  THEME=light setup/setup-file "configs/$1" > "${DESTDIR}$2-light"
  ln -sf "${DESTDIR}$2-${THEME}" "${DESTDIR}$2"
else
  setup/setup-file "configs/$1" > "${DESTDIR}$2"
fi
