#!/bin/sh

TMP_SCRIPT_FILE=$( mktemp )
trap 'rm "${TMP_SCRIPT_FILE}"' EXIT

FOLDERS_FILE="defs/folders"

{
  while read -r line; do
    alias=$( echo "${line}" | cut -f1 -d' ' )
    path=$( echo "${line}" | tr -s ' ' | cut -f2 -d' ' )
    path=$( eval "echo ${path}" )
    echo "s|{folder/${alias}}|${path}|g"
  done < "${FOLDERS_FILE}"
} > "${TMP_SCRIPT_FILE}"

sed -f "${TMP_SCRIPT_FILE}" -
