#!/bin/sh

SCRIPT_FILE="build/substitute-dirs"

if [ -f "${SCRIPT_FILE}" ]; then
  sed -f "${SCRIPT_FILE}" -
  exit
fi

DIRS_FILE="config/dirs"

mkdir -p build

{
  while read -r LINE; do
    ALIAS=$( echo "${LINE}" | cut -f1 -d' ' )
    DIR_PATH=$( echo "${LINE}" | tr -s ' ' | cut -f2 -d' ' )
    DIR_PATH=$( eval "echo ${DIR_PATH}" )
    echo "s|{dir/${ALIAS}}|${DIR_PATH}|g"
  done < "${DIRS_FILE}"
} > "${SCRIPT_FILE}"

sed -f "${SCRIPT_FILE}" -
