all: tmux-docs

tmux-docs:
	setup/setup-doc tmux/tmux-extract-tokens
	setup/setup-doc tmux/tmux-move-pane-window-index
	setup/setup-doc tmux/tmux-move-window-index
	setup/setup-doc tmux/tmux-notify-alert
	setup/setup-doc tmux/tmux-select-pane-vim
	setup/setup-doc tmux/tmux-send-vim
	setup/setup-doc tmux/tmux-switch-session
	setup/setup-doc tmux/tmux-toggle-monitoring
	setup/setup-doc tmux/tmux-toggle-no-distraction
