TMUX-SWITCH(1perso)

# NAME

tmux-switch - Interactive selection to switch session or window

# SYNOPSIS

tmux-switch [ *session* | *window* ] [_option_...]

# DESCRIPTION

Open interface to allow the selection of a session or window to switch to.

# OPTIONS

_option_
	*fzf-tmux* option

# OPERANDS

*session*
	Switch session

*window*
	Switch window

# ENVIRONMENT VARIABLES

None

# FILES

None

# DEPENDENCIES

- fzf-tmux
- tmux
