tmux-move-window-index(1perso)

# NAME

tmux-move-window-index - Move current window within session

# SYNOPSIS

tmux-move-window-index _index_

# DESCRIPTION

Move the current tmux window within the session at desired index. It supports
indexes which are not part of the current windows indexes.

# OPTIONS

None

# OPERANDS

_index_
	Index to move the window to

# ENVIRONMENT VARIABLES

None

# FILES

None

# DEPENDENCIES

- tmux
