tmux-notify-alert(1)

# NAME

tmux-notify-alert - Handle a tmux alert for notification

# SYNOPSIS

tmux-notify-alert _type_ _socket_path_ _session_id_ _window_id_

# OPERANDS

_type_
	Type of alert (activity, bell, silence)

_socket_path_
	tmux socket path where the alert is coming from

_session_id_
	tmux session id where the alert is coming from

_window_id_
	tmux window id where the alert is coming from
