query-hosts-tags(1)

# NAME

query-hosts-tags - Query the hosts tags file

# DESCRIPTION

A "tags" query displays the tags from the host argument++
A "hosts" query displays the hosts matching the tags arguments++
Without any argument, it displays all the hosts

# SYNOPSIS

query-hosts-tags

query-hosts-tags hosts [_tag_=_value_...]

query-hosts-tags tags _host_

# OPERANDS

_host_
	Host to display tags of

_tag_=_value_
	Couple _tag_/_value_ to filter the hosts to display
