all: foot-configs

foot-configs:
	setup/setup-config foot/foot.ini              $(CONFIG_DIR)/foot/foot.ini
	setup/setup-config foot/config.d/bindings.ini $(CONFIG_DIR)/foot/config.d/bindings.ini
	setup/setup-config foot/config.d/general.ini  $(CONFIG_DIR)/foot/config.d/general.ini
	setup/setup-config foot/config.d/style.ini    $(CONFIG_DIR)/foot/config.d/style.ini
